### ISSUE TITLE
Write and unit test `MultisigModule`

### ISSUE THREAD

**Issue by asaj** [hyperlane-xyz/hyperlane-monorepo#1001]
This ticket is for smart contract changes and unit testing only.

Requires implementing the following interface for a simple m-of-n ECDSA multisig.

Note that unlike previous `ValidatorManager` contracts, contracts that implement this interface should be able to validate sovereign data for all domains.

```
interface IInterchainSecurityModule {
    enum ModuleType {
        MULTISIG
    }

    // Used by relayers to determine how to structure sovereign data.
    function moduleType() external view returns (ModuleType);

    // Called by the Mailbox to determine whether the provided root
    // is valid to verify proofs against.
    function accept(
        bytes32 _root,
        uint256 _index,
        bytes calldata _data,
        bytes calldata _message
    ) external returns (bool);
}


interface IMultisigModule is Ownable, IInterchainSecurityModule {
    function enrollValidator(uint32 _domain, address _validator);
    function unenrollValidator(uint32 _domain, address _validator);
    function setThreshold(uint32 _domain, uint256 _threshold);
    function validators(uint32 _domain)
        external
        view
        returns (address[] memory);
}
```

**Comment by yorhodes** [comment]
unclear to me that the `type` enumeration is useful
maybe adopt [EIP712](https://eips.ethereum.org/EIPS/eip-712) type hashes

**Comment by jennifermarie** [comment]
@asaj is this ticket still relevant with the re-scoping of Sovereign Consensus / Hyperlane v2?

**Comment by asaj** [comment]
@jennifermarie yes

**Comment by asaj** [comment]
Making a note with some design ideas:
- `RouterModule` which takes a message and returns an ISM
- `CombinationModule` which can express boolean clauses of modules
- per-origin-domain `MultisigModules`, like we have with IVMs
