### ISSUE TITLE
Update Inboxes to expose `domainHash()`

### ISSUE THREAD

**Issue by asaj** [hyperlane-xyz/hyperlane-monorepo#1002]
In the current design, every mailbox has an associated `domainHash()`, used as a domain separator to ensure that validator signatures cannot be replayed on different mailboxes.

 Right now, this `domainHash()` is stored in the `[Out|In]boxValidatorManager` contracts. This works because there is a 1:1 mapping between mailboxes and `ValidatorManagers`; each `Mailbox` can look to its `ValidatorManager` for its `domainHash`.

With the replacement of `ValidatorManagers` with [sovereign ValidatorManagers](https://github.com/abacus-network/abacus-monorepo/issues/1001), this 1:1 mapping will no longer exist; each `Mailboxes` will not have a single `ValidatorManager` at which it can query its `domainHash()`.

To address this, we should move `domainHash()` from the `ValidatorManager` contracts to the `Inbox` contracts.

**Comment by jennifermarie** [comment]
@asaj is this ticket still relevant with the re-scoping of Sovereign Consensus / Hyperlane v2?

**Comment by asaj** [comment]
Closing in favor of more up to date tickets
