### ISSUE TITLE
Hyperlane v2 contract audit

### ISSUE THREAD

**Issue by asaj** [hyperlane-xyz/hyperlane-monorepo#1070]
Probably engage the same firms as last time

**Comment by augustjest** [comment]
Hey, just familiarizing myself with hyperlane and saw this....[Macro](https://0xmacro.com/) is an up and coming auditing firm if you haven't heard of them. They have really in-depth audit reports. Here's an example of how in-depth their reports are compared to other firms https://github.com/PeggyJV/aave-v2-cellar/tree/main/audits. (no, I don't work for them -- this is just word of mouth)
