### ISSUE TITLE
Show handle tx calldata for unprocessed messages

### ISSUE THREAD

**Issue by jmrossy** [hyperlane-xyz/hyperlane-monorepo#1091]
The explorer is not perfect in showing reversions, or even if it does revert, the execution might not be clear to the user/developer. Tenderly is a great tool that helps with that, but developers can't easily construct the handle tx calldata. This ticket would be to show that so users can plug it into tenderly themselves.

~~When a tx reverts, show the developer the execution.~~

**Comment by nambrot** [comment]
I would probably punt on this for now since I don't think this looks like easily doable right now

**Comment by nambrot** [comment]
I would actually change this ticket to just show the handle tx calldata so that folks can plug that into Tenderly themselves with a tooltip or something. It has been imo very helpful to developers
