### ISSUE TITLE
Use Solidity custom errors

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1097]
Solidity 0.8 introduced more gas efficient custom errors: https://blog.soliditylang.org/2021/04/21/custom-errors/

@yorhodes tried to do it when deploying v1 but ran into issues with existing code not being able to handle custom errors well. IIUC, this actually still would be an issue anyways with application contracts containing those, but luckily ethers-rs recently seemed to have fixed it https://github.com/gakonst/ethers-rs/pull/1549

**Comment by yorhodes** [comment]
https://github.com/hyperlane-xyz/abacus-monorepo/pull/538/

**Comment by asaj** [comment]
@nambrot @yorhodes do we still want to do this? Custom errors are significantly less readable, than strings, no?

**Comment by yorhodes** [comment]
only less readable if the source code isn't verified

**Comment by yorhodes** [comment]
> @nambrot @yorhodes do we still want to do this? Custom errors are significantly less readable, than strings, no?

only less readable if the source code isn't verified

**Comment by nambrot** [comment]
I would say we shouldn't do this, tooling would need to have access to source code to indicate the error, i dont' think the gas savings are worth it

**Comment by nambrot** [comment]
@yorhodes I'm just gonna assume i have convinced you :P
