### ISSUE TITLE
HyperlaneRouterDeployer should not assert a particular shape of factories/contracts

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1132]
`HyperlaneRouterDeployer` asserts contracts and factories under the `router` key so that it can do transferOwnership/enrollRemoteRouter/initConnectionClient. We can probably get away without this prescription and still provide those niceties. Specifically it breaks verification input assumptions since the key is also used as the contract name

**Comment by asaj** [comment]
We did this
