### ISSUE TITLE
Quickstart quick-fixes

### ISSUE THREAD

**Issue by jennifermarie** [hyperlane-xyz/hyperlane-monorepo#1163]
- [ ] Make mock mailboxes conform to interfaces
- [x] Make mockinterchainaccountrouter and its interface
- [x] Modify interchainaccountrouters to return leafIndex
- [ ] Provide single call function signature
- [x] Expose Call on ICARouter
- [x] Export InterchainAccountRouter on core or sdk
- [x] Loosen type of ChainNameToDomainID
- [x] Loosen type of hyperlaneCoreAddresses

**Comment by jmrossy** [comment]
Adding one: Loosen type of hyperlaneCoreAddresses
Problem being that a var of type `ChainName` can't access hyperlaneCoreAddresses because ChainName includes unsupported networks like Aurora :(

**Comment by nambrot** [comment]
- tried to make mock mailboxes conform to the mailbox interfaces but I don't think it made all that much sense, especially if we move to v2 mailboxes soon
-
