### ISSUE TITLE
More advanced search/filter options (Message Explorer)

### ISSUE THREAD

**Issue by jennifermarie** [hyperlane-xyz/hyperlane-monorepo#1181]
- [x] On message detail page, click on sender/recipient address to do a recipient search
- [x] Filter is crude at the moment, upgrade for multi-select and other improvements
- [ ] (Option to) hide Hello World/system debugging messages (based on msg body, future state with address filter)

**Comment by jmrossy** [comment]
Punting last bit for later but otherwise this is done and live
