### ISSUE TITLE
Design Permissionless Bridge smart contracts

### ISSUE THREAD

**Issue by jennifermarie** [hyperlane-xyz/hyperlane-monorepo#1224]
- Lock/mint / burn/unlock functionality
- Equivalent of governance piece from Optix -- time-lock and Gnosis multi-sig (possibly involving ICA)
- Synthetics with Create2
- Tokens transferrable to asset issuers (else owned by Abacus Works)
- Middleware for V1 compatibility

**Comment by yorhodes** [comment]
WIP https://www.notion.so/Permissionless-Bridge-Contracts-Design-and-Architecture-34598eff50434c52bebe71bb281a90da
