### ISSUE TITLE
Non-smart contract scoping for token wrapping bridge

### ISSUE THREAD

**Issue by jennifermarie** [hyperlane-xyz/hyperlane-monorepo#1225]
- Reusable/forkable by customers for use within their app UI
- Includes functionality for:
    - Address entry (token and recipient)
    - Amount entry
    - Destination chain selection
    - Connection to wallet
    - Send transaction
    - “Explorer page” (communicates status, finality, etc)

**Comment by jmrossy** [comment]
#1315 
#1316 
#1317 
#1318 
#1319 
#1320 
#1321 
#1322 
#1323
