### ISSUE TITLE
Illuminate Hackathon Bounties

### ISSUE THREAD

**Issue by Skunkchain** [hyperlane-xyz/hyperlane-monorepo#1267]
**Build Interchain Apps with Hyperlane!**

Hyperlane is the modular interoperability platform. With Hyperlane, you can build interchain applications, apps that can communicate between any blockchain, serving users wherever they are.

**Challenge Description**

Hyperlane would like to invite you to take your chance at building your first interchain applications! In the prize section below we outline how our prizes will be awarded, and give some ideas to get you started. Hyperlane is a bit different than other challenge issuers, as it is an interoperability platform allowing you to build applications that can communicate with other blockchains. This means you'll be deploying on more than one chain, and encountering new functionality (as well as new challenges!) as you go about it. It may be more difficult to get start with a set of challenges like these, but hopefully our ideas below give you enough to get started!

**Prizes**
- 🥇Top prize - 5k 'Best use of Hyperlane' interchain API
    - To win this prize you simply need to build an application that utilizes the Hyperlane API to establish interchain connectivity. You could be passing messages or assets. You could be making cross-chain view calls or oraclize data between blockchains. There is really no end to what you could build, but given that time is of the essence you don’t want to expand scope too much.
    - A great way to shoot for the top prize is to attempt to make an interchain version of a popular app, i.e. an interchain Compound or Sudoswap.
    - Another application we would love to see if a Blockchain Smart Router. Imagine being able to route computation to the cheapest blockchain within the Hyperlane network, and then being able to retrieve or read that state whenever necessary from your home chain. Effectively turning any blockchain into your layer 2 and beyond. This will be incredibly challenging to build, but the rewards will be far greater than you can imagine!
- 💸 2k x 2 - Best use of Hyperlane - DeFi related
    - As noted above there are many ways you can win our prizes, but here are some DeFi related ideas:
        - You could use our Accounts API to create an app that allows for interchain swaps without having to deploy any contracts on remote chains.
        - You could create an interchain Stableswap, accepting deposits of assets on multiple chains and creating unified liquidity pools.
        - You could create an interchain lending app, allowing borrowers to borrow against collateral from a remote chain.
        - You could create a contract that allows you to control multiple SAFEs or DAOs on remote chains. Using Interchain Accounts you could do this without having to deploy any additional logic on the receiving chains.
        - You could create interchain payment streaming contracts, collecting deposits on a number of chains and directing assets to their destinations.
- 🌠 2k x 2 - Best use of Hyperlane - NFT related
    - You could create an interchain minting contract that acts as a load balancer between chains, i.e collecting orders on several chains (with lower fees or higher throughput) and executing the mint on a different chain.
    - You could create an interchain nft collection where the NFTs have different properties based on the chain they’re currently on.
- 🏗 2k x 2 - Best use of Hyperlane - Infrastructure, Governance, or Gaming 
    - With respect to infrastructure, here’s a chance to build infrastructure either for Hyperlane or build infrastructure for other protocols that uses Hyperlane. 
    - More specific applications and examples include:
         - SAFE based app would be one that allows you to create a SAFE on one chain, and use any app on any Hyperlane supported chain from that SAFE.
         - An EIP 5164 implementation
         - A Tally or other Governance related integration
         - Lastly, an example we'd love to see built would be a modification with Hyperlane mailboxes or agents (relayer and validator) binaries to make them compatible with non-EVM environments such as Cosmos, Fuel, and others. 
    - On the gaming front, either a game, or gaming related infrastructure would qualify. 
  
- 1k - Best use of Interchain Queries
    - Build an interchain application which utilizes Interchain queries via the [Hyperlane Queries API](https://docs.hyperlane.xyz/hyperlane-docs/developers/query) as a core functionality, i.e. it cannot fulfill its purpose without the use of queries.
- 1k - Best use of Interchain Accounts
    - Build an interchain application, or integrate an existing application utilizing Interchain Accounts via the [Hyperlane Accounts API](https://docs.hyperlane.xyz/hyperlane-docs/developers/send), i.e. it cannot fulfill its purpose without the use of Interchain Accounts.
- 1k - Best use of Liquidity API
    - Build an application that integrates the [Liquidity API](https://docs.hyperlane.xyz/hyperlane-docs/developers/token-bridge-api) as part of its core functionality, i.e. it cannot fulfill its purpose without the use of the Liquidity API.

**Examples of Finalist Submissions**
Gani - https://ethglobal.com/showcase/gani-wallet-838so
Goatvoter - https://ethglobal.com/showcase/goatvoter-88p83
NFTArena - https://ethglobal.com/showcase/nft-arena-93bvn
Noca - https://ethglobal.com/showcase/noca-9o99z
Onchain.game - https://ethglobal.com/showcase/onchainga-me-fahyu
Mundo - https://ethglobal.com/showcase/mundo-wh4t0

**Useful Resources**

Docs - https://docs.hyperlane.xyz/hyperlane-docs/
Quickstarts - https://docs.hyperlane.xyz/hyperlane-docs/developers/quickstarts
Github - https://github.com/hyperlane-xyz/hyperlane-monorepo
Website - https://www.hyperlane.xyz/
Discord - https://discord.gg/hyperlane
Message Explorer and Debugger - https://explorer.hyperlane.xyz/
Protocol Overview - https://docs.hyperlane.xyz/hyperlane-docs/protocol/overview

**Submission Requirements**
Your submission should contain the following:

- Create a public GitHub repository for your project, then submit it using the Gitcoin platform.
- Create a [README.md](http://readme.md/) which contains the project name, name and email of team members, and explains the project and how to run it.
- Include a video (about 3-5 minutes) that demonstrates your submission. Videos must be uploaded to YouTube, Vimeo, or Facebook Video and made public.
- Submit by the official deadline

**Judging Criteria**
- Creativity: How does the project leverage Hyperlane? Does it use Hyperlane to do something unique? How innovative is it?
- Contribution to the ecosystem: Does the presence of the project advance the Hyperlane ecosystem?
- Technical prowess: How well executed is the project technically? Is the code well written? Is it properly commented and readable? Is the project well documented?
- User experience: Does the project result in a delightful user experience?

**Comment by makinghappen** [comment]
Really challenging hackaton, loved it to implement Hyperlane support for [Devopsdao](https://github.com/devopsdao)
