### ISSUE TITLE
On-chain fee quoting: accommodate gas payments for middlewares

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#1297]
Blocked by: https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1296

The design for how today's middlewares should allow users to correctly pay for gas is still a bit up in the air. This issue tracks settling on the best design and implementing it in the v2 branch.

Ideas:

1. Return the amount of gas used by the middleware to the caller:
```solidity
contract SomeMiddleware {
  // Destination domain => amount of gas used by this middleware on that destination
  mapping(uint32 => uint256) destinationGas;

  // Returns the (messageId, destination gas used by this middleware)
  function middlewareDispatch() external returns (bytes32, uint256) {
    bytes32 _messageId = mailbox.dispatch(...);
    return (_messageId, destinationGas[_destinationDomain]);
  }
}

contract UserContract {
  function dispatchViaMiddleware() external payable {
    (bytes32 _messageId, uint256 _middlewareGas) = middleware.middlewareDispatch();
    igp.payGas{value: msg.value }(_messageId, _destinationDomain, _middlewareGas + USER_CONTRACT_DISPATCH_GAS, msg.sender);
  }
}
```

Something like the logic in `dispatchViaMiddleware` could be shipped as a library to help calling contracts use the middleware + pay for gas in one function. Note this approach may make sense for middlewares that are always expected to be called by other contracts that are able to make the call to pay for gas. For something like the ICA router, that doesn't necessarily require the caller to be a contract with middleware-specific functionality, does this make sense? Probably not...

2. We could have middlewares commit to the IGP interface (which we've been against doing in the Mailbox, but maybe in the middlewares this is okay):

```solidity
contract SomeMiddleware {
  // Destination domain => amount of gas used by this middleware on that destination
  mapping(uint32 => uint256) destinationGas;

  function middlewareDispatch(
    IInterchainGasPaymaster _igp,
    uint256 _userGas // assuming there's some arbitrary logic that the user wants to execute on the destination, the amount of gas that uses
  ) external payable {
    bytes32 _messageId = mailbox.dispatch(...);
    _igp.payGas{ value: msg.value }(_messageId, _destinationDomain, destinationGas[_destinationDomain] + _userGas, msg.sender);
  }
}
```

3. ???

Maybe it makes sense to pick between 1 and 2 depending on the middleware? Unsure

Definition of done:
1. Decide how to pay for gas in an on-chain fee quoting world via middlewares
2. Implement the changes to the middlewares

**Comment by nambrot** [comment]
@tkporter this is basically done right?

**Comment by tkporter** [comment]
yeah I'd say this is replaced by #1603, #1604, and #1302. Closing
