### ISSUE TITLE
Remove unused "bank" key

### ISSUE THREAD

**Issue by asaj** [hyperlane-xyz/hyperlane-monorepo#1343]
This key is no longer used, yet a field exists in KEY_ROLE_ENUM and the infra code creates a key for it automatically. We should remove this code

**Comment by ef3n9r98** [comment]
Hi @asaj, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ](http://www.openq.dev/).

Thanks!

**Comment by nambrot** [comment]
This is done
