### ISSUE TITLE
Convert from CJS only to ESM or Hybrid

### ISSUE THREAD

**Issue by jmrossy** [hyperlane-xyz/hyperlane-monorepo#1354]
## Restructure core dist so factories are tree-shakeable 
_enables tree shaking of all the ABIs, deployers, and utils that apps (like the warp UI) don't actually use. And more broadly, CJS is being deprecated._

Revamp libraries in ESM so that integrating for partners is a better experience, so that their bundlers can discard unused packages

All SDK users will pull in 850Kb of factories, 200kb of which are for Test

<img width="1440" alt="Screen Shot 2022-11-30 at 14 13 16" src="https://user-images.githubusercontent.com/710751/204888655-e46c3527-ca66-4333-be5d-3a93338c4298.png">

**Comment by yorhodes** [comment]
maybe deployer code should be in a different package

**Comment by jmrossy** [comment]
Possibly blocked by https://github.com/NomicFoundation/hardhat/issues/3385

**Comment by jmrossy** [comment]
Semi-related: https://github.com/cosmos/cosmjs/issues/904#issuecomment-1018900767
