### ISSUE TITLE
Eclipse: working around small tx size limits

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#1363]
Solana transaction sizes are limited to 1232 bytes. I believe this includes all properties of the [Transaction](https://docs.rs/solana-sdk/latest/solana_sdk/transaction/struct.Transaction.html)-- e.g. including [Instructions](https://docs.rs/solana-program/latest/solana_program/instruction/struct.Instruction.html), which include the accounts they'll touch, instruction data, etc

This is unfortunate because processing a message can require a lot of data.

For example, the MultisigIsm's metadata is:
```
/**
 * Format of metadata:
 * [   0:  32] Merkle root
 * [  32:  64] Root index
 * [  64:  96] Origin mailbox address
 * [  96:1120] Merkle proof
 * [1120:1152] Threshold
 * [1152:????] Validator signatures, 65 bytes each, length == Threshold
 * [????:????] Addresses of the entire validator set, left padded to bytes32
 */
```
Which comes out to `1152 + (65 * threshold) + (32 * valset_size)` bytes. (Note this will decrease by 28 bytes due to https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1358)
 
With a 3/5 multisig setup that comes out to 1507 bytes for the metadata alone!

Proposed plan:

Split up the verification of messages and the processing of messages.

There would be 3 transactions:
1. Caching a signed checkpoint. This would involve a call made directly to the MultisigIsm including the merkle root (32 bytes), the root index (4 bytes), the origin mailbox address (32 bytes), the origin domain ID (4 bytes), and a quorum of signatures over the [checkpoint digest](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/solidity/contracts/isms/MultisigIsm.sol#L320). The total size of this would be `32 + 4 + 32 + 4 + (65 * threshold)` bytes. The MultisigIsm writes to storage that the checkpoint has been verified. We should consider also writing some attestation to the current validator set so that we can enforce that only signed checkpoints by the current validator set can be used to process against. Note that we don't need to pass in the addresses of the validator set as calldata because storage reads are very cheap on Solana, and should probably be favored over calldata
2. Proving inclusion of a message in a cached checkpoint. This would involve a call made directly to the MultisigIsm with the message hash (32 bytes), the proof (32 * 32 bytes = 1024 bytes) for a total of 1,056 bytes. The MultisigIsm would write to storage that the message has been successfully proved against a cached signed checkpoint. Could also consider a way to let us ensure that a message was proved against a checkpoint root that was signed by the current validator set
3. Actually processing the message (? unsure how to do this given the constraint of needing to know the accounts for an `invoke` call - see https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1371)

**Comment by tkporter** [comment]
thinking we should actually store the validator set in the ISM itself. That way we don't need to pass it in each time, and storage is so cheap on solana

**Comment by nambrot** [comment]
@tkporter is this still open?

**Comment by tkporter** [comment]
For posterity our workaround was just to not support merkle proofs - if we ever want bigger valsets able to be processed on Solana chains or bigger proofs, we'll wanna revisit this, but happy to consider this closed and irrelevant
