### ISSUE TITLE
Eclipse: processing messages

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#1371]
Solana has an unfortunate requirement that a list of all accounts that will be invoked must be specified in the transaction itself (see `accounts` in the [Instruction](https://docs.rs/solana-program/latest/solana_program/instruction/struct.Instruction.html) struct). Sadly, these differ from EIP-2930 style access lists, which in the Ethereum world allows you to run an off-chain simulation of the transaction to get a list of the storage slots that the transaction will touch. This is because Solana programs have another quirk -- code is never stored alongside state, state is always stored in a separate account. A common practice is to pass in the accounts where storage is present *in the transaction* as a parameter to the entrypoint. This means that the behavior of a program very heavily depends upon the accounts that are passed into the program. So simulating a transaction without the list of accounts that a program will touch isn't really possible.

In other execution environments, Hyperlane messages are processed by a transaction being made to the Mailbox.process function. If the ISM verification is successful (a call performed by the Mailbox), then the Mailbox calls into the recipient's `handle` function and marks the message as delivered.

In Solana, the relayer would need to know all accounts that the ISM and the recipient will touch beforehand. ISMs tend to require the relayer to know details about the ISM (i.e. to craft the correct metadata), so it's not unreasonable to expect the relayer to be able to pass in correct accounts for the ISM. However it's worth noting that more complicated ISMs in the future could make invocations to other contracts. The biggest thing is the recipients -- recipients need to be able to do whatever they want when handling a message, including making invocations to whatever programs they want

Some ideas:
1. Could the recipients expose a view function that returns a list of all `AccountMeta`s that the recipient will touch? The relayer could then call this before processing the message, and use this to construct a transaction with the correct AccountMetas.
This could *maybe* work as long as that view function itself doesn't require any accounts to be passed in-- i.e. the function can't depend upon specific accounts being passed in to e.g. read state from. It would need to just take in the message itself. Is that too restrictive? Is this too much of a lift for developers?

2. Rather than having the relayer be responsible for actually processing messages, we could shift this entirely to user applications. The relayer could be aware of specific applications, e.g. a wrapped token bridge, and know how which accounts to provide when processing the message.

Some ideas that aren't possible:

1. Could recipients keep the list of accounts they will touch in storage, and then when the process transaction is being executed they simply read the accounts from storage and pass them into the `invoke` calls?
This is definitely not possible - there's a strict requirement that the accounts must have their `AccountMeta` specified in the transaction

**Comment by tkporter** [comment]
Hmmm is there any way to leverage address lookup tables in our favor? Maybe that's like a more optimized version of (1) or something

**Comment by tkporter** [comment]
Shorter term I'm leaning toward 2

**Comment by tkporter** [comment]
Also shorter term I think we should just pass in the message as instruction data. And then medium term we can consider writing it to an account for larger messages

**Comment by sloboste** [comment]
i think potential option 1 may be possible - i don't think you can store any extra bits of info in an address lookup table that would be needed to fill out the AccountMetas

definitely not ideal, but I agree option 2 looks like the most straightforward short term solution

**Comment by nambrot** [comment]
@tkporter is this still open?

**Comment by tkporter** [comment]
This was completed - programs are expected to know what accounts are required to process a message, and they expose this in a standard way to the relayer
