### ISSUE TITLE
Deduplicate provider instances at runtime

### ISSUE THREAD

**Issue by mattiekat** [hyperlane-xyz/hyperlane-monorepo#1384]
Currently every `Mailbox`, `MailboxIndexer`, `InterchainGasPaymaster`, `InterchainGasPaymasterIndexer`, ... (`MakeableWithProvider`) type creates a duplicate provider instance. This is fine at some levels since they are not maintaining connections, but for things like metrics, we make calls on intervals to update certain information which causes redundant queries.

Creating a way to deduplicate at least some levels of the stack will also allow for #1304 to be more useful.

**Comment by nambrot** [comment]
@mattiecnvr how critical is it to do this soon?

**Comment by mattiecnvr** [comment]
> @mattiecnvr how critical is it to do this soon?

Not very. Definitely a nice to have change though.

**Comment by nambrot** [comment]
Close this in favor of #3321 if you agree @tkporter
