### ISSUE TITLE
Permissionless Deployment v1

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1450]
# Permissionless Deployment Product Spec

### New Chains

New chains will need users and liquidity to come from some other chain to make their chain valuable. Right now, that mainly requires an asset bridge (or a centralized exchange) to integrate with the new chain so that users are able to acquire tokens on the new chain to do useful stuff with. Said integration often requires substantial business development effort which larger projects are able to do, but smaller projects run into substantial issues (unless they have native interop a la IBC)

### Application Developers

Application developers often times would like to expand their addressable market of users by going cross-chain and in that process survey suitable chains with regards to existing users, incentives, ideological alignment, etc. There also often is opportunity to first-mover advantages to be the first in its class to move to a new chain. However, said integration of a new chain is often limited by the availability of interopability/asset bridging to that new chain which again generally requires substantial business development effort.

Both stakeholders are currently bottlenecked by that effort and ideally would like a permissionless option that is accessible to them that ultimately satisfies the need of creating interopability between a new chain and an existing chain already supported by Hyperlane. 

### Validators

This one is a little trickier. There are two kinds of validators as stakeholders we can expect:

**Professional multichain validators**:
These are generally professional validators whose main focus is to validate any many chains and have build competency and infrastructure to do so easily. Once a validator has learned how to set up a Hyperlane validator, they will generally appreciate the low operational burden of it, and thus might be interested in become validators for newer chains, especially with incentivization from the deployer. Abacus Works also falls in this category.

**Chain node operator**:
Often in the early days of a new chain, it might not attract "outside" node operators. However, existing chain operations usually are carried by dedicated chain enthusiasts, some of which may be interested and well positioned to support their existing commitment to the chain by running validators.

### Relayers

Very similar to validators, except even tricker since relaying inherently requires the relayer operator to be multichain. In Cosmos, Validators who validator on many chains often also end up as IBC relayers. So far, Hyperlane validators have not expressed interest or readiness to run relayers, and thus Abacus Works is the only known entity having demonstrated to operating relayers. However, it is expected that any reasonably successful adoption of permissionless deployment to make running a fully connected Abacus Works relayer operationally prohibitive.

## High-Level requirements

- Deployers should need only cursory understanding of Hyperlane
- Deployers should need to write no code to complete a deployment. (for which a Hyperlane implementation with smart contracts and agent code exists)
- It should be easy for anyone to be able to assess basic security parameters of a deployment.
- Existing hyperlane applications should be able to easily incorporate this new deployment.
- Operational burden for validator and relayer operators to be as minimal as possible with low implementation effort

## High-Level Addition User Flow

1. Source Validators and Relayers
2. Deploy mailbox contract and DefaultISM
3. Setup and run validators
4. Setup ISMs on existing hyperlane chains
5. Setup and run relayers
6. Publish deployment artifacts

## Smart contract architecture

```mermaid
flowchart LR
	subgraph Ethereum
       Mailbox1(Mailbox):::old

       FooChainISM(FooChainISM)

	end

	subgraph FooChain
        Mailbox2(Mailbox)   
        DefaultISM2(DefaultISM)
        
	end

    subgraph Legend
      Old(Existing Contract):::old
      New(New Contract)
    end

    classDef old fill:#163b99
```

A new deployment involves the creation of the contracts above for a bi-directional connection of the new chain, primarily the `Mailbox` contract.

**Inbound messages**:
To support inbound messages from a chain for which the default ISM has coverage on, the deployer is encouraged (but not required) to replicate the DefaultISM (which currently is a `MultiSigISM`) on the new chain.

**Outbound messages**:
To support outbound messages from the new chain to an existing chain, the deployer can deploy an ISM specific to its chain on the existing chain (most likely a `MultisigISM`).

## Contract deployment flows

There should be simple commands Implicit in the below commands is an equivalent command to verify the contract on the canonical block explorer as well as against the on-chain bytecode.

1. `yarn fetch-multisig-ism-config --network ethereum --address $ISM > config.json`
2. `yarn deploy-multisig-ism --network fooChain --config config.json`
3. `yarn deploy-mailbox  --network fooChain --defaultISM $DEFAULT_ISM_ADDRESS`
4. `yarn deploy multisig-ism --network ethereum --config fooChainValidators.json`

**Task details**:
- `yarn hardhat deploy-mailbox --network $NETWORK --defaultISM $DEFAULT_ISM_ADDRESS`
  - Deploys the mailbox from `@hyperlane-xyz/core`
- `yarn hardhat deploy-multisig-ism --config config.json --network $NETWORK`
  - Deploys a `MultisigISM` with the specified configuration
  - Configuration Format:
    - Array of:
      - chainID: number
      - threshold: number
      - signers: array of addresses
 - `yarn fetch-multisig-ism-config --network ethereum --address $ISM`
   - Fetches the configuration of the specified MultisigISM into the above configuration format

## Offchain Agent Architecture

A key change to agent operations is that core developers should no longer expect domains/chains to be statically known at compile time, i.e. a new chain should be operable entirely from config. Because the set of people who will operate but especially configure agents will become larger, it is likely that the current agent config parsing has to return more helpful error messages in the case of missing or malformatted configuration values that are expected. In general, the operations of agents has to become more forgiving.

### Validators

Deployers should source a reasonable validator set, ideally from the existing node operator community of the new chain. 
Hyperlane docs should be clear and concise enough so that validators with no background on Hyperlane are able to follow the guide and get the validator up and running within 30 minutes. (excluding RPC node operations).

### Relayers

To ensure relaying to and from the new chain, the new chains are expected run relayers and allowlist messages to/from the new chain. If relayers are concerned about griefing or generally more cost conscious, they can further constraint the messages that are being served to specific applications (message senders/receivers). Relayer allowlisting should be documented well.

Relayers continue to be configured directly with the storage locations of validator signatures.

## Out of scope

Everything below is considered out of scope and is left for context purposes

- IGPs
  - Ideally, IGPs should be deployed on the every chain that the new relayers are operating on to collect gas payments
- Consistent addresses/permissionless create2 factory
- scraper/message explorer
  - Anyone could run a scraper and message explorer instance
    - the explorer should support user-initiated relaying 
  - Anyone could run a scraper and give read-access to the operator of the "canonical" explorer for it to have wider coverage with a syncing agent
- relayer coverage
- proof of possession for validators
- alternate checkpoint storage to s3
- SDK tooling for distribute artifacts
- map of zones like website to indicate chains with hyperlane support, showing validator and relayer configs
- infra tooling like helm or terraform charts
- `RoutingISM`

## Out of scope verification

This part is technically optional for deployers, a deployment is fully functional without it. Deployers can always host these artifacts on a website of their choice.

However, applications who use these artifacts can potentially get compromised and thus the distribution of the artifacts has to be carefully caveated. At the same time, artifacts should be easily discoverable and consumable. This section describes a basic verification process for these artifacts to be displayed on the canonical docs page.

Deployers should be able to make PRs to add the addresses of the domain ID, mailboxes, ISMs to the repo. The PR should contain the following:

- A list of validators. For each validator, a publicly identifiable web2 identity (Twitter, Github, can be pseudonymous) or web3 identity (ENS, etc.) should make a statement self-attesting to them operating the validator and the address of the key they are using
- For each contract artifact, if the contract can be owned (like MultisigISM or DeferringISM) or proxied, the owner should be identifiable.
- For each contract artifact, it should point to a verified contract on a block explorer.
- For each contract artifact, 
- If contracts are owned by any multisig, each signer on the multisig should similarly use their identity to signify their membership 
- A list of relayers.

The DefaultISM owner can use the very same PR to decide whether or not to add the list of validators to the DefaultISM

## Out of scope signature/merkle proof service

**Validator Signature retrieval**:

just signature storage pointer or basically the relayer without tx submission?

A subset of relayer functionality can be  should be created which just takes very simple JSON config (basically hosted on Github) and makes accessible the signatures of the validators. This can be built as a module and then replace the `MultisigCheckpointSyncer` inside the relayer. There should be a single request `get_checkpoint(domain)` which basically grabs the currently highest signed checkpoint with quorum from the configured validator checkpoint storage locations. `MultiSigISM`s can then just use CCIP-read style reverts to allow clients to automatically get

See more in https://github.com/hyperlane-xyz/issues/issues/258#issuecomment-1356181434

**Comment by Yiwen-Gao** [comment]
@nambrot Thank you for posting the spec! The overall design makes sense to me, but I have a few clarification questions.

> Contract deployment flows
> ...
> 2. `yarn deploy-multisig-ism --network fooChain --config config.json`
> 3. `yarn deploy-mailbox --network fooChain --defaultISM $DEFAULT_ISM_ADDRESS`

The underlying beacons and proxies will be abstracted away so that the user doesn't have to worry about them, right? Does a user go through the same flow to upgrade the contracts? Or is the initial deployment different from a redeployment? 

If two users try to deploy the contracts for the same chain, will there be two instances of Hyperlane on that chain? 

> See more in https://github.com/hyperlane-xyz/issues/issues/258#issuecomment-1356181434

Did you mean to paste a different link? This one 404s for me.

**Comment by nambrot** [comment]
> @nambrot Thank you for posting the spec! The overall design makes sense to me, but I have a few clarification questions.
> 
> > Contract deployment flows
> > ...
> > 2. `yarn deploy-multisig-ism --network fooChain --config config.json`
> > 3. `yarn deploy-mailbox --network fooChain --defaultISM $DEFAULT_ISM_ADDRESS`
> 
> The underlying beacons and proxies will be abstracted away so that the user doesn't have to worry about them, right? Does a user go through the same flow to upgrade the contracts? Or is the initial deployment different from a redeployment?

That's a good point, we haven't specified whether the tooling would deploy proxied contracts or not. Maybe this could be just a command line arg. Since we don't have any interchain contract upgrade solution yet, the deployer actually would own the contract upgrade logic. An initial deployment would be different from a redeployment in that case, which one to choose depends. I suspect that generally it would be beneficial to be able to upgrade mailbox logic for minor bug fixes, but eventually we want to probably avoid the owner having this kind of power.

> If two users try to deploy the contracts for the same chain, will there be two instances of Hyperlane on that chain?
> 

Indeed. Like mentioned in the beginning of the spec, I would personally expected it to be easy enough to coordinate hyperlane deployments on a given chain. If there are differences in approach, I would suspect them to be mostly at the ISM level which is separate.

> > See more in [hyperlane-xyz/issues#258 (comment)](https://github.com/hyperlane-xyz/issues/issues/258#issuecomment-1356181434)
> 
> Did you mean to paste a different link? This one 404s for me.

Oh its from a private repo, I will paste a copy below

**Comment by nambrot** [comment]
> > To support inbound messages from a chain for which the default ISM has coverage on, the deployer is encouraged (but not required) to replicate the DefaultISM (which currently is a MultiSigISM) on the new chain and have it be owned by the DefaultISM owner on Ethereum via its ICA.
> 
> I'm not sure that's a good thing to encourage? That implies that ICAs will be deployed on the new chain, and that the new ICARouter contract will be enrolled by all the other routers.

Great point, I forgot about the need to deploy and enroll the ICARouter. What would you suggest for the ownership of the DefaultISM on FooChain?

> 
> > To support outbound messages from the new chain to an existing chain, the deployer can deploy an ISM specific to its chain on the existing chain (most likely a MultisigISM).
> 
> > Realistically, applications will likely want to compose several ISMs and thus a DeferringISM is necessary to allow the deployer/owner of said DeferringISM to specify which ISM to use depending on the origin of a message.
> 
> I've called this a `RoutingISM` in the past. I don't see why this is necessary for the scope that you're proposing.

You are right again, moving into out of scope as well.

> 
> > In general, this calls for a creation of a separate package either inside the monorepo or outside as a separate repo to run infra-like scripts without any presumption of Abacus Works infrastructure, ideally with the goal of transitioning over to use it instead of infra. To start, these should probably be hardhat tasks similar to https://github.com/hyperlane-xyz/hyperlane-quickstart. Implicit in the below commands is an equivalent command to verify the contract on the canonical block explorer as well as against the on-chain bytecode.
> 
> Why not use `forge` here?

Definitely open for being convinced otherwise here, but IMO hardhat/typescript is more approachable than `forge`, non EVM tooling is more likely to be compatible as npm modules or even hardhat plugins. If folks needed to look under the hood and see how things worked or make modifications, IMO this would be easier.

> 
> > yarn hardhat deploy-default-ism --network $NETWORK --environment $ENV
> 
> I'd love for this to be more general, e.g. by taking a config file, rather than passing an env name. Suggest instead `yarn hardhat deploy-ism --type multisig --config config.json --network $NETWORK`
> 
> And probably we should encourage this be done _before_ mailbox deployment and to have mailbox deployment take a default ISM address as an argument

I was trying to avoid needing to find the `config.json` file or needing to update it, imo the source of truth should be on-chain. But maybe we can have a separate command to pull the config from on-chain and then pass it here?
 
> > FooChainISM deployment
> > yarn hardhat deploy-multisig-ism --network $NETWORK --originDomain $NEW_DOMAIN --validators $VALIDATORS_ADDRESSES --threshold
> 
> Not sure I understand what's going on here. As far as I can tell we _just_ need `yard hardhat deploy-ism --type multisig`. It feels very weird to me to have two separate commands to deploy the same contract type.

The only difference was above was not needing to specify the configuration, but per above comment, changed it to the more generic command.

> > DeferringISM deployment
> > yarn hardhat deferring-ism --network $NETWORK --mapping domain:ISM
> Did you mean 'deploy-deferring-ism'? Suggest taking a config json file here as well

Indeed I meant deploy-deferring-ism. I def don't feel strongly, but i weakly prefer command line args/env vars for "simple" configuration. Accessible input validation feels marginally simpler in that case.

> > Relayers continue to be configured directly with the storage locations of validator signatures.
> 
> IMO this is one of the easiest things we can do to make running a relayer easier.

This is the one thing I wanted to spend a bit more time thinking about, so might as well do it here. I was originally gonna go with suggesting a simple registry service like I believe we have talked about which allows the operator of said service to just pull the signatures for any relayer, making running a relayer significantly easier. (Whether the service runs per ISM or for all ISMs I think is not material) 

So moving from:

```mermaid
flowchart LR
    subgraph origin
        MailboxO
    end

    subgraph destination
        Mailbox
        ISM
    end

	


    
    Relayer --"read" --> S3
    S3Config --> Relayer
    
    Relayer --"readIndexedMessages"--> MailboxO
    Relayer --"submit(message, proof, signatures)"--> Mailbox
    Mailbox --"isValid"--> ISM
```

to 

```mermaid
flowchart LR
    subgraph origin
        MailboxO[Mailbox]
    end

    subgraph destination
        Mailbox
        ISM
    end

	
    Relayer --"readLatestCheckpointSignatures"--> VSS

    VSS[Validator Signature Service]
    VSS --"read" --> S3
    S3Config --> VSS

    Relayer --"readIndexedMessages"--> MailboxO
    Relayer --"submit(message, proof, signatures)"--> Mailbox
    Mailbox --"isValid"--> ISM
```

However as I was thinking about it, it seemed to me than pretty quickly thereafter, we'd actually want to support things like relaying from the explorer or CCIP-read compliance (which is not a goal in of itself perse, but a good guide imo). For those goals, "just surfacing" the validator signatures actually isn't sufficient, the merkle proof still has to be generated somewhere. Additionally, to support different ISM metadata, the `Relayer <--> Validator Signature Service` API would have to be adjusted to become more generic. Instead, it seemed possibly preferrable to leapfrog to an architecture like this:

```mermaid
flowchart LR
    subgraph origin
        MailboxO
    end

    subgraph destination
        Mailbox
        ISM
    end

	
    Relayer --"getProcessableMessage"--> VSS

    VSS[ISM Service]
    VSS --"read" --> S3
    S3Config --> VSS
    
    VSS --"readIndexedMessages"--> MailboxO
    Relayer --"submit(message, proof, signatures)"--> Mailbox
    Mailbox --"isValid"--> ISM
```

This effectively separates the retrieval/indexing part of the relayer from the submission part.  ISMs can indicate the ISM service via CCIP-read style reverts to indicate the necessary off-chain data to process the message. This also would allow the explorer to easily support end-user relaying (in addition to any CCIP-read enabled client). Relayers could easily support new origin chains without the need to operate reliable origin chain node infrastructure, as ISM service operations can be done on a per-origin-chain basis (like the validators).

There is a decent chance that this is too forward looking, but it was enough for me to feel uncomfortable enough with the idea that a simpler `Validator Signature Service` would not be long-lived.


> > Out of scope verification
> > I don't think we should work on any of this stuff for now and it seems distracting to mention it.
> 
> > Out of scope signature/merkle proof service
> > Ditto, this feels like part of a spec for `Relayers continue to be configured directly with the storage locations of validator signatures`?

The way I approached it was that I was considering the things on the margin that could be in scope, but then extracted it out to `Out of scope` after consideration. I personally find it helpful in allowing the reader to evaluate the scope of what would be ahead. I can remove it if you feel strongly about its distraction cost.

**Comment by samtvlabs** [comment]
Thanks for this. We have already started to explore deployments and wanted to clarify the following points:

* Having recently just upgrade to v2, we are wondering which (if any) breaking changes are introduced?
* Will the existing tooling work out of the box? e.g. The relayers depend on external storage (s3). 
* Can you clarify what the `routing ISM` is ?

**Comment by asaj** [comment]
Responses inline, if I didn't respond it means I agree with you (or I missed it) :)

> Great point, I forgot about the need to deploy and enroll the ICARouter. What would you suggest for the ownership of the DefaultISM on FooChain?

I would just leave that to the discretion of the `Mailbox` deployer. Don't forget about the ownership of the `Mailbox` as well (and proxy?)

> I was trying to avoid needing to find the config.json file or needing to update it, imo the source of truth should be on-chain. But maybe we can have a separate command to pull the config from on-chain and then pass it here?

This solution works for me.

> This is the one thing I wanted to spend a bit more time thinking about, so might as well do it here.
> Instead, it seemed possibly preferrable to leapfrog to an architecture like this

Agreed that we'll want something like you outlined, and now I agree with your original choice to keep this out of scope (though I do think we should prioritize it). I revisited CCIP-read over the weekend and a good design here is going to require some careful thought.

One thing I'd suggest that I don't think you included is an on-chain broadcast protocol for validator signature locations so that the ISM service needs minimal configuration (e.g. just the address of a contract).

**Comment by asaj** [comment]
Obviously I'm not @nambrot but my understanding is inline

> Thanks for this. We have already started to explore deployments and wanted to clarify the following points:
> 
> * Having recently just upgrade to v2, we are wondering which (if any) breaking changes are introduced?

I don't think @nambrot is proposing any breaking changes (or technically any protocol changes), just ways to make it easier for anyone to deploy Hyperlane v2 to any chain.

> * Will the existing tooling work out of the box? e.g. The relayers depend on external storage (s3).

The relayers will continue to depend on external storage. @nambrot 's proposal of what we do short-term here is just about making it as easy as possible for anyone deploy Hyperlane contracts and run one or more validators/relayers. Up to now the tooling for contract deployment and running a relayer was mainly built by and for Abacus Works.

You may note towards the end of his most recent comment Nam proposes separating out the two functions of the relayer (gathering metadata like merkle proofs and validator signatures, and submitting transactions) into separate binaries ("ISM service" and "Relayer"). I think this is a great idea but it will take some time will be fully backwards compatible (i.e. running the old, monolithic relayer will still work just fine).

> * Can you clarify what the `routing ISM` is ?

The RoutingISM is just an ISM whose `accept()` function is just a big switch statement based on the message's `origin` chain. A few examples of how this might be useful:

1. Permissionless Deployment
I want to deploy Hyperlane to AsaChain, and allow messages *from* AsaChain to be receivable on Ethereum. This means I need an ISM deployed to Ethereum that is capable of accepting messages from AsaChain. 

I can deploy a MultisigISM that is configured with an AsaChain validator set. But what if folks that are using this ISM also want to be able to receive messages from Avalanche, BNB, Polygon, Celo, etc.?

I have two options. I can configure my MultisigISM with validator sets for those chains. But that is a pain for me to configure and keep up to date. Instead, I can deploy a RoutingISM that redirects all non-AsaChain messages to the default ISM.

```
accept(metadata, message) {
  if (message.origin == AsaChain) {
    return asaChainISM.accept(metadata, message)
  } else {
    return mailbox.defaultIsm().accept(metadata, message)
  }
}
```

2. Supporting multiple ISM types

Imagine we build an ISM type that's specific to a single chain (e.g. verifying signatures of the "sync set" for ethereum). Ideally we'd want to use that ISM type for verifying ethereum messages, but a different ISM type for verifying messages from other chains. A RoutingISM lets us vary the ISM type (e.g. Multisig, Optimistic, LightClient) by origin chain

**Comment by nambrot** [comment]
> > Great point, I forgot about the need to deploy and enroll the ICARouter. What would you suggest for the ownership of the DefaultISM on FooChain?
> 
> I would just leave that to the discretion of the `Mailbox` deployer. Don't forget about the ownership of the `Mailbox` as well (and proxy?)

Yeah, leaving this unspecified for now and making that explicit in the spec.

 > One thing I'd suggest that I don't think you included is an on-chain broadcast protocol for validator signature locations so that the ISM service needs minimal configuration (e.g. just the address of a contract).

yeah i would like to think about the ISM service a bit more, but it seemed like easy enough to just have the operator of the ISM service specify an off-chain logic for this

**Comment by nambrot** [comment]
Scope:

Deployment:
- https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1466 (1)
- https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1467 (2)

Agents/Operations:
- https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1471
- https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1468
- https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1469

Documentation:
- https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1470
