### ISSUE TITLE
Scraper should be able to handle messages to/from unknown domains

### ISSUE THREAD

**Issue by asaj** [hyperlane-xyz/hyperlane-monorepo#1544]
The scraper should be able to elegantly handle messages sent from a known domain to an unknown domain, and vice versa.

Ultimately this will allow the explorer to show the message details and the transaction that occurred on the known domain

**Comment by nambrot** [comment]
What happens right now? I hope the agent doesn't just crash? @mattiecnvr

**Comment by nambrot** [comment]
From Discord DM:

> I think it used to crash but I fixed it so that just the sending domain had to be known or something
> And the reverse for delivered messages
> It was because of a constraint on the db tables that I had falsely assumed would always hold
> If it does crash it is an easy fix and I know where to check to verify if it’s okay

Closing for now
