### ISSUE TITLE
On chain fee quoting: deployment and rollout

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#1589]
Deploy new IGP(s), announce accordingly, ensure new SDK rollout occurs

Captured by:
#1302 
#1603
#1601 
#1600 
#1604 
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1613

But keeping this issue around to clearly track that I'm responsible for the deploy and rollout

**Comment by nambrot** [comment]
Remember that helloworld and warp route and quickstarts also need adjustment, maybe wanna do that ahead of this as well
