### ISSUE TITLE
Sealevel / Eclipse / Solana: write outbound messages to accounts

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#1590]
The easiest way to "index" outbound messages seems to be to write to an account.

This is for a few reasons:
* Indexing Solana seems to be hard in general - msg! logs don't seem to be easily indexed
* https://github.com/solana-labs/solana/issues/23653

**Comment by tkporter** [comment]
This is what many ppl seem to go with, see https://github.com/solana-labs/solana/issues/23653#issuecomment-1171220612. Also Wormhole does this

**Comment by nambrot** [comment]
@tkporter is this still open?

**Comment by tkporter** [comment]
done ages ago lol
