### ISSUE TITLE
Incorrect Celo IGP address used in agents and HelloWorld

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#1598]
Noticed that the docs say that the IGP address should be `0xde86327fbfd04c4ea11dc0f270da6083534c2582` everywhere.

This contract does exist on Celo (https://celoscan.io/address/0xde86327fbfd04c4ea11dc0f270da6083534c2582#code), but it seems like we're actually using the *implementation* contract ([`0x5bc68C82d33160cF4EA34d0bab3F7c27cD9eD8D6`](https://celoscan.io/address/0x5bc68C82d33160cF4EA34d0bab3F7c27cD9eD8D6)) of the IGP in some places:
* [Agent config](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/rust/config/mainnet2/mainnet2_config.json#L9)
* We deployed the HelloWorld router on Celo with that implementation address as the IGP https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/typescript/infra/config/environments/mainnet2/helloworld/hyperlane/verification.json#L30

We should:
1. Fix the agent config to use the proxy address `0xde86327fbfd04c4ea11dc0f270da6083534c2582`
2. Change the HelloWorld router on Celo to use `0xde86327fbfd04c4ea11dc0f270da6083534c2582` as the IGP

**Comment by nambrot** [comment]
@tkporter will this be resolved once you deploy the new IGPs and we have to update the middlewares anyways?

**Comment by nambrot** [comment]
@tkporter you already updated the IGP on kathy right. Will close, feel free to re-open otherwise

**Comment by tkporter** [comment]
yup this is done
