### ISSUE TITLE
Release SDK with new IGP addresses

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#1613]
* The SDK should allow access to the default ISM's OverheadIGP, as well as the base IGP where the fee quoting lives
* Should indicate it's a breaking change because of the changes to InterchainGasCalculator & the new IGP addresses
* Should make sure that all of our own services / repos that consume the SDK upgrade to the new version. This includes deploying kathy from a fresh commit such that kathy pays for gas with the correct IGP

**Comment by nambrot** [comment]
Can you also update https://github.com/hyperlane-xyz/hyperlane-token/blob/main/trade-route-example-config.json
