### ISSUE TITLE
Deploy InterchainGasQuoteOracle to testnet3

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1619]
This will require 
- some configuration of HyperlaneCoreDeployer that includes mapping to LayerZero domains for LayerZeroGasQuoteOracle
- some configuration of Hyperlane CoreDeployer that statically sets gasPrice * relativeGasPrice
- HyperlaneCoreDeployer can deploy quote oracles from said config

**Comment by tkporter** [comment]
😎

**Comment by tkporter** [comment]
with #1765
