### ISSUE TITLE
Create2 tooling test

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1651]
Right now we have a fixed create2 address in our deployment tooling that means it that path is untested in our test environment since we don't have create2 factories in it. 

We should pre-sign create2 factory deployment txs, deploy them in the test environment and then have as many tests as possible excercise this code path.

As a side-effect, we should expose these create2 factory deployment txs in the SDK so that we can reuse them in a permissionless deployment setting.

**Comment by asaj** [comment]
Got rid of Create2Factory
