### ISSUE TITLE
Investigate fork testing for deployment tooling

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1653]
Right now, issues with the core deployment tooling against the live deployments on testnet3 or mainnet2 are only surfaced when running it. Instead, it would be nice to test deployments via a forked network(s) to figure this out. This may or may not be easily done. This ticket is a time-bounded investigation into that.

**Comment by nambrot** [comment]
Possible things to do:

- Run the deployer against remote networks with no changes (this could be done without fork testing and just throws an error when a tx is attempted)
- simulate the addition or changing of contracts after changing some config and observe that the deployer at least runs (i believe you need fork testing for this)
- Run the checker against the deployed environments and observe no violations
- Run the checker against the deployed environments with changed config, observe violations and then simulate the govern script to see if it runs (also believe fork testing is required). optionally then run the checker again to see violations resolved. (this would also be useful against local test deployments)

**Comment by yorhodes** [comment]
- run deployer against remote forked network
- test idempotency of removing any key from core contracts typescript/infra/test/core.test.ts

1. `hardhat_impersonateAccount(gnosisSafeAddress)` on violation chain
2. `ethers.getSigner`
3. rotate signer on multiprovider
4. run govern with multiprovider, run checker
