### ISSUE TITLE
Idempotent resuming deploy tests for proxied contracts

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1655]
We already have tests that test the ability to resume a contract after removing artifacts like here https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/0ab04dc6770482cea0bfc52b7340b68bdc0549b7/typescript/infra/test/core.test.ts#L91

However, those removed artifacts do not capture proxied contracts which we recently ran into as non-functionality. This ticket is about adding a test that removes the artifact of a proxied contract and the deploy still succeeds. There should be another test case that tests when the proxyAdmin is not owned by the deployer key as well.

**Comment by asaj** [comment]
We got rid of proxied contracts, kind of
