### ISSUE TITLE
FAQ question - PKs in contract

### ISSUE THREAD

**Issue by anettrolikova** [hyperlane-xyz/hyperlane-monorepo#1720]
Add: 
Q: Why we are using private key in Hyperlane contracts?
A: Private keys are being deployed by contract developers (creators). Deploying private keys gives you the ability to control the messaging bridge and modify it. In case of Warp Route it lets you modify the routes

Check this with Nam for correction

**Comment by nambrot** [comment]
We don't use private keys in the contracts, we just have scripts that use it as input so that one can sign transactions for the deployment of the contracts itself. You don't deploy private keys

**Comment by anettrolikova** [comment]
FAQs
Is Warp Route a token bridge or messaging bridge? 
Actually it is hard to tell, as Warp Route is essentially locking value on collateral chain and reflecting it and minting the same value 1:1 on synthetic chain. The value is being bridged but actually not.

**Comment by nambrot** [comment]
I would say that is traditionally considered a token bridge. Warp route is definitely not a message bridge itself

**Comment by asaj** [comment]
We did the FAQ :)
