### ISSUE TITLE
Update diagram in Intro into Hyperlane

### ISSUE THREAD

**Issue by anettrolikova** [hyperlane-xyz/hyperlane-monorepo#1721]
Why there are two routes between mailbox and relayer ? 
Shouldn't be there two way narrows between mailbox and relayer and also relayer and mailbox on destination chain ? 

![Image](https://user-images.githubusercontent.com/44020788/215894485-08c69577-3452-48a9-82e7-35708ffb7353.png)

source: https://docs.hyperlane.xyz/docs/introduction/readme

**Comment by anettrolikova** [comment]
There should be explanation of this diagram or linked article that explains this doc. Or just link protocol overview docs  under this diagram https://docs.hyperlane.xyz/docs/protocol/overview

**Comment by yorhodes** [comment]
@anettrolikova 
> Why there are two routes between mailbox and relayer ?
The relayer gets partial information from each route
From the mailbox, they get message content
From the validators, they get signatures
