### ISSUE TITLE
Supporting Arbitrum in GasPaymentPolicyOnChainFeeQuoting

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#1728]
To recap, Arbitrum gas amounts are special. Each opcode that's executed on Arbitrum has the exact same gas cost as any other EVM chain, so the actual amount of gas used by the opcodes that are executed has no difference, but Arbitrum will add an amount of gas to the transaction in addition to the opcode usage (similar to intrinsic gas) that is intended to cover L1 costs. This is because the serialized Arbitrum transactions are posted to L1 Ethereum as calldata

You can think of the gas amount for Arbitrum transactions as the sum of L2 gas and L1 gas. The L2 gas is just "normal" gas that we expect on any other chain -- e.g. this covers gas used by opcodes, L2 calldata, etc. Then the L1 gas covers the cost of posting the transaction to the L1. This is a good resource if you're curious and want a deeper explanation https://medium.com/offchainlabs/understanding-arbitrum-2-dimensional-fees-fd1d582596c9. The L1 gas component changes depending on how big the tx is (more bytes => more calldata => more expensive to post on L1), the L1 gas price (higher L1 gas price means it's more expensive to post transactions to L1), and L2 gas price (a lower L2 gas price means that to cover the L1 costs, more gas needs to be charged)

Anyways, we now have a situation - users on chain are specifying a gas amount that relates to the "L2 gas" (because they specify the amount of gas they expect their logic to consume on the destination), but in the relayer when we make the `eth_estimateGas` call to estimate gas for processing a message, we're getting the full L1 gas + L2 gas estimation. So we need to do a couple things...
1. On-chain, we need to make sure that the oraclized gas price that we use when charging ppl for txs sent to Arbitrum considers the L1 gas costs. This is out of scope for this issue
2. In the relayer, we need to change the GasPaymentPolicyOnChainFeeQuoting to compare the L2 gas amount used by a message to how much has been paid for via interchain gas payments. We can't just use the value we get from `eth_estimateGas` (which is the `tx_cost_estimate.gas_limit`), because this is the sum of L2 gas + L1 gas. This is what this issue seeks to address

The recommended way Arbitrum suggests estimating the L2 gas and the L1 gas is via their [NodeInterface](https://developer.arbitrum.io/arbos/gas#nodeinterfacesol) contract, which is a fake precompile. By fake precompile, I mean that they've made it so that if you make an `eth_call` to a node at the address `0x00000000000000000000000000000000000000c8`, it'll let you call functions in this file https://github.com/OffchainLabs/nitro/blob/master/contracts/src/node-interface/NodeInterface.sol. These functions don't access on-chain state-- they do more heavyweight off-chain things, like allowing you to estimate gas usage for a tx, and aren't accessible on-chain

The function that I think we can best leverage is [`gasEstimateL1Component`](https://github.com/OffchainLabs/nitro/blob/master/contracts/src/node-interface/NodeInterface.sol#L110):
```
    /**
     * @notice Estimates a transaction's l1 costs.
     * @dev Use eth_call to call.
     *      This method is exactly like gasEstimateComponents, but doesn't include the l2 component
     *      so that the l1 component can be known even when the tx may fail.
     * @param data the tx's calldata. Everything else like "From" and "Gas" are copied over
     * @param to the tx's "To" (ignored when contractCreation is true)
     * @param contractCreation whether "To" is omitted
     * @return gasEstimateForL1 an estimate of the amount of gas needed for the l1 component of this tx
     * @return baseFee the l2 base fee
     * @return l1BaseFeeEstimate ArbOS's l1 estimate of the l1 base fee
     */
    function gasEstimateL1Component(
        address to,
        bool contractCreation,
        bytes calldata data
    )
        external
        payable
        returns (
            uint64 gasEstimateForL1,
            uint256 baseFee,
            uint256 l1BaseFeeEstimate
        );
```

This will provide the L1 gas estimate as `gasEstimateForL1`, and then we can use this to subtract from the `tx_cost_estimate.gas_limit` to get the L2 gas. Then we can have the gas payment enforcement policy compare the paid-for gas amount to the L2 gas amount.

For a concrete example to play around with, we can try estimating gas amounts for this Arbitrum tx (at a block before it was executed, ofc): https://arbiscan.io/tx/0xaaf47c9ca61e12c9481dd1dd89966f27e348af7f976f962c10546d143b2f66e1

First, note the gas used: 2,985,956, and the gas limit: 3,452,720. Lots of this gas used is due to L1 gas because there's a lot of calldata in the transaction.

Using the public RPC url `https://arbitrum.blockpi.network/v1/rpc/public`, we can get some more info (`$CALLDATA` in all the following examples is set to the raw calldata of the transaction, i.e. `0x7c39d13000000...........6c6f2100000000000000000000000000`)

We can use `eth_getTransactionReceipt` to get the L1 gas via the `gasUsedForL1` property present on arbitrum:
```
$ cast rpc eth_getTransactionReceipt 0xaaf47c9ca61e12c9481dd1dd89966f27e348af7f976f962c10546d143b2f66e1 --rpc-url https://arbitrum.blockpi.network/v1/rpc/public | jq
{
  "blockHash": "0xa08410e199ce5bf28129ce9721edaf4840fa7209412ab9a3e123607f93ef08b7",
  "blockNumber": "0x354a6dd",
  "contractAddress": null,
  "cumulativeGasUsed": "0x2d8fe4",
  "effectiveGasPrice": "0x5f5e100",
  "from": "0x5e8bd7ed3e6bcd01961ac9e2edce34a2295b17fe",
  "gasUsed": "0x2d8fe4", # 2985956 in decimal
  "gasUsedForL1": "0x2b262a", # 2827818 in decimal
  "l1BlockNumber": "0xfbbfe6",
  ...
  "status": "0x1",
  "to": "0x35231d4c2d8b8adcb5617a638a0c4548684c7c70",
  "transactionHash": "0xaaf47c9ca61e12c9481dd1dd89966f27e348af7f976f962c10546d143b2f66e1",
  "transactionIndex": "0x1",
  "type": "0x0"
}
```

If we do `gasUsed - gasUsedForL1`, we can get the L2 gas actually used: `2985956 - 2827818 = 158,138`

Now if we try a normal eth_estimateGas:
```
$ cast rpc eth_estimateGas "[{\"to\": \"0x35231d4c2d8b8adcb5617a638a0c4548684c7c70\", \"data\":\"$CALLDATA\"}, \"0x354a6dc\"]" --raw --rpc-url https://arbitrum.blockpi.network/v1/rpc/public
"0x33290e"
~  $ cast td 0x33290e
3352846
```

And if we were to do a call to `NodeInterface.gasEstimateL1Component:`

```
$ cast call 0x00000000000000000000000000000000000000c8 'gasEstimateL1Component(address,bool,bytes)(uint64,uint256,uint256)' 0x35231d4c2d8b8adcb5617a638a0c4548684c7c70 false $CALLDATA --rpc-url https://arbitrum.blockpi.network/v1/rpc/public --block 55879388
3189687 # gasEstimateForL1 an estimate of the amount of gas needed for the l1 component of this tx
100000000 # baseFee the l2 base fee (this is just the L2 gas price really)
10013522349 # l1BaseFeeEstimate ArbOS's l1 estimate of the l1 base fee
```

Ok, so now if we do `3352846 - 3189687 = 163,159`, we get an estimation of what the L2 gas is. This is a pretty solid estimate of what the L2 gas actually was (recall `158,138` from earlier).

So, concretely, we should change the relayer such that:
1. In addition to the normal gas estimation when we do `let tx_cost_estimate = match self.mailbox.process_estimate_costs(&msg.message, &metadata)`, we get the "L1 component" of the gas estimate. For Arbitrum-based chains (i.e. arbitrum goerli and arbitrum), this would be a call to the `NodeInterface.gasEstimateL1Component` function. For all other chains, the L1 component returned can be zero and no call is necessary
2. In the gas payment enforcement policies, we compare the `interchain_gas_payment.gas_amount` to the `tx_cost_estimate.gas_limit - l1_cost_estimate.gas_limit`

### Other ideas

There are a couple other ideas that I'll share just for completeness & if others feel like they're better:

1. Instead of dealing with the `NodeInterface` contract, we roughly estimate the L2 gas by still getting the normal `tx_cost_estimate`, but by then also doing a second eth_estimateGas where the calldata of the tx is the exact same, but the `to` address is some random address that doesn't have any bytecode at all (like `address(0xdead)`). This way, the only L2 gas that's really charged is calldata gas, and there are no opcodes. And we can subtract these two gas estimates to figure out rough estimations for what the L1 and L2 gas usage is. Imo this is pretty hacky and it's not even very accurate
2. In `NodeInterface`, there's another function called `gasEstimateComponents`. This returns the L2 gas and the L1 gas, each split up. This is nice because then we wouldn't need an eth_estimateGas when doing `tx_cost_estimate` and then a subsequent call to the NodeInterface contract. But! if the transaction reverts, as it very well may, then the `gasEstimateComponents` call will revert. And unfortunately because we need to use `eth_call` there, the RetryingProvider that we use will not realize that we are okay with this call reverting, and it'll continually retry it in hopes that it'll stop reverting. This takes minutes and clogs the serial submitter :/ so i don't really like this

**Comment by nambrot** [comment]
Very elaborate explanations, thank you. IIUC this proposal is just for the enforcement of the gas amounts in the IGP payment, not for quoting the right "gasPrice" since the gasAmount enforced is only the L2 gas component?

For that, your proposal of calling `NodeInterface` in the relayer makes sense to me, though I am also curious about how to solve the pricing issue?

**Comment by tkporter** [comment]
I think our only option is to just have the oraclized Arbitrum gas price be high enough where we feel that the L1 gas will be roughly accounted for. We can't really replicate the exact logic for calculating exactly what the L1 gas will be because that'd require knowledge of the size of the calldata the process message will use -- i.e. both the message and the metadata -- which we don't have on chain

**Comment by tkporter** [comment]
Curious if people feel that roughly accounting for those costs is sufficient

**Comment by nambrot** [comment]
Yeah imo that is sufficient for me. What do our competitors do?

**Comment by nambrot** [comment]
Like for example can we just use L0s oracle cause that's also what they do?

**Comment by tkporter** [comment]
Looking at the quoting they do on Ethereum for messages to Arbitrum, it looks like they make no effort to increase the gas price or token exchange to account for the L1 gas. The on-chain gas price is 0.1 gwei (which is the actual gas price of Arbitrum), and their gas-per-calldata-byte is configured to just 1 gas. Their token exchange rate is 1.06 (bc both charge eth fees, and they charge a 6% premium)

**Comment by nambrot** [comment]
So does that mean that either they dont actually check actual gasPrices and just eat the diff?

**Comment by tkporter** [comment]
yeah I believe they just eat the cost
