### ISSUE TITLE
CI should show storage layout changes in PRs

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1742]
looks like foundry supports showing diffs against snapshots for the storage layout of the contracts to force developers to explicitly acknowledge

**Comment by vinhyenvodoi98** [comment]
the target of bounty is this PR right ?

**Comment by nambrot** [comment]
Not quite, this bounty talks about snapshotting and showing storage layout changes

**Comment by yorhodes** [comment]
example https://github.com/morpho-org/morpho-optimizers/pull/1150/
