### ISSUE TITLE
Inaccurate `payment` amount emitted in the InterchainGasPaymaster's `GasPayment` event

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#1751]
In the shuffle of moving over to on-chain-fee quoting, we should've updated the `payment` amount in the `GasPayment` event here: https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/solidity/contracts/igps/InterchainGasPaymaster.sol#L71 to `_requiredPayment` instead of `msg.value`. This means that atm if e.g. 0.1 ETH is required as payment, someone can pass 1 ETH in, get refunded 0.9 ETH, and the event will say 1 ETH was paid.

This isn't a big deal in practice because in the on-chain fee quoting case (which is all we care about for the currently deployed IGPs), the relayers don't care about the payment amount. But this is still incorrect, and we will want to change this as a part of the move toward actually quoting accurate gas payments

**Comment by Bukky3** [comment]
Okay
