### ISSUE TITLE
Allow a single relayer instance to relay from multiple origin chains

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1760]
The investigate ticket for https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1899

**Comment by asaj** [comment]
> maybe just do it in a backwards compatible way ideally

Wdym by this?

**Comment by asaj** [comment]
> We should quickly investigate if there is an easy way to run the relayer differently without incurring that overhead

What overhead?

**Comment by asaj** [comment]
Dupe of omniscient relayer ticket #1899
