### ISSUE TITLE
Relayer logs should be more meaningful

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1768]
The general goal here is to make the relayer logs more useful

That includes, but is not exclusive to:
- Default verbosity should be `INFO` (might already be)
- Should the "indexed block range" log lines to reduced in verbosity?
- some lower level http logs like `incoming body completed` or `flushed 806 bytes` should be moved to `TRACE`?
- serialize some objects more concisely (`HyperlaneMessage`, `MetadataBuilder`
- remove some traces like [this one ](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-02-06T21:21:14.858063349Z;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22abacus-labs-dev%22%0Aresource.labels.location%3D%22us-east1-c%22%0Aresource.labels.cluster_name%3D%22hyperlane-mainnet%22%0Aresource.labels.namespace_name%3D%22mainnet2%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22relayer%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22moonbeam%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22hyperlane-agent%22%0ANOT%20%22indexed%22%0Atimestamp%3D%222023-02-06T21:21:14.858063349Z%22%0AinsertId%3D%225ha4qxva2b5d2mnx%22;summaryFields=jsonPayload%252Ffields%252Fmessage,jsonPayload%252Ffields%252Freturn:false:32:beginning?project=abacus-labs-dev) or [this one](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-02-06T21:21:25.240271678Z;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22abacus-labs-dev%22%0Aresource.labels.location%3D%22us-east1-c%22%0Aresource.labels.cluster_name%3D%22hyperlane-mainnet%22%0Aresource.labels.namespace_name%3D%22mainnet2%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22relayer%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22moonbeam%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22hyperlane-agent%22%0ANOT%20%22indexed%22%0Atimestamp%3D%222023-02-06T21:21:15.630746550Z%22%0AinsertId%3D%2294xits27oybh5lgg%22;summaryFields=jsonPayload%252Ffields%252Fmessage,jsonPayload%252Ffields%252Freturn:false:32:beginning?project=abacus-labs-dev)
- when there is a `JsonRPCError`, probably don't log it in the inner retries at warn if possible, but when the max number was hit, then do log the errors from at least the last retry
- have dedicated info or warn messages (or maybe debug) when a message could not be estimated, no metadata could be fetched
- Log more data about ISM metadata https://discord.com/channels/935678348330434570/1072862711681142874/1072868391045578812

**Comment by nambrot** [comment]
another good source for real world relayer logs that seem very hard to read https://discord.com/channels/935678348330434570/1063471868742467644/1072155638135795772

**Comment by samtvlabs** [comment]
> another good source for real world relayer logs that seem very hard to read https://discord.com/channels/935678348330434570/1063471868742467644/1072155638135795772

I think these logs are harder than usual to read as i had the `pretty` var enabled. They are easier to parse without it.
