### ISSUE TITLE
Have appropriate diagrams in the docs

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1812]
Our diagrams need an overhaul. This is two parts:

1. We need the source of truth kinda diagrams. These should be done in mermaid for versioning. imo we need the following:
- A basic message passing diagram (showing mailboxes and ISMs, without going to detail about how security works) I.e. on https://docs.hyperlane.xyz/docs/protocol/overview or https://docs.hyperlane.xyz/docs/protocol/messaging
- also diagrams about PI and the deployment of ISMs (v confusing unless you are us)
- A diagram about how warp routes can set security. It can hide the security details away by linking to the above page/diagram

2. For those diagrams, then making more approachable, visually appealing versions of those for blog posts, twitter, etc.

**Comment by anettrolikova** [comment]
Warp Route simple flow: 

![Image](https://user-images.githubusercontent.com/44020788/219211367-54bc1603-9966-464c-b12b-218f7fd81c90.png)

**Comment by yorhodes** [comment]
relevant https://github.com/hyperlane-xyz/hyperlane-token/pull/41

**Comment by anettrolikova** [comment]
This issue is closed but I think we should get better at diagrams in docs. May create new issue on this
