### ISSUE TITLE
SDK should return populated TXs instead of submitting them

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1817]
Currently, `HyperlaneApp` (and also `HyperlaneDeployer`) just submit txs directly with the MP-defined signer and wait for confirmation. That approach is not conducive for some potential users of the SDK, the UI is an example of that. We should learn more about the shortcomings of tx construction and submission so that we change the interface to be more conducive.

**Comment by yorhodes** [comment]
closing in favor of CRUD work
cc @paulbalaji
