### ISSUE TITLE
Build explorer API abstraction layer into MultiProvider

### ISSUE THREAD

**Issue by jmrossy** [hyperlane-xyz/hyperlane-monorepo#1831]
Inspired by comment here: https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/1804#discussion_r1107767728

Goal would be to simplify ContractVerifier code here: https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/pi-sdk/typescript/sdk/src/deploy/verify/ContractVerifier.ts#L66

Would also involve adding optional `apiKey` fields to `ChainMetadata`'s blockExplorers

**Comment by nambrot** [comment]
@jmrossy We did this with smart provider right?
