### ISSUE TITLE
Investigate solutions for faster warp ui route fetching

### ISSUE THREAD

**Issue by jmrossy** [hyperlane-xyz/hyperlane-monorepo#1842]

**Comment by nambrot** [comment]
Last time i checked, this was entirely explained by the default goerli RPC nodes

**Comment by jmrossy** [comment]
It was in the case of lag for a single token, and I also parallelized some things to help out. But it could be better b.c. I think UX would still be mediocre for 10+ tokens, even if RPC is behaving well.

**Comment by nambrot** [comment]
doing this at build time now IIRC @jmrossy
