### ISSUE TITLE
Restructure Agent docs

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1848]
Goal: Make the agent operations guides docs flow better and assume less specific setups

- Just do the structure and then there are specific improvements in follow-on tickets too
    - Use tabs when there is optionality (like the metamask/cast ones)
      - for docker/cargo/binary
      - for signers
      - for checkpoint syncer
    - Add recaps
    - Example structure
        - Section: Validators
            - Page: Guide
                - Installation/Requirements
                    - Break out Cargo/binary/docker
                - Configuration
                    - Required options
                    - Options with different types
                        - Validator signer
                            - Aws kms
                            - hexKey
                        - Checkpoint syncer
                            - S3
                            - localStorage
                                - (Remind folks that they can’t do that with remote validators)
                    - Options you can override
                - Announcement
        - Section: Relayers
            - Page: Guide
                - Installation/Requirements
                    - Break out Cargo/binary/docker
                        - When using docker, remind folks that checkpoint syncer folder has to be mounted
                - Configuration:
                    - Required options
                    - Options with different types
                        - Chain signers
                    - Gas payments/enforcement
                        - (Maybe this should be a separate page)
                        - Point to pay for gas 
            - Page: Message filtering + gas payments?
        - Page: AWS KMS setup when using

**Comment by tkporter** [comment]
Done with the exception of gas payments. I think it probably makes sense to wait till Asa's changes around PI gas payments go through before mentioning anything?

**Comment by tkporter** [comment]
Yup I'm gonna close this and track the gas payment related docs in #1847
