### ISSUE TITLE
Improve agent operator documentation

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1849]
Block on https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1848
- In step 2 (running validator), indicate which file to use when doing PI
- How to specify whitelist, i.e. json serialized string
- Link validators guide
- ~~mention to users how they may have to update the files in the config (i.e. numbers to strings) when using CONFIG_FILES~~ fixed by https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/1885
- Make clear that tracing level is log level
- Separate required values from default values (either in code or in the default config)
    - Tracing level, db_path should just default in code
    - Tracing format should default to pretty
- Document finality blocks and reorg period better

**Comment by asaj** [comment]
> Document finality blocks and reorg period better
@nambrot should we encode defaults for known domains?

**Comment by asaj** [comment]
> mention to users how they may have to update the files in the config (i.e. numbers to strings) when using CONFIG_FILES
Isn't this targeted more towards PI users? We already call this out in a "warning"

**Comment by asaj** [comment]
@nambrot is it possible the ticket title is wrong?

**Comment by nambrot** [comment]
> > Document finality blocks and reorg period better
> @nambrot should we encode defaults for known domains?

You mean encode defaults in the default configs? So i believe we do for finality blocks, just not for reorg period. We could do that for reorg periods too, but it seems like prescribing that to validators seems a bit forceful

This point was about documenting each specific config option and what it is used for and why it matters, so that operators can pick specific values.  Right now that is confusing to folks.

> > mention to users how they may have to update the files in the config (i.e. numbers to strings) when using CONFIG_FILES
> 
> Isn't this targeted more towards PI users? We already call this out in a "warning"

It is, but currently when you jump from the PI guide to the validators guide to run the validator, you might not be on the page to see the warning. Example was @mattiecnvr 's experience: https://www.notion.so/Mattie-Sepolia-73cb798903cf44af91c7070e7a1ad695?pvs=4#47c9f6207c3e43fb89ee03be1750eb42 

I think in general I think information is worth repeating, i.e. it's fine to say in step 1: This config you will need in step 2, in step 2 to say, "here we use the config from step 2", and then on the validator guide again "if you do PI, remember to add this config file".

I personally care less about having a strict "DB-normalized" approach to information in our docs that maybe prioritizes conciseness vs. "denormalized" information that is copied around at the risk of being inconsistent at times.

> @nambrot is it possible the ticket title is wrong?

Totally could be, I tried to group general issues when it came to configuration of the agents

**Comment by mattiecnvr** [comment]
https://app.gitbook.com/o/Pl1c4GYUuMTxkQTcVCdO/s/STktvmwamt5GXWv1jqOM/~/changes/145

**Comment by mattiecnvr** [comment]
What would we default the tmp directory to? Also I am raising a PR to update the code to default the logging but we will also need to remove it from the config since it was getting overriden anyway. Makes less sense to have it in the default config now that we load all the configs.

**Comment by nambrot** [comment]
I think the current default value would be good
