### ISSUE TITLE
Don't check message validity twice when handling messages in routers

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#185]
Copied from https://github.com/bridge-buddies/optics-monorepo/pull/178#discussion_r818585389, which was referencing the `handle` function for GovernanceRouter.sol.

There's some room for gas efficiency for all this message handling logic. E.g. for the call message, right now we're first checking if msg is a valid Call and then calling `tryAsCall()` if so, which itself calls `isValidCall()` a second time. We could consider a function in GovernanceMessage that just returns `_view.castTo(uint40(Types.Call));` (`mustBeCalls` still calls `tryAsCall`).

We should avoid checking message validity twice in GovernanceRouter and any other xapp Routers we have

**Comment by asaj** [comment]
Closing as our applications no longer have this problem :)
