### ISSUE TITLE
Audit `from` agent settings and increase sync speed when far from tip

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1851]
Defaults to 2000 right now if not specified https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/a836ce21d39ea916257fa92a18bb44ff6d1e0194/rust/hyperlane-base/src/settings/chains.rs#L107

We should revisit if that is a reasonable chunk size to default on and for popular chains (or chains with high block production) that folks are likely going to index, we should consider increasing the chunk size to allow catching up to tip to be much faster (i.e. goerli, the rollups, binance and polygon maybe)

Otherwise running a relayer from one of those chains might be annoying

**Comment by asaj** [comment]
@nambrot what is the time to sync for the slowest chain, currently? Ballpark

**Comment by nambrot** [comment]
I don't know but it definitely at least took a minute when I ran the relayer for goerli, and what was worse is that there were no log messages for i think the first minute?

Additionally, we can reduce the RPC consumption with larger page sizes (if they are safe)

**Comment by asaj** [comment]
Goerli took a minute or two for me which was not particularly inconvenient

**Comment by nambrot** [comment]
How long did it take you to get log messages that indicate progress to you? This reminds me, what probably would be useful is to indicate how far behind the relayer is in its indexing

**Comment by nambrot** [comment]
filed https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1872

**Comment by nambrot** [comment]
Fwiw, just ran it again and just getting a bunch of `No message found in DB for nonce` messages with no indicate that anything is being indexed or processing. Only after 2 minutes did anything show up for me. Got up to tip for goerli in about 4 minutes.

Another thing is that the logs get polluted imo when syncing up, i wonder if we should have individual "storing new message/gas payment" events as `INFO` and instead of just have the group of messages/payments as an info log.

**Comment by nambrot** [comment]
So quiknode allows windows of 10k blocks which does noticably improve the time to first message (within 10 seconds).  The biggest difference however is to set the from block for goerli to `8200342` instead of `8039005` (which makes sense). Both of these together improve the indexing to about 30s.

Biggest issue is however that the public ankr node does not seem to support much larger windows.

**Comment by nambrot** [comment]
Kunal said that indexing arbitrum took 3 hours

**Comment by asaj** [comment]
Yeah that's a PITA

**Comment by nambrot** [comment]
If its easy, it might be nice to let infra override the config with larger values for our RPC providers, I think we should be able to pick larger values (I think 10k should be safe). For low-block-time chains like Arbitrum and Optimism, the safe window might actually be higher as well. Like mentioned above, actually adjusting the `from` values might be saving us a lot, we may have chosen not super tight numbers there.

**Comment by mattiecnvr** [comment]
Related to #1256

**Comment by nambrot** [comment]
Chatted offline and basically all we should do is 

```
reduce our wait time when we're far from the tip from 1s -> 100ms (that's 10x there)
```

**Comment by asaj** [comment]
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2004 is a good idea from @yorhodes
