### ISSUE TITLE
Improve agent operations experience using Docker

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1852]
Block on #1848 

  - ~~CONFIG_FILES is unclear what the relative path is in the docker image~~
    - becomes superflous with #1687 and https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1850
  - Should mention how to mount config files into the container
  - Add docker-compose flow

**Comment by nambrot** [comment]
Great call out, capturing that insight

**Comment by mattiecnvr** [comment]
https://app.gitbook.com/o/Pl1c4GYUuMTxkQTcVCdO/s/STktvmwamt5GXWv1jqOM/~/changes/108
