### ISSUE TITLE
Improve Announcement docs

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1853]
Block on #1848 

Problem:
- R,s,v values sometimes do not serialize leading 0s which makes concatenation error prone
- Guide did not show how to announce without an explorer

Suggested scope for changes:

- Serialize announcement signature in announcement.json
- ~~Cast instructions for announcing~~

**Comment by asaj** [comment]
> Cast instructions for announcing

We have this now :)

**Comment by asaj** [comment]
> R,s,v values sometimes do not serialize leading 0s

Should this be a separate thing?

**Comment by asaj** [comment]
> Currently does not account for PI (i.e. no explorer)

What does the explorer have to do with announce?

**Comment by nambrot** [comment]
> > R,s,v values sometimes do not serialize leading 0s
> 
> Should this be a separate thing?

What do you mean by separate thing? Separate ticket?

> > Cast instructions for announcing
> 
> We have this now :)

Thanks!

> > Currently does not account for PI (i.e. no explorer)
> 
> What does the explorer have to do with announce?

In this case I meant block explorer (since there were no cast instructions)

**Comment by asaj** [comment]
> What do you mean by separate thing? Separate ticket?

I meant it's nested under "cast instructions" which doesn't make sense to me

**Comment by nambrot** [comment]
ahh yes, changed the description to hopefully be more clear
