### ISSUE TITLE
Improve AWS Setup documentation

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1854]
- Block on #1848 

Problems:
> Step 5-6 of the AWS setup was a little confusing because it just said to click next once but had to go through a couple pages

- S3 bucket naming is unclear what to put in there for “validator_name”
- S3 permissioning is unclear
    - step 2 is unclear, I did not see "at least one 'User'", I did see a button which says "Users" and that does seem to take me to the right place
    - step 9 is mildly annoying, I don't have two clipboards
- ~~Make testing kms access easier~~ Remove this section, validators no longer need to really know their address, since it's in the `validatorAnnounce` file.
    - ~~Improve section~~
    - ~~Move getting KMS address into hyperlane org or hyperlane-deploy~~
- Consider using the CLI approach instead/additionally

**Comment by asaj** [comment]
> A bit out of date, now you have to go through several pages

@nambrot what are you referring to?

**Comment by asaj** [comment]
I would advocate for CLI tooling rather than the GUI, assuming an AWS CLI

**Comment by nambrot** [comment]
> > A bit out of date, now you have to go through several pages
> 
> @nambrot what are you referring to?

yeah that is confusing phrasing, comes from https://www.notion.so/Mattie-Sepolia-73cb798903cf44af91c7070e7a1ad695?pvs=4#c9956e8a302d43a28a61b0c086401f35

> Step 5-6 of the AWS setup was a little confusing because it just said to click next once but had to go through a couple pages

**Comment by asaj** [comment]
@nambrot should we not point people to their `validatorAnnounce` file instead? I don't see why anyone should be running trevor's tool anymore

> Move getting KMS address into hyperlane org or hyperlane-deploy

**Comment by nambrot** [comment]
Yes indeed!

**Comment by nambrot** [comment]
Closing in favor of https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3341
