### ISSUE TITLE
Add section for common issues with Agent configuration

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1855]
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1735 should technically have some of this in the agent, but folks may miss that, so we should have troubleshooting in the docs as well, probably close to the documentation of the configuration itself.

Block on #1848 

- Missing signer 
  - i think this only happens at tx submission time which sucks ("unknown account")
- Relative URL “”
    - You sure have the url
- Missing field name
    - You sure you load the configuration files

**Comment by asaj** [comment]
Personally I think it's more sustainable to address these things in the binar(ies) rather than in the docs, I'd much rather we focus on that

**Comment by nambrot** [comment]
Absolutely agreed which is why #1735 exists, and would love your eyes on #1814.

I'm happy to get those things out first and see if that is still a problem, but these error messages are very infuriating.
