### ISSUE TITLE
Hyperlane-deploy setup should be easier

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1858]
- Put setup under an explicit Installation/Requirements section
      - Include link to faucets page and ensure balance
      - indicate the need for RPC urls in addition to balance
  - Pin foundry version
  - Separate commands out from ENV vars so that they are easily copyable
  - Separate commands for repo cloning/installation for easy copying
  - Resolve license warning when running yarn

**Comment by asaj** [comment]
> Separate commands out from ENV vars so that they are easily copyable

Suggest bash scripts instead
