### ISSUE TITLE
Improve PI contract deployment docs

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1859]
- Deploy remote ISMs can be very confusing, a diagram would be helpful
  - Artifacts are only shown in output, maybe point to the broadcast folder or write to dedicated file
- ~~Cast instructions for sending test message~~
- ENV var docs do not match (comment talks about private key above the rpc url var)
- export RPC_URL=YOUR_CHAIN_RPC_URL when it should be remote chain rpm url
- Add Common possible issues and workarounds to docs
    - When deploying core contracts
        - Check for typos in REMOTES
            - When deploying the core smart contracts
        - Remove comments from example json
        - Eip1559
        - —slow
        - Make clear that domain ID/chain ID has to be uint32
    -  when sending test message
        - You sure validators are announced
        - Debugging steps with the explorer when it comes or scripts that assess 
- Add recaps

**Comment by asaj** [comment]
> Cast instructions for sending test message

@nambrot why this over the script?

**Comment by asaj** [comment]
I wonder if bash scripts that you edit (or that take args and set env vars for you) would be better? The problem with setting env vars that are used across multiple scripts and need to change is that you could accidentally forget to change DESTINATION_CHAIN

**Comment by nambrot** [comment]
> * Cast instructions for sending test message

You are right, that is not desirable, I forgot the context that caused @tkporter to have to send it via cast 

> I wonder if bash scripts that you edit (or that take args and set env vars for you) would be better? The problem with setting env vars that are used across multiple scripts and need to change is that you could accidentally forget to change DESTINATION_CHAIN

Bash scripts seem heavy imo but the env var reuse is spot on. I feel like command line args would feel better here for env vars that change like `REMOTES`, rpc url

**Comment by asaj** [comment]
> Bash scripts seem heavy imo but the env var reuse is spot on. I feel like command line args would feel better here for env vars that change like REMOTES, rpc url

So the reason I suggested bash scripts is because that would let us make these command line args. I'm not sure how to pipe command line args to forge scripts. If there's a way, we should just do that.

**Comment by nambrot** [comment]
Ahh i assumed you could but looks like you cant. So much for solidity scripting is the future .... I asked in the TG, but yeah bash scripts sound like the way to go

**Comment by nambrot** [comment]
May be partialy addressed by #1864
