### ISSUE TITLE
Update hyperlane-deploy artifacts

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1860]
Problems encountered:
- mainnet configs seem to be missing, but the example specifies mainnet remotes
- what are the IGPs used for?
- confused by the presence of artifacts of other chains in `networks.json` (like IGPs, proxyadmins, etc.)
- confused by create2Factory presence in artifacts
- someone noticed that the shape of validator configuration in the sdk and infra is different from hyperlane-deploy
- confused by the presence of the owner of contracts on the default chains

OLD:

Possible mitigations are:

- Mainnet configs for ISMs
- IGPs ?!?
- Probably remove all things but the mailboxes for the other chains?
- Maybe write a script that does the artifact updating or at least have the shape match what’s in infra/sdk
- Remove unnecessary fields from network.json
    - Owner of default chains
    - IGP, proxyadmin, etc.

**Comment by asaj** [comment]
> IGPs ?!?
I'm not sure we should aim to provide first class support gas payments in PI until we've ironed out the kinks

**Comment by asaj** [comment]
I'm not sure that these are the right things to do if we want to solve the more general problem of "hyperlane-deploy config can be confusing"

**Comment by asaj** [comment]
Should we fold https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1862 in?

**Comment by asaj** [comment]
Like I suspect this will result in some config refactor effort like @yorhodes and I have already tried in https://github.com/hyperlane-xyz/hyperlane-deploy/pull/2 and https://github.com/hyperlane-xyz/hyperlane-deploy/pull/12 respectively

**Comment by asaj** [comment]
This should be maybe blocked on @jmrossy 's work on config?

**Comment by jmrossy** [comment]
> This should be maybe blocked on @jmrossy 's work on config?

That'll be merged in an hour or so

**Comment by nambrot** [comment]
May be partially addressed by #1864
