### ISSUE TITLE
Reconsider foundry for hyperlane-deploy

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1864]
Problems:
- Can’t import/use sdk constants
- JSON parsing
- JSON serializing string number
- The broadcast feature means that artifacts can be written during simulation for contracts that didn't actually get deployed.

**Comment by asaj** [comment]
> broadcast

What do you mean by this?

**Comment by nambrot** [comment]
> > broadcast
> 
> What do you mean by this?

Clarified, basically the writing of the contracts to file when issues occurred during tx submission
