### ISSUE TITLE
Overhaul Agent configuration/CLI configuration

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1865]
This ticket captures work to more fundamentally rearchitect agent configuration. This can either look like changing the current `config` library to not be based around the path-encoding ENV vars, but something more conventional. That possibly could be a lot of work and backwards compatability has to be considered, so this ticket is an `investigate` ticket.

An alternative could be a CLI that builds configuration in a wizard like fashion (and could be reused for other configuration).

Previous version:

Configuring Agents (and hyperlane-deploy) is super manual and the configuration surface area is massive (and super awk with ENV vars). There are related but also separate things to think about:

- Overhaul agent configuration
The current way to building up an object from config files and ENV vars that encode the path in it is not intuitive to most people. At the same time, changing that can be quite difficult. Maybe there are smaller scope things that can be done in the short-term (i.e. are command line args possible) but it is possible that the only way forward is a rewrite of the configuration loading part. (see https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1593 for further context

- CLI for configuration building
avalanche and others have some very nice CLIs that basically build configuration through interactive wizards, store configuration in persistent memory and make it accessible-exportable. This could help with our config woes as operators could just use this to ultimately get the config they desire (either at that "wizard-time", or it specifies which exact ENV vars to set).

**Comment by nambrot** [comment]
In general, i think folks don't look at docs or guides to figure out what to run, but more often than not just run the binary/container. Ideally, the error message should indicate things like required/optional flags, how to format, etc.

**Comment by mattiecnvr** [comment]
https://discord.com/channels/935678348330434570/1088882379923390566

**Comment by nambrot** [comment]
It just occurred to me, how hard is it to extend the current configuration scheme we have to use command line args? I know we don't love our current scheme, but as far as I can tell it might be not that dificult maybe?

**Comment by nambrot** [comment]
Splitting out #2034 and #2033 , and keeping this as an investigate for a larger effort

**Comment by jmrossy** [comment]
Related: https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2573
