### ISSUE TITLE
Non-on-chain-fee-quoting IGP for use on PI chains

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#1871]
Related: https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1857

We shouldn't force PI chains to use on chain fee quoting. Instead, we should provide them an IGP that receives payment but doesn't require payment. As we move over to on chain fee quoting, we'll want to have an IGP contract still in the monorepo that hyperlane-deploy uses that doesn't involve on chain fee quoting

**Comment by nambrot** [comment]
Sorry what do you really mean here? What would that IGP quote as payment? I would assume we have multiple IGPs (we probably should rename the current one to `QuotingIGP`) and maybe have a default "NoOpIGP" or something that just has a static payment requirement (which could be 0)?

**Comment by tkporter** [comment]
this is `NoOpIGP` as you describe it

**Comment by nambrot** [comment]
@asaj @tkporter IIRC what we talked about, we said we instead would just make deploying `StorageGasOracles` easier that have static amounts?

**Comment by asaj** [comment]
Yup yup
