### ISSUE TITLE
Docs should be more clear as to which API you should use for what use case

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1875]
If you are a builder coming to Hyperlane and you kinda know you need something cross chain, our docs don't help you out a lot on where you should start.

Pages like:
- https://docs.hyperlane.xyz/docs/introduction/getting-started
- https://docs.hyperlane.xyz/docs/build-with-hyperlane/quickstarts

don't seem sufficient. Also the APIs section feels a bit out of place, maybe it should be part of the `Build with Hyperlane` section?

Ultimately, the need we need to solve is that builders need to understand what tools are at their disposal and what they can do with that. We mostly show right now how those tools work.

**Comment by anettrolikova** [comment]
To improve https://docs.hyperlane.xyz/docs/sdks/building-applications

We can also have Tools and Build with Hyperlane section but unsure if that's not too conflicting with persona type docs

**Comment by anettrolikova** [comment]
API section needs intro

**Comment by anettrolikova** [comment]
this issue relates to #1707

**Comment by nambrot** [comment]
Build with Hyperlane, here are the tools you can use:

Accounts API
-  You can use the accounts API to have an account make function calls on another chain, like a DAO can own assets on other chans
- You could build a EIP5164 implementation, safe integration, tally integration

Queries API
- You can use the queries API to read state from a remote chain, for example read a pricefeed on Ethereum from BSC

Message API
- Anything that doesn't fit in the above, you can use Hyperlane messaging to send and receive arbitrary bytes between your contracts on different chains.

Warp Routes API
- Looking to have a representation of a token from one chain, on another? Use Warp routes to quickly create a bridge without writing any code

Permissionless Deployment
- Looking to do any of the above, but Hyperlane is not on there? You can use PD to deploy hyperlane to that chain and then use that to have your app do stuff on there

**Comment by nambrot** [comment]
People are constantly confused about warp routes vs. liquidity layer

**Comment by nambrot** [comment]
https://app.gitbook.com/o/Pl1c4GYUuMTxkQTcVCdO/s/STktvmwamt5GXWv1jqOM/~/diff/~/changes/184/build-with-hyperlane/quickstarts/quickstart-tutorial-1/~/comments/JFK9SyjcEabpXyOzmfR0
