### ISSUE TITLE
IQS callbacks are difficult to use

### ISSUE THREAD

**Issue by asaj** [hyperlane-xyz/hyperlane-monorepo#1889]
A recent experience using IQS suggests that the current callbacks API is not easily understood

A points of confusion
- User was using the wrong selector, and including arguments in the callback that would also be appended by the query
- User used abi.encode for his callback, not encodePacked
- User added the onlyCallback modifier to some functions unnecessarily (e.g. a view function)

**Comment by asaj** [comment]
@yorhodes and I have talked at length in the past about the following psuedo-interface:

```
interface IUsingIQS {
  function resolve(bytes32 messageId, bytes returnData) onlyCallback;
  function reject(bytes32 messageId, bytes returnData) onlyCallback;
}
```

IMO moving to this interface would address all of the problems the user ran into.

- No need to specify a selector, or worry about how arguments get appended, you get the return value(s) straight up
- No need to encode the callback
- onlyCallback modifier goes in the same two functions every time, rather than different functions depending on the calling contract

**Comment by nambrot** [comment]
I would imagine that this interface is quite nice for building higher-level abstractions on top as well, though I do wonder whether folks needing to cast the returnData themselves is foreign to many developers. I've been looking at Chainlink's documentation https://docs.chain.link/any-api/get-request/examples/single-word-response/ and wondering if the interface should actually be closer to CL (which does make you specify callbacks as well)

**Comment by yorhodes** [comment]
> wondering if the interface should actually be closer to CL (which does make you specify callbacks as well)

do you mean this? 
 https://github.com/smartcontractkit/chainlink/blob/20fc3a50847bca5b21a41ad3993a4465c200a0ea/contracts/src/v0.6/Oracle.sol#L71

I do think the callback selector is more composable -- eg existing contracts with multicall support (DAOs?) can receive callbacks with the current interface but couldn't support the proposed resolve reject interface

I don't have a good demonstrative use case for this requirement though

**Comment by asaj** [comment]
So I agree the callback selector is strictly more efficient and flexible, I think it's just significantly more confusing than the callback approach above.

IMO there's a tradeoff here between understandability/simplicity and efficiency/flexibility. I see the current IQS interface as maxing the latter, I'd suggest we try to prioritize understandability/simplicity a bit more.

**Comment by asaj** [comment]
> Any extra context data would otherwise have be stored for each messageId

Indeed, I'm personally comfortable with this tradeoff

**Comment by avious00** [comment]
closing in favor of IQS v2 redesign https://github.com/hyperlane-xyz/issues/issues/607
