### ISSUE TITLE
Utils ParsedMessage type conflicts with calculator ParsedMessage type

### ISSUE THREAD

**Issue by jmrossy** [hyperlane-xyz/hyperlane-monorepo#1892]
https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/typescript/sdk/src/gas/calculator.ts#L67

https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/typescript/utils/src/types.ts#L43

There should be only 1 and it should probably be the utils verson

**Comment by asaj** [comment]
FYI I'm deleting the calculator in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/1907

**Comment by nambrot** [comment]
Closing this unless anyone objects
