### ISSUE TITLE
Relayer backoff results in 5 minute delay

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1896]
From: https://discord.com/channels/935678348330434570/935678739663192184/1081348632101519420

Just did the Circle Demo and one thing I found was that the message took a surprisingly long time to process. Logs are here: https://cloudlogging.app.goo.gl/VoYwPgRLxpU5grZ59, explorer link https://explorer.hyperlane.xyz/message/ed42f4dfd5ce96aa6e027a603d4b55bd33b8d6bb2f4cb5d107112861af47f127

I first suspected that it's the underlying Circle transfer that took so long, but that wasn't the case. Instead I think its our backoff logic: https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/03d32f4009611ae4afd044c1e95a89d2676b7df0/rust/agents/relayer/src/msg/serial_submitter.rs#L196

IIUC, what happened is that we retried to message in quick succession 16 times in the span of 20 seconds, and after 16 times, we basically enforce a minimum 5 minute wait. I'm sure there is a meme somewhere about how hard it is to specify good backoff functions, but IMO we should something like "step-function-y"? I.e. something along the lines of 1,2,4,8,16,32,45,60,75,90 seconds etc. until 5 minutes, and then retry every 5 minutes?

Separately, it looks like "rusoto_core::request" log lines are a bit verbose, even at DEBUG, idk that individual HTTP headers need to be logged? cc @mattiecnvr

**Comment by nambrot** [comment]
@mattiecnvr let me know if you want me to make a separate issue for this, but just ran into the verbose log lines again. I think a bunch of lower level networking is exposed which we should imo only show on TRACE

**Comment by nambrot** [comment]
@tkporter you didn't have a separate issue for this, but i think you saw this too?

**Comment by tkporter** [comment]
This was just related to https://github.com/hyperlane-xyz/issues/issues/415
