### ISSUE TITLE
ERROR: Liquidity Layer API 

### ISSUE THREAD

**Issue by megabyte0x** [hyperlane-xyz/hyperlane-monorepo#1936]
# ERC20 ERROR while using `dispatchWithTokens`

Source: [Link](https://docs.hyperlane.xyz/docs/apis/token-bridge-api#interface)
Time: 13-March-2023
Transaction: [Link](https://mumbai.polygonscan.com/tx/0xc9eabd5c06f41f97d98c6f61e1ac45c6fca51d1537dbffdd2d87aab3c429a8fa)

## Parameters Entered:
`_dispatchDomain`: 5
`_recipientAddress`: 1cb30cb181d7854f91c2410bd037e6f42130e860000000000000000000000000
`_token`: 0000000000000000000000003c68ce8504087f89c640d02d133646d98e64ddd9
`_amount`: 1
`_bridge`: Portal
`_messageBody`: 0x00

## Output 
**ERROR**
```
Fail with error 'ERC20: transfer amount exceeds allowance'
```

## Expected Output:
**Successfull**

## What I tried:

- Changing the token to WETH and USDC back and forth on Polygon. 
- Getting additional tokens from AAVE testnet to rectify the error if possible.

**Comment by nambrot** [comment]
Putting this on #1729 instead
