### ISSUE TITLE
RetryingProvider shouldn't retry reverting eth_calls

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#1944]
See https://github.com/hyperlane-xyz/issues/issues/412 for context

Each RPC provider / chain has different error codes, but generally they all include `"revert"` in the error. Something dead simple like `if response.contains("revert")` feels sufficient

Consider adding this to FallbackProvider too?

**Comment by asaj** [comment]
+1 to adding to fallback, and note that we should restrict to `eth_call`

As a shortcut we could just not retry eth_call

**Comment by tkporter** [comment]
See https://github.com/hyperlane-xyz/issues/issues/414 for expanded scope for this - we should probably also not retry for `eth_feeHistory` calls

**Comment by tkporter** [comment]
re: not retrying eth_calls, note that I believe the way the validator is written now it doesn't gracefully handle eth_call errors and expects the retrying provider to protect against failed RPCs. Otherwise I think the validator will crash
