### ISSUE TITLE
Deprecate ProxiedContract and ProxyAddresses

### ISSUE THREAD

**Issue by asaj** [hyperlane-xyz/hyperlane-monorepo#1953]
Because our contract addresses are sometimes flattened, sometimes not, buildContracts will sometimes give you a Contract, sometimes a ProxiedContract.

Because the ProxiedContract type is not transparent, it matters.

We should also consider removing the proxy information from the addresses artifacts.

If/when we need to know if a contract is proxied, we can just query the chain for the bytecode.

Similarly, if we need to know the implementation (or admin), we can query storage slots directly.

**Comment by nambrot** [comment]
spicy, i'm sure @yorhodes has a take here

**Comment by asaj** [comment]
@yorhodes is this ticket's biggest champion

**Comment by asaj** [comment]
@yorhodes would this allow us to derive XContracts and XAddresses types from XFactories?

**Comment by asaj** [comment]
@nambrot for context I hit this a bunch where I didn't really know what I would get out of `buildContracts`, and so e.g. didn't know if I needed mailbox.dispatch or mailbox.contract.dispatch.

I expect if we don't do the above we will see this sort of thing a bunch

**Comment by nambrot** [comment]
its been too long but personally very sympathetic to hide the fact that contracts are proxied from sdk consumers (not from the docs tho)
