### ISSUE TITLE
Interchain GasPayments should be easily digestable from the docs

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1988]
IGPayments are nested under Build => Guides => Interchain Gas Payments which makes it not easy to discover. We should have pages in the APIs (Reference) and Protocol (Architecture/Design) sections

**Comment by tkporter** [comment]
Agree this is worth doing but I've been prioritizing other things atm to avoid the context switch, will do it this week

**Comment by asaj** [comment]
Merged docs update
