### ISSUE TITLE
PI Interchain Queries Design

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#1993]
## Problem: 

Currently the queries middleware uses the static router pattern and cannot be used on non-enshrined chains.

In the same spirit of [PI ICAs](https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/1832), the user should be able to optionally specify which destination contract should receive the interchain query message.

Related: https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1889 https://github.com/hyperlane-xyz/issues/issues/400

## Desirable Features:

- Only inherit security guarantees of queried => querying chain transport layer for maximal utility to longtail PI chains
- Minimize gas overhead and latency of round trip Hyperlane messages incurred for query
- Prevent "timetravel" attacks where a stale response can be delivered to a fresh query by associating with a nonce

### Router Overrides

```solidity
function queryWithOverride(
    uint32 _destinationDomain,
    bytes32 _destinationRouter,
    CallLib.StaticCallWithCallback[] calldata calls,
) public returns (bytes32 messageId);
```

Router override allows the user to query a non default domain. **Note: ISM overrides are not necessary as in the ICA case.**

### One-way verification

```solidity
contract QueryIsm is IInterchainSecurityModule {
    function verify(bytes calldata _metadata, bytes calldata _message)
        public
        pure
        returns (bool)
    {
        InterchainQueryMessage.MessageType messageType = InterchainQueryMessage.messageType(_message);

        // noop on queries
        if (messageType == InterchainQueryMessage.MessageType.QUERY) {
            return true;
        }

        // messageType == MessageType.RESPONSE
        return ism.verify(_metadata, _message);
    }
}
```

No metadata requirements on `QUERY` message types enables "instant" queries and cheap verification on queried chain (likely ethereum).
Potential damage done by malicious queries is mitigated because only view calls are performed.

#### Dispatch on querying chain
```solidity
uint256 nonce = mailbox.count();
bytes memory body = abi.encodePacked(nonce, msg.sender, calls);
uint256 messageId = dispatch(_destinationDomain, _destinationRouter, body);
status[messageId] = DISPATCHED;
return messageId;
```

#### Handle on queried chain
```solidity
// derive origin (Hyperlane) message and id
bytes memory originMessage = Message.formatMessage(
    VERSION,
    body[0:32], // nonce
    origin, // origin domain from handle
    sender, // origin router from handle
    localDomain,
    address(this), // destination
    body // message body from handle
);
bytes32 originMessageId = originMessage.id();

// result = body.calls();
// querier = body.sender();

bytes memory responseBody = abi.encodePacked(originMessageId, querier, result);
dispatch(origin, sender, responseBody);
```

#### Handle on querying chain
```solidity
bytes32 messageId = body[0:32];
require(status[messageId] == DISPATCHED, "message not dispatched");
status[messageId] = HANDLED;

// resolve result on querier
```

**Comment by yorhodes** [comment]
### Alternative "timetravel" mitigation 

If we want to avoid the overhead of a nonce, we can instead use a timestamp to prevent "timetravel" attacks.
This requires consumers of the query API to handle staleness of results themselves.

#### Handle on queried chain
```solidity
// result = body.calls();
// querier = body.sender();
uint256 stamp = block.timestamp;
bytes memory body = abi.encodePacked(stamp, querier, result);
dispatch(origin, sender, body);
```

#### Handle on querying chain
```solidity
// resolve (stamp, result) on querier
```

**Comment by nambrot** [comment]
Obviously you guys have thought about this and I haven't but would love to get a bit more convinced that the no-op ISM thing works:

Happy path:
- Sender S specifies query X with callback C
- IQS on origin sends it over in message M, IQS on destination makes view call and sends message O back (which includes S)
- IQS ISM on origin verifies message O, and triggers callback C on S with the query result of X.

Possible attack:
- attacker crafts a malicious message pretending that Sender S specified query Y with callback C
- IQS with the no-op ISM will accept the message, do query Y and send a message P "back to origin"
- IQS ISM on origin verifies message P, and trigegers callback C on S with the query result of Y.

What am I missing?

**Comment by asaj** [comment]
The messageID will not be present on the origin chain IQS router, and so it will be rejected

**Comment by avious00** [comment]
@yorhodes closing as not planned, but linked it to newer token balance migration/IQS V2 tech design issue
