### ISSUE TITLE
Warp Template UI demo deployment should work

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1995]
I think something wtih the transfer modal doesn't work

https://discord.com/channels/935678348330434570/935678477246554132/1088158668488454374

**Comment by jmrossy** [comment]
Fixed with https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/commit/04ae98a5d9da7369947aef4ce8b7f2882da8c613
