### ISSUE TITLE
Warp route transfer progress should be accessible

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1996]
- The label doesn't change, it keeps suggesting to sign with metamask even after signature
- It's too easy to loose the transfer modal, and then it seems impossible to get back to it (that happened to me after trying to click on the explorer link of the toast notification)
- probably would be nice if there is a way to persist that in the URL to come back to it

**Comment by jmrossy** [comment]
Fixed in https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/21
