### ISSUE TITLE
Indexed contracts store deployment block number immutably

### ISSUE THREAD

**Issue by asaj** [hyperlane-xyz/hyperlane-monorepo#2004]
h/t @yorhodes on https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/1907#discussion_r1140512096

This would allow agents to index contract events optimally without any config beyond contract addresses.

**Comment by yorhodes** [comment]
```sol
contract Indexable {
    uint256 public immutable index = block.number;
}
```

**Comment by nambrot** [comment]
@asaj with the backwards cursor, do you still feel like this is valuable to change?

**Comment by avious00** [comment]
@yorhodes is this related to v3?
