### ISSUE TITLE
Explorer should indicate if quorum is impossible

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2032]
The explorer equivalent for #2031.

 A common issue is if the MultisigISM that is used (either on the mailbox or on the recipient) that does not actually have any validators set for the origin of the message

**Comment by jmrossy** [comment]
@nambrot can you outline the high level approach for how to check this?

**Comment by nambrot** [comment]
Of course.

- Get the ISM that verifies a particular message (`Mailbox#recipientIsm(address recipient)` function)
- fetch the ISM module type and check if its LEGACY_MULTISIG = 3 (if not, ignore)
- call `validatorsAndThreshold(bytes calldata _message)` with the message on the ISM
- if the validators list is empty and the threshold is 0, quorum is impossible and we should indicate that
