### ISSUE TITLE
Preflight checks

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2038]
Deployers should have pre-flight checks that indicate to users that a deploy is likely to encounter issues and abort the deploy. Probably should allow overriding those if desired.

Checks to implement:
- Check if signer balance is large enough to complete deploy
- Check if a collateral token actually exists on the chain
- Check if the specified IGP actually can quote payments for all specified remotes

**Comment by nambrot** [comment]
Related is https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1729#issuecomment-1501155601

IsmDeployer should check that the config is valid

**Comment by nambrot** [comment]
When doing a warp route deployment (or generally a router deployment), there should be preflight checks that see if the ISMs specified can actually support the warp route

**Comment by asaj** [comment]
@nambrot unfortunately this is pretty difficult. How would you check this?

> there should be preflight checks that see if the ISMs specified can actually support the warp route

**Comment by asaj** [comment]
> IsmDeployer should check that the config is valid

@nambrot what does this mean? Configs are typed, what does an "invalid" config look like?

**Comment by asaj** [comment]
> Check if the specified IGP actually can quote payments for all specified remotes

@nambrot, what is the problem that someone ran into? This is a solution but it's underspecified, I have no idea where it should go because I don't know where this issue came up.

**Comment by nambrot** [comment]
> @nambrot unfortunately this is pretty difficult. How would you check this?
> 
> > there should be preflight checks that see if the ISMs specified can actually support the warp route

Could we not check that if a warp route is configured for chains x,y,z that on x, the specified ISM is a multisig ism (via module type) and then construct a message coming from the remotes (y,z) to pass to `validatorsAndThreshold` and see if the threshold is 0? I get that there are possible edge cases to this, but I would imagine it is very unlikely for developers to run into that?



> > IsmDeployer should check that the config is valid
> 
> @nambrot what does this mean? Configs are typed, what does an "invalid" config look like?

IIRC, somebody specified a threshold that was larger than the list of validators. We should also validator lists to be not empty. And then I forget if we are validating that here is a config at all for a given chain, but if not, we should



> > Check if signer balance is large enough to complete deploy
> 
> @nambrot unfortunately we don't know what the cost of deployments are, since they vary by config, remotes, etc.
> 
> What we do now is just check that your balance is non-zero, best we can do is pick a gas amount and require that your balance is at least amount * current gas price.

I think that would be a great heuristic



> > Check if the specified IGP actually can quote payments for all specified remotes
> 
> @nambrot, what is the problem that someone ran into? This is a solution but it's underspecified, I have no idea where it should go because I don't know where this issue came up.

The issue here was that somebody deployed a warp route with the default IGP which did not know about a particular destination PI chain. I think this preceded the merge of hyperlane and warp route deployment, but is IMO still a useful check to make (similar to the ISM one)
