### ISSUE TITLE
Add decimals to StorageGasOracle & IGP contracts

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2066]
Coming out of https://discord.com/channels/935678348330434570/1090317341604196445, we'll be configuring on chain # of decimals of the remote chain and of the local chain. IGasOracle should be changed to return the # of decimals of a remote chain, token exchange rates will mean the exchange rate between one "whole" remote token and one "whole" local token regardless of decimal count, and the IGP will adjust calculations to the correct order of magnitude

This tracks the contract changes & changes to the gas oracle tooling

**Comment by nambrot** [comment]
@tkporter were you planning on taking this on in this sprint?

**Comment by tkporter** [comment]
no
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2067#issuecomment-1505786410

**Comment by tkporter** [comment]
Think this will take 1 or 2 days
