### ISSUE TITLE
Places where MultiProvider's handleTx is used should be using tx overrides

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2087]
It seems like we use MultiProvider's `handleTx` function as if it were injecting transaction overrides for us. But handleTx is too late to inject overrides. Only `prepareTx`, `sendTransaction`, and `estimateGas` use the overrides

Instead, we should move to using populated transactions. Maybe there's a way to still use handleTx but to pass in a closure instead?

**Comment by yorhodes** [comment]
closing in favor of #3547 work
