### ISSUE TITLE
Config errors always list `HYP_BASE_*` as the env prefix

### ISSUE THREAD

**Issue by mattiekat** [hyperlane-xyz/hyperlane-monorepo#2098]
We currently support two env prefixes for every agent, `HYP_<AGENT>_*` and `HYP_BASE_*`. The problem is that for a first version of #2070 agent config parsing we did not have an easy enough way to denote the source of this config and that may lead to confusion by operators who are not using the `HYP_BASE_*` prefix.

The solution I propose to fix this is actually not to fix the config errors but actually to remove support entierly for alternative config prefixes and replaces all of them with `HYP_*`. This would also be a good opportunity to make other breaking config changes such as #532/#2091 as operators will already be forced to update configs.

**Comment by asaj** [comment]
Folks are already hitting this

**Comment by nambrot** [comment]
@mattiecnvr Would you suggest to do this in a backwards compatible way? I.e. support prefix and no prefix?
