### ISSUE TITLE
More clearly display unknown chains in hyperlane explorer

### ISSUE THREAD

**Issue by mattiecnvr** [hyperlane-xyz/hyperlane-monorepo#2102]
One of our users set up a relayer to zkEVM and was confused why his message has been pending for 20+ min (even though it was presumably delivered) because the explorer still shows it as pending.

Obviously we won't have the deliver information for the other chain or the sending information, but we do know that we won't see it so we could update the delivery info to more clearly indicate that it is an unsupported chain.

This is the message:
https://explorer.hyperlane.xyz/message/0x06923747afbbf1e00f15dcefd8272ad1e8b643210e8b51ddf69a00070000e2e3

I also think it might be helpful to show delivered messages even if we don't have the sending info. (Might require a change to the DB).

From:
https://discord.com/channels/935678348330434570/1096444620172431410/1096831534813683712

**Comment by mattiecnvr** [comment]
@nambrot Assigning to you for prio

**Comment by nambrot** [comment]
Yeah we have a bunch of work slated to support this
