### ISSUE TITLE
Agents cannot handle mixed case chain names

### ISSUE THREAD

**Issue by asaj** [hyperlane-xyz/hyperlane-monorepo#2103]
Seemingly, at least

https://discord.com/channels/935678348330434570/1096444620172431410/1096800853882572860

**Comment by nambrot** [comment]
Ohh good catch, @mattiecnvr do you know how easy/hard it would be to account for this? I assume this would be just a matter of lowercasing the chainnames everywhere? Or maybe better is to just throw an error, but discover when there likely is a typo? (one of my favorite compiler features in Rust and others)

**Comment by mattiecnvr** [comment]
I'd be down for just lower casing them. Case sensitive names is probably not a feature we want to support at this time. I see more ways for it to cause issues than help things.

**Comment by nambrot** [comment]
Well we support it right now technically right? It's just that it is not obvious that we do? I actually like the idea of just detecting minor typos
