### ISSUE TITLE
Confusion over CONFIG_FILES path between binary and docker setup

### ISSUE THREAD

**Issue by asaj** [hyperlane-xyz/hyperlane-monorepo#2106]
Some folks seem to be unfamiliar with how docker mount works, and try to use the same path for both docker and binary setup

**Comment by asaj** [comment]
We might consider either:
- Mounting config to the same path as on the local fs, so that you don't have to understand this
- Have the instructions default to the simplest setup across the board (i.e. docker + local keys) and then have entirely separate pages showing how to do more complex things

**Comment by nambrot** [comment]
Absolutely agree, docker mounting directories is very unintuitive, and we should avoid this as much as possible. I wonder if we actually maybe should support just storing the signatures on the origin chain for test setups, that would avoid a lot of headaches.

Another alternative is to get rid of docker prescription and have binaries

**Comment by nambrot** [comment]
Curious if @tkporter has any thoughts here
