### ISSUE TITLE
Hyperlane-deploy changes after EthTokyo

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2114]
Problems:
            - Having to type yarn ts-node scripts/deploy-hyperlane, do I need to know that it is ts-node?
            - A bit unclear on what test-messages does (other than giving binary success conditions)
            - Using space delimiter for —chains params is unfamiliar
            - Can’t easily just send a test-message in a single direction

Possible solutions:
            - Have yarn commands to hide the ts-node/.ts script files, i.e. yarn deploy-hyperlane
            - ~~Point to explorer where possible in test-messages~~ https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2358
            - Allow for custom test message and show in both explorer and etherscan the result of the test
            - Use comma delimiter for list of chains
            - Make test-messages uni-directional

**Comment by nambrot** [comment]
@yorhodes I think yesterday you had some questions about the scope?
@asaj Yesterday, IIRC, you expressed some concerns about the scope?

**Comment by asaj** [comment]
> - Having to type yarn ts-node scripts/deploy-hyperlane, do I need to know that it is ts-node?

Can you elaborate on how this caused a problem? I'm surprised anyone ran into difficulties here, given commands are presumably copied and pasted

**Comment by asaj** [comment]
> - A bit unclear on what test-messages does (other than giving binary success conditions)

Can you provide more context on what this looked like? Presumably you're saying that someone ran this script and then was confused about what it did? The docs say:
```
You can check everything is working correctly by sending a test message between each pair of chains.
```

**Comment by asaj** [comment]
> - Using space delimiter for —chains params is unfamiliar

Can you elaborate on what problems this caused?

**Comment by nambrot** [comment]
> > * Having to type yarn ts-node scripts/deploy-hyperlane, do I need to know that it is ts-node?
> 
> Can you elaborate on how this caused a problem? I'm surprised anyone ran into difficulties here, given commands are presumably copied and pasted

I don't know that it is a problem per-se, but it seems preferable to to have the simpler `yarn deploy-hyperlane` instead of `yarn ts-node scripts/deploy-hyperlane.ts`, even if most folks would just copy/paste (but i def dont feel strongly on this one)

> > * A bit unclear on what test-messages does (other than giving binary success conditions)
> 
> Can you provide more context on what this looked like? Presumably you're saying that someone ran this script and then was confused about what it did? The docs say:
> 
> ```
> You can check everything is working correctly by sending a test message between each pair of chains.
> ```

When I was talking with developers I sometimes got the sense they didn't really know what sending a test message meant. This may be a more egregious example but one person did not realize that a validator and relayer had to be running for messages to be delivered. I think more generally if you are not very familiar with interoperability then I could see how just saying test message was sent or not sent would not be enough to help with debugging. I think being more verbose with what a test message actually does at each step and each of the artifacts that let you observe the success would be a helpful background when something then does not work.

> > * Using space delimiter for —chains params is unfamiliar
> 
> Can you elaborate on what problems this caused?

No problem, but @yorhodes mentioned it here https://www.notion.so/Permissionless-Interoperability-Deploy-DX-Game-Yorke-6e0bec56e36647a6a7136bcb3bd1726f?pvs=4#baa7944328e8435ca6632683455d4b77



> > * Can’t easily just send a test-message in a single direction
> 
> Can you explain in what context someone wanted to do this?

Somebody tried to debug one way of messages not working and lamented how it sending messages in the other way (which worked) was noisy, spend unnecessary funds and latency

**Comment by nambrot** [comment]
Capturing the unidirectional message part in here https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2238
