### ISSUE TITLE
Explore solutions for improving FallbackProvider reliability

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2115]
Problems:
            - ~~Fallback provider aggregates the underlying errors which makes them hard to parse and produce large logs~~
            - Intermittent problems with the network connection can lead to failures
            - https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/031f0a9692ec1c631c8921fb25864aff4377f2c0/typescript/sdk/src/deploy/HyperlaneDeployer.ts#L91 shows null at times

Possible solutions:
            - ~~We should modify fallback provider to catch and identify the actual underlying error for better legibility~~
            - We should consider wrapping the fallback provider with retry providers as well to be more resilient to intermittent network

**Comment by jmrossy** [comment]
@nambrot RE  `this.multiProvider.tryGetExplorerAddressUrl` returning null, that's intentional. It happens when the chain metadata doesn't have any block explorers (like for a PI config that didn't include one). In that case HypDeployer uses the address instead

**Comment by jmrossy** [comment]
Seems like all the other feedback is around FallbackProvider. Renaming this ticket to reflect scope better.

**Comment by nambrot** [comment]
> @nambrot RE `this.multiProvider.tryGetExplorerAddressUrl` returning null, that's intentional. It happens when the chain metadata doesn't have any block explorers (like for a PI config that didn't include one). In that case HypDeployer uses the address instead

I guess the issue is that the log line IIRC shows something like `Deploying from null`, though IIRC, maybe @asaj has fixed this recently

**Comment by asaj** [comment]
I think I fixed this, not certain

**Comment by jmrossy** [comment]
Relevant: https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2129/files#diff-052e25dca2614e17e27ee066275ea9748f4603d23bd1226b91e142baa1a51515R504

**Comment by nambrot** [comment]
Commented
