### ISSUE TITLE
Manual validator announce is cumbersome

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2120]
Problem:
            - Validator announce is easy to miss
            - Validator announce is annoying to do manual with cast (and the only reason why you still need foundry)
Possible Solution:
            - Hyperlane-deploy should have a command that allows the announcement of a validator by just pointing to the announcement file
            - Relayer should indicate if the reason for quorum is that the validator(s) have not announced themselves

**Comment by asaj** [comment]
Another possible solution:
- Ask validator key to have some funds, automagically announce itself if it isn't already announced
