### ISSUE TITLE
Explorer shows no gas payment prematurely

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2122]
When the scraper has not yet indexed the gas payment, the explorer will show a message as undeliverable due to a lack of gas payment with bright red. In the first couple of seconds or maybe minutes, maybe it shouldn't be that confident that the payment hasn't been made, just that it hasn't been found (yet)

**Comment by jmrossy** [comment]
Hmm, not sure how to handle this. If a payment hasn't been made we do want to clearly surface that as an error right (as we do now)? 
One option would be to not who an error until a certain amount of time has passed. Crude but might help.
Would also help to improve the scraper. In theory the events marking a gas payment should be available as soon as the block containing them is finalized.

**Comment by nambrot** [comment]
Yeah, it's not super straightforward, which is why i stashed it in the backlog for now. Honestly the easy thing to do would be to just not make super bright red and mention how it could be a while until it's indexed

**Comment by jmrossy** [comment]
It would take a bunch of hacking to not show the red banner for delivery failure debugger results for _just_ gas which I'd rather not do, so I'll just disable the red banner entirely for now.
