### ISSUE TITLE
Hyperlane-deploy only deploys per single PI chain

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2123]
Problem:
- If you are connecting multiple PI chains, you need to run hyperlane-deploy multiple times which is confusing and inconsistent how all the other deployment scripts work we have (i.e. infra and warp routes)

Possible Solution:
- Hyperlane-deploy should only need to be run once, and the run should identify which contracts need to be deployed on which chains

**Comment by nambrot** [comment]
cc @asaj @yorhodes for opinions on this one

**Comment by asaj** [comment]
How many people have this problem?

**Comment by nambrot** [comment]
It was quite common in the hackathon scenario, but agree the jury is still out on more "production deploys"

**Comment by nambrot** [comment]
It's actually worse, since hyperlane-deploy right now makes assumptions that remotes already have mailboxes (for agent config), which results in an error during the deploy, and you have to just ignore the error and run again with the other chain being local (which is obviously a terrible experience)

**Comment by HariSeldon23** [comment]
Yup, we're definitely running into this issue. Not a deal breaker, but it can cause a lot of extra work. Especially when testing out multi chain scenarios on testnet where we want to boot up a fairly hardened environemnt

**Comment by nambrot** [comment]
This has been happening multiple times now, mostly at hackathons or for the india team who is doing multiple testnet deploys. It's also gotten worse since the set of contracts per chain has increased with ISM factories and a more complicated default ISM setup.
