### ISSUE TITLE
Contracts should be verified after PI/warp route deployment

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2145]
When deploying Hyperlane + Warp Routes via https://docs.hyperlane.xyz/docs/deploy/deploy-hyperlane and https://docs.hyperlane.xyz/docs/deploy/deploy-warp-route/deploy-a-warp-route, it is not clear or easy to verify those contracts. The scope of this ticket is to have contract verification easily done, ideally programmatically. However, even just a very clear guide on doing so manually with some flattened source code would work (though not clear if that is actually easier)

Infra has a [verify script](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/efad4e1326e964a1c3e6230474b85d53bbf977a2/typescript/infra/scripts/verify.ts#L15) that uses [ContractVerifier](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/6bac228efb27a179ad0fca1646f052a5adcf15d4/typescript/sdk/src/deploy/verify/ContractVerifier.ts#L33) to verify deployed contracts that could be useful in this context

**Comment by megabyte0x** [comment]
@nambrot I would like to work on this issue. 

I have deployed several chains and am familiar with the deployment scripts and other modules of the Hyperlane-SDK.

**Comment by nambrot** [comment]
just did this in #665
