### ISSUE TITLE
Feature: support AWS `WebIdentityProvider` credentials configuration

### ISSUE THREAD

**Issue by serejke** [hyperlane-xyz/hyperlane-monorepo#2168]
### Objective
Currently, the only way to configure AWS credentials for agents to access S3 and KMS is by passing env variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`. This is not the best security practice as the specified credentials never expire. 

The [recommended](https://aws.amazon.com/blogs/containers/diving-into-iam-roles-for-service-accounts/) approach for integrating AWS roles for EKS pods is to use IAM roles for `ServiceAccount` (IRSA). The IRSA webhook automatically sets up `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_ROLE_ARN` env variables on the pod, and mounts the web identity token file.

### What needs to be changed in code
Hyperlane uses [rusoto](https://github.com/rusoto/rusoto) SDK for AWS services, which, by the way, is in [maintenance](https://github.com/rusoto/rusoto/issues/1651) mode (consider migrating to the [official AWS SDK for Rust](https://aws.amazon.com/sdk-for-rust/) ?).

Rusoto has a `ProvideAwsCredentials` [trait](https://github.com/rusoto/rusoto/blob/34e929974a6f0925d9bd0c17c6901da0af5ecf85/rusoto/credential/src/lib.rs#L227-L226), which has several implementations. Currently, the [`EnvironmentProvider`](https://github.com/rusoto/rusoto/blob/c44e7709fba3af66f39e2508316ce5b1a29c23da/rusoto/credential/src/environment.rs#L54-L53) is used:

https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/1722f4ee7e38f292dfe39d7d522934b0b800b280/rust/hyperlane-base/src/settings/signers.rs#L112

https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/03d32f4009611ae4afd044c1e95a89d2676b7df0/rust/hyperlane-base/src/types/s3_storage.rs#L96

we can provide a configuration flag to use [WebIdentityProvider](https://github.com/rusoto/rusoto/blob/928fe4965e46a5a7c4bd307bdb29fba568965e43/rusoto/services/sts/src/custom/web_identity.rs#L109) instead.

### Suggestion:
`SignerConf.Aws`
https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/1722f4ee7e38f292dfe39d7d522934b0b800b280/rust/hyperlane-base/src/settings/signers.rs#L24

can be extended with a new `credentials_type: AwsCredentialsType` enum `AwsCredentialsType = EnvironmentVariables | WebIdentityFile` with the default value of `EnvironmentVariables`, and depending on the enum value, the `EnvironmentProvider` or `WebIdentityProvider` is created.

### Related discussion
This issue was first discovered by @Kuzirashi and mentioned in [Discord](https://discord.com/channels/935678348330434570/961710804011458621/1103051296933695649).

**Comment by tkporter** [comment]
related re: rusoto - probably makes sense to switch when ethers-rs does https://github.com/gakonst/ethers-rs/issues/2312

**Comment by yorhodes** [comment]
closed by https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2188
