### ISSUE TITLE
PR reviews can take a long time

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2172]
PR reviews are critical to any living code base. Sometimes it can be difficult to get reviews on time.

Possible solutions:
- Host a solution like https://github.com/change-metrics/monocle to get more insight into activites

**Comment by Tashuuuu** [comment]
I would like to work on this. Can you please explain it more?

**Comment by VasuK111** [comment]
I want to work on this. Can you please elaborate a little on it?
