### ISSUE TITLE
hyperlane-quickstart should be a good starting resource

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2174]
https://github.com/hyperlane-xyz/hyperlane-quickstart/ was intended as a starting point for developers who want to have a repo with pre-made contracts and scripts that can be simply used and extended to try out building with Hyperlane. It originally started during v1 and was late to get updated to v2. When it got updated, only the basic messaging example with hardhat got the update. Thus the scope for this ticket a significant subset of:

- [ ] Update npm dependencies to latest version
- [ ] Fix the Accounts API example for the hardhat unit test and task
- [ ] Fix the Queries API example for the hardhat unit test and task
- [ ] Fix the Messaging API example for the foundry unit test
- [ ] Fix the Accounts API example for the foundry unit test
- [ ] Add a Queries API example for the foundry unit test

**Comment by kamalbuilds** [comment]
Hi @nambrot can you please assign me this one , I would ensure to get this done ✅

**Comment by nambrot** [comment]
@kamalbuilds just want to confirm that you are stil working on this?

**Comment by kamalbuilds** [comment]
> @kamalbuilds just want to confirm that you are stil working on this?

Yes @nambrot I am still workin on this 🫡

**Comment by megabyte0x** [comment]
cool. All the best @kamalbuilds 🚀

**Comment by megabyte0x** [comment]
@nambrot is this still active? 

I would like to work on this if no one's working on it and its still a type of bounty.
