### ISSUE TITLE
Hyperlane Dune Dashboards

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2182]
We have a bounty ticket available for creating Dune dashboards for Hyperlane Activity Analytics. The goal is to help our clients visualize and analyze data and insights on the activity taking place on Hyperlane.

To claim the bounty, we're looking for developers who can create visually appealing Dune dashboards that showcase data on:

Total transactions processed on Hyperlane
Distribution of transaction volume across different chains and protocols
Breakdown of transaction types across different chains and protocols
Active accounts/contracts on Hyperlane
The dashboards should be customizable, allowing our clients to select the data and timeframes they want to view.

This bounty is an exciting opportunity to provide our clients with actionable intelligence on the activity taking place on Hyperlane. If you're interested in working on this bounty ticket, please let us know by commenting on this issue. Once the bounty is claimed, we'll provide further details on the project and requirements.

**Comment by vinhyenvodoi98** [comment]
i would like to start doing this issue:
- Total transactions processed on Hyperlane:
  - could describe more detail ?
  - like how many transaction to mailbox on each chain

**Comment by nambrot** [comment]
It would be about both messages that are dispatched on the origin chain, as well as messages that are processed on the destination chain. You'll likely need to correlate `DispatchId` and `ProcessId` events https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/55f40ad7602e616367b2483b5ce57eaf7db5420d/solidity/contracts/Mailbox.sol#L78

**Comment by vinhyenvodoi98** [comment]
Dashboard
https://dune.com/taionewgate/hyperlane

**Comment by yorhodes** [comment]
> It would be about both messages that are dispatched on the origin chain, as well as messages that are processed on the destination chain. You'll likely need to correlate `DispatchId` and `ProcessId` events

https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/solidity/contracts/interfaces/IMailbox.sol#L15-L44

**Comment by vinhyenvodoi98** [comment]
@yorhodes
i updated dashboard
i still don't understand i feel like number of event process and dispatch is the same

**Comment by nambrot** [comment]
Its dispatch on the origin and process on the destination

**Comment by vinhyenvodoi98** [comment]
how to mapping that ? is it base on dispatchId and processId

**Comment by vinhyenvodoi98** [comment]
@nambrot why don't we just count number of Dispatch even ?

**Comment by nambrot** [comment]
Because the dashboards are more useful to determine whether they actually got processed or not

**Comment by vinhyenvodoi98** [comment]
i updated dashboard 
please review it

**Comment by nambrot** [comment]
Making great progress!

The primary purpose of correlating Process and Dispatches, is to be able to say something like `Completion percentage of messages from Polygon to Celo`. Take for example, this message https://explorer.hyperlane.xyz/message/0x9f36e4a168c1e616ac3ce1090b583a5daa72cd757e098e6193f1873f5502a611. As you can see on the explorer https://polygonscan.com/tx/0xe0dc7c21a3dcdbbdea20f4a1f9f39ff15d244c48cd4d26d467c36045a5e64715#eventlog is the tx on Polygon that emitted the DispatchId event, and https://celoscan.io/tx/0xe243d14cf1710a65554f4dcaa89c059dad380191fe9f7d821e36e17d48dce553#eventlog on Celo for the ProcessId event

You should join those events so that you can make those kind of queries easily and more. It is important to be able to say `Messages from X have Y completion rate`, or even `Messages from Polygon to Celo take X seconds on average`. Once you join those events together, your dashboard becomes much more powerful.

**Comment by vinhyenvodoi98** [comment]
@nambrot 
Thanks for the suggestions. I have gained more experience in dune stats.
I have added some statistics but I find it a bit strange that there are transactions where the process even handles the dispatch

<img width="751" alt="Screen Shot 2023-05-31 at 18 12 31" src="https://github.com/hyperlane-xyz/hyperlane-monorepo/assets/33363513/fc9bec8c-911d-474f-8658-59de14980dec">


https://explorer.hyperlane.xyz/message/0x6537518a741db3e1ab01ae57f64192ce7e8668acaf1d9c00656ab76f1a0dbd5b

**Comment by vinhyenvodoi98** [comment]
i tried query a query . it's actually quite convenient
<img width="1490" alt="Screen Shot 2023-06-05 at 8 23 24" src="https://github.com/hyperlane-xyz/hyperlane-monorepo/assets/33363513/c86a3f41-18f2-41c6-b952-a202c46ec3a0">

**Comment by vinhyenvodoi98** [comment]
I updated it as a real number. it looks more reasonable
<img width="748" alt="Screen Shot 2023-06-06 at 14 27 02" src="https://github.com/hyperlane-xyz/hyperlane-monorepo/assets/33363513/211f2edf-20a6-4a83-ab14-e6d3ccf2dfd5">
