### ISSUE TITLE
Proxy Middleware for easy ICA remote calls

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2184]
We have a bounty ticket available for creating a general middleware service that enables the use of any dapp on a given chain with the ICA ([Hyperlane Accounts API](https://docs.hyperlane.xyz/docs/apis-and-sdks/accounts)) of a different account on a remote chain.

To claim the bounty, we're looking for developers who can create a middleware service that utilizes WalletConnect to act as a proxy between the dapp on the remote chain (which thinks the user is the ICA) and the actual account on the local chain. The middleware service should be able to translate requests for transaction signatures from the dapp into calls on the ICA router on the local chain. See https://twitter.com/nambrot/status/1466504723247284231 for prior art.

The demo should showcase the potential of these features to enhance the user experience of interacting with existing dapps on different chains from a single account (potentially even a DAO) on a single chain. 

This bounty is an exciting opportunity to drive innovation in the DeFi ecosystem and explore new possibilities for interoperability between different chains. If you're interested in working on this bounty ticket, please let us know by commenting on this issue. Once the bounty is claimed, we'll provide further details on the project and requirements.

**Comment by AlexBHarley** [comment]
I've made a pretty good attempt at claiming this bounty.

#### Quick links

- https://hyperlane-ica-demo-web.vercel.app/
- https://github.com/AlexBHarley/hyperlane-utils/tree/main/apps/ica-middleware

#### Overview

I've built a simple website that can turn any EOA wallet into a multi-chain ICA enabled wallet. It uses WalletConnect, sitting between dapps/wallets in the connection flow, and enriches the addresses of the EOA with all its ICA's.

It also demos gas payments from the origin chain, taking into account the gas overhead of whether the remote ICA has been deployed or not. 

All the other limitations I could think of with this approach are highlighted in the [readme](https://github.com/AlexBHarley/hyperlane-utils/tree/main/apps/ica-middleware).

**Comment by HariSeldon23** [comment]
Hey @AlexBHarley great work on this. Just busy playing around with this and was wondering if there was any way to get around some of the limitations mentioned by using Wallet Connect 2? 

As a demo, there's not much we can show people, would Wallet Connect 1 make it more useable?

**Comment by HariSeldon23** [comment]
This is really helpful. Appreciate it mate. 

When it comes to the limitations then, would we be able to use Warp in order to seed the accounts for those use cases where accounts need a balance? And then in terms of signatures (OpenSea, 1inch) for ToS, would account abstraction be a viable way around this limitation in the future?

**Comment by AlexBHarley** [comment]
@HariSeldon23 I believe warp routes are specifically designed to facilitate non-native token transfers across chains. The [Liquidity Layer](https://docs.hyperlane.xyz/docs/apis-and-sdks/token-bridge-api) (which currently supports ETH transfers across testnets via Portal) seems more like the correct Hyperlane specific thing to use here. But, as long as your origin account has the wrapped assets, I don't see why you couldn't just bridge assets normally and specify the ICA as the recipient.

Re. signatures, I'm not sure how AA ties in here but happy to think about it more. One solution could be if ICA's supported EIP-1271, somehow registering the owner during deployment, then dapps could check signatures originated from the owner. There'd still be UX barriers with undeployed ICAs of course but a new standard could be created and adopted by Ethereum tooling, whereby dapps check that the signature originated from the origin account. Although I think that seems out of scope for this bounty.

**Comment by yorhodes** [comment]
> @HariSeldon23 I believe warp routes are specifically designed to facilitate non-native token transfers across chains. 

[Warp routes also support native transfers](https://github.com/hyperlane-xyz/hyperlane-token#transfer-alices-amount-native-eth-from-ethereum-to-bob-on-polygon). Depending on liquidity, it may make sense to use warp routes though we will support additional bridges in the Liquidity Layer like [CCTP](https://www.circle.com/en/cross-chain-transfer-protocol).

> But, as long as your origin account has the wrapped assets, I don't see why you couldn't just bridge assets normally and specify the ICA as the recipient.

Generally agree with this sentiment. Using ICAs via Hyperlane should be composable with any assets.

> One solution could be if ICA's supported EIP-1271, somehow registering the owner during deployment, then dapps could check signatures originated from the owner.

We actually support ICAs with custom ISMs. An account abstraction ISM of some sort seems like a fantastic idea!
