### ISSUE TITLE
Explorer for Pi chains requires communication with the deployer

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2198]
Problem:
- To view messages/debug a message to a PI-chain, the user would need the artifacts from the Hyperlane deployment to get the relevant information. While most arguably would need to have gotten it from before, it still can be cumbersome to have to add it manually to the UI (the URL parameter feature helps a lot here though)

Possible Solution:
- Ideally, the explorer just works, and is able to be aware of all Hyperlane deployments and show relevant information without any setup. it could use directories like https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2178 for that

**Comment by jmrossy** [comment]
Closing this as done thanks for recent registry work
