### ISSUE TITLE
Warp Route NFT Support in the UI

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2201]
Warp Route contracts already support ERC721s, however the warp route [template UI](https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/) currently only supports ERC20's/native gas tokens.

Thus this issue is a about adding NFT support in the [template UI](https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/).

The scope is minimally as follows (but more is encouraged for a better judgement of submission):
- UI should be configurable with a NFT warp route
- UI should detect the NFTs owned by the wallet and show them as available for transfer on all chains
- UI should allow for triggering of the transfer

**Comment by vinhyenvodoi98** [comment]
@nambrot hi
I want to start doing this bounty. how can i start it, for example which channel to subscribe, who can i discuss,..

**Comment by nambrot** [comment]
Feel free to ask questions on this issue, or jump into the discord as well

**Comment by vinhyenvodoi98** [comment]
@nambrot 
<img width="815" alt="Screen Shot 2023-05-10 at 8 34 30" src="https://github.com/hyperlane-xyz/hyperlane-monorepo/assets/33363513/fb914511-5fef-4db1-8c21-ae2650f3bc0a">
This is my plan.

**Comment by HariSeldon23** [comment]
At Pangolin we built a set of open source components for DeFi called Honeycomb https://docs.honeycombsdk.com/honeycomb/

Within that we have an existing component for a Bridge
https://components.pangolin.exchange/?path=/story/defi-primitives-bridge-bridge--default

This particular component integrates with [Li.Fi](https://li.fi/), Axelar via [Squid](https://www.squidrouter.com/) and others.

It uses React and we use it for our entire site at [Pangolin](https://app.pangolin.exchange/)

It's built to be VM and chain agnostic. 

Currently supports EVM and pseudo EVM for Hedera. 

We're also hoping to extend it into either Flutter or else React Native components. 

MIT licensed so if you built the UI on Honeycomb anyone could use it anywhere. 

Here's the code https://github.com/pangolindex/components 
**Please note** eventually we'll move the repository to a Honeycomb org to distance itself from the Pangolin brand.

**Comment by jmrossy** [comment]
Done here https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/29/files
