### ISSUE TITLE
Streamline config shapes (typescript)

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2214]
As a result from https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1867, this ticket specifies the streamlining of our config shapes. 

Specifically, explorer config becomes the merge of the existing `ChainMetadata` (with slightly modified keys) and `HyperlaneDeploymentArtifacts` from https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2203/files#diff-0dda34e51b45fcb259676791b216443495e465f6ec7c372fc77ec9abe9b8409aR90, and can be easily generated during a Hyperlane deploy and easily shared, and eventually able to be communicated to registries a la https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2178 (instead of having to be manually constructed right now)

To do this, probably take the above draft PR, and make sure that it compiles in the sdk and adjust the consumers of ChainMetadata

**Comment by asaj** [comment]
@nambrot I think there are more contract addresses that would be good to share (e.g. ISM factories)

**Comment by nambrot** [comment]
Ahh good, point, any other ones? Feel free to add them to the PR, otherwise I can
