### ISSUE TITLE
Generic contract deployment middleware / Cross-chain create2 factory

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2232]
To deploy contracts on multiple chains today, developers need a funded EOA on all chain. For example the Router abstraction tooling as well as hyperlane-deploy itself require that as well. For applications building on top of Hyperlane, you could imagine a generic contract deployment middleware to be useful. Thus the scope of this issue is to create a simple Router application looking somewhat similar to this:

```solidity
interface GenericContractDeploymentMiddleware {
  function deployContract(uint32 destination, bytes bytecode, bytes32 salt)
  function deployContractAndInit(uint32 destination, bytes bytecode, bytes32 salt, bytes initCode)
}
```

On the sending side, it would just dispatch a message to the remote router whose handle basically just deploys a contract via a Create2Factory like [this one](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/4f01ee2c95f240e517fc577be348ee5812825059/solidity/core/contracts/Create2Factory.sol) (The create2 part of it is not strictly necessary, tho also follow https://github.com/foundry-rs/foundry/issues/2638.) It would probably be secured by a RoutingISM similar to interchain accounts to allow senders to specify the ISM to be used (which allows them to not have attackers squat the address it wants if using Create2)

This allows developers to just have a balance on one chain but deploy contracts on multiple chains.

**Comment by armanthepythonguy** [comment]
I would like to work on this. I have experience in this. I worked on something very similar in ScalingETH hackathon for my custom solution. Can you please assign me?

**Comment by nambrot** [comment]
Go for it!

**Comment by nambrot** [comment]
Probably blocked by https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2512

**Comment by nambrot** [comment]
Unblocked now

**Comment by lmcorbalan** [comment]
Hi @nambrot, I'm Lisandro from @BootNodeDev 
We've been researching about Hyperlane and we think this issue would be a good contribution so we would like to give this a try. 

- We see the issue is quite old, so do you think changes on Hyperlane since it was created may affect in some way the description?
- Do you see this as something added to this repo? If so, where would be the best place to add it?
- We would like to make this work with Create2 so we were thinking about adding something like [this](https://github.com/pcaversaccio/createx/blob/main/README.md#permissioned-deploy-protection-and-cross-chain-redeploy-protection) for preventing an address to be squat by attackers. WDYT? What about having chain redeploy protection also?

**Comment by nambrot** [comment]
Thanks @lmcorbalan for researching this one. I would say the bounty is still pretty applicable as it stands. It has become easier due to the lack of message limit now. 

You can also check out @destiner who has build this at Ethglobal london this year https://github.com/Destiner/hyperdeploy-contracts/blob/main/src/BytecodeRouter.sol

This work doesn't have to be added to this repo and is probably easier to do standalone. I would say that part of the bounty completion should be some basic script to deploy it on any Hyperlane chain (and allow contracts to be initiated from any other Hyperlane chain). For that, like we had mentioned on the description, we need a way to prevent squatting. IMO the easiest way to do that is to add the origin domain, the origin chain sender, as well as the ISM as part of the salt, the referenced solution imo sounds more complex than that

**Comment by lmcorbalan** [comment]
Hey @nambrot I already have the a dimple version of a router working, Could you please take a look at https://github.com/BootNodeDev/hyperlane-create2-factory-router/tree/feat/create2-factory and let me know what you think?

Once it is finished I'll be adding some scripts for deploying and using the router, also some more doc about how to use.

**Comment by nambrot** [comment]
Thanks for the update @lmcorbalan! On first look, it looks quite good, but I'm wondering if there is any way to have the key files in a PR somehow so that we can have PR comments on specific lines? I'm also wondering if you were able to test this remotely or the unit tests the main testing so far?

**Comment by lmcorbalan** [comment]
@nambrot There is a PR submitted where you could make you comments, this one https://github.com/BootNodeDev/hyperlane-create2-factory-router/pull/1

Regarding testing this remotely, I have deployed the routers on [Sepolia](https://sepolia.etherscan.io/address/0x2Ee69E78B5A4C7623e8a968c13Be7F463d4Ac166) and [Op Sepolia](https://sepolia-optimism.etherscan.io/address/0x7b4389980C4B0931B2f9846BE6122f41D0f1697a) and tested deploying a contract on Sepolia from Op Sepolia, here are the txs links
- https://sepolia-optimism.etherscan.io/tx/0x52c1c97dc5e6e5350e66b6f6cd50a15ddc61949b62ba6dd06f43549c1008a88f
- https://sepolia.etherscan.io/tx/0x807e4257406f5d56db4d86be9ebafdfa6769f83ffaf3610489cf459e1dd09635

And the deployed contract https://sepolia.etherscan.io/address/0xa546323EAA93eB4bA2484C3f789AA86A2260DFF0#code

**Comment by nambrot** [comment]
Thank you for your patience again, left 2 small comments on the PR (sorry for missing that the first time around)

**Comment by pablofullana** [comment]
hey @nambrot wondering if you have any feedback on the changes based on your feedback. thanks!

**Comment by nambrot** [comment]
I think that is, approved, and happy to close this bounty!
