### ISSUE TITLE
Unclear how to manually override gasLimit in Hyperlane-deploy

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2234]
Problem:
- For some chains, gas estimation does not work, which will lead to "gasLimit" errors. The typical work around is to manually override the gasLimit of transactions to a rather high value, which is very acceptable on testnet or cheap chains.

Possible Solution:
- Link to `chains.ts` and/or copy `ChainMetadata` to the docs and have the overrides be commented out but indicate which fields like gasLimit or gasPrice that they might care about

may be addressed in PR: https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2234

**Comment by asaj** [comment]
I like just commenting out overrides in chains.ts

**Comment by avious00** [comment]
may be addressed in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2952

**Comment by jmrossy** [comment]
It is indeed possible to fix this with the `transactionOverrides` property which users can now more easily set for core chains after #2952.
A bit of documentation would be good but otherwise calling this fixed
