### ISSUE TITLE
Make sending hyperlane-deploy messages one-way

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2238]
Problem:
- Sometimes folks want to test sending message just one way instead of all pairs of a network of `n` chains. That's because:
  - they are trying to debug one path that is not working and sending fully connected unnecessarily pollutes the logs + spends gas on the paths that already work
  - They may not actually support all pairs of chains

Solution:
- Make sending test-messages unidirectional and require users to specify the specific origin/destination of the message

Optional/Extra credit:
- Allow the user to specify the test message
- Recap what sending a message involves (Mailbox (Etherscan/Explorer) -> Validator -> Relayer -> Delivery (Etherscan/Explorer)) and what they should see (logs on the validator and relayer). Link to etherscan and explorer in the logs and docs where applicable

**Comment by asaj** [comment]
Please do not make it exclusively unidirectional. Instead, please allow origin and destination to be optionally specified

**Comment by yorhodes** [comment]
this is done in the new CLI
