### ISSUE TITLE
Sealevel agent: TxOutcome should support 64 byte tx ids

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2252]
On Solana, transaction IDs are 64 bytes (this is because tx IDs are actually the *signature* over a transaction!) instead of 32 bytes. `TxOutcome` at the moment expects the tx id to be 32 bytes. We can get away with hashing the 64 byte Solana tx id to be 32 bytes for the time being, but this sucks because now the original transaction ID can't get recovered. So we should move over to 64 byte transaction IDs (or at least when they're needed)

Update: a version was done, but due to other changes needs to be reworked now

**Comment by tkporter** [comment]
@asaj please make change to stop hashing the tx ID

**Comment by avious00** [comment]
@mattiecnvr spoke with @tkporter and if you have time this sprint to tackle, please do. it's lower prio so no worries if not.
