### ISSUE TITLE
Support proxy recipient contracts in debugger

### ISSUE THREAD

**Issue by jmrossy** [hyperlane-xyz/hyperlane-monorepo#2266]
https://discord.com/channels/935678348330434570/935678477246554132/1109669192472481822

Try lib https://github.com/gnosis/evm-proxy-detection

![image](https://github.com/hyperlane-xyz/hyperlane-monorepo/assets/710751/7bbb7839-c0d4-4bc3-b335-d85414824d84)

**Comment by avious00** [comment]
@jmrossy is this issue outdated now that we have v3?

**Comment by jmrossy** [comment]
> @jmrossy is this issue outdated now that we have v3?

I believe it still applies

**Comment by jmrossy** [comment]
Fixed by @Xaroz
