### ISSUE TITLE
Sealevel: create PDAs using a helper fn

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2267]
See https://github.com/solana-labs/solana-program-library/blob/master/associated-token-account/program/src/tools/account.rs#L18, we should use something like this

I read somewhere that `create_account` won't work if the PDA already has some lamports in it (which we should confirm, and is kinda ridiculous if so because it's not very well documented...)

If that's the case, we should make sure all PDA creation moves to a helper like this

**Comment by nambrot** [comment]
@tkporter Is this still open?

**Comment by tkporter** [comment]
done
