### ISSUE TITLE
Change block numbers throughout agent codebase to be u64 instead of u32

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2275]
Solana uses u64 for its block number, not u32. We should change this, and also consider that there may be u32 block numbers stored in DBs. Unsure what the best approach is for such a case.

Functions in particular are `get_finalized_block_number`, etc

Might make sense to make this change to the `trevor/sealevel-validator-rebase` branch to minimize merge conflicts - I've touched this a tiny bit

**Comment by asaj** [comment]
Sounds like maybe we can avoid doing this for now, since it will be a long time until u32 overflows

**Comment by tkporter** [comment]
See #2610 as well
