### ISSUE TITLE
Relayer should fail if it can't find the messages for a signed checkpoint

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#228]
Per https://github.com/bridge-buddies/optics-monorepo/pull/227, the relayer will wait for the messages with an expected leaf index to show up in the DB given a signed checkpoint. If the relayer or the node it is using for whatever reason are failing, this loop should eventually throw an error instead of being "stuck"

**Comment by mattiecnvr** [comment]
There may exist a situation in which an agent falsely assumes a message is in the database just because it saw a checkpoint with that message. Solution may be to go and fetch the message or at least prevent a deadlock.

**Comment by asaj** [comment]
I think this issue is a relic of a 1:1 mapping of checkpoints and messages? Closing
