### ISSUE TITLE
Sealevel infra plan & tooling to deploy solana-supporting agents

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2350]
We need the ability to load in Solana keys. These will only be `hexKeys` for the relayer - validator key can & should be configured the same way. Now with omniscient relayer, I believe the scaffolding for per-chain keys isn't there in `typescript/infra` anymore.. Maybe we need to introduce per-protocol keys or something?

We maybe want to do things in a separate context? Testing in RC is probably sufficient for now, but we should decide what our own infrastructure should look like for Solana / Nautilus - are we okay with using the `hyperlane` context?

Desired end state here is:
* the ability to run the `deploy-agents.ts` script and have it work with solana based chains
* Validators can be deployed that validate a sealevel chain
* Able to deploy a relayer that supports both sealevel and ethereum chains - i.e. the Ethereum signer may be an AWS KMS key, but the Sealevel signer would be a hexKey pulled from GCP secrets
* Decision on how we should run infra for Solana & Nautilus

**Comment by asaj** [comment]
Add the notion of chain type to chain metadata
Modify our infra to create/use hex keys for sealevel type chains. Presumably stored in GSM

**Comment by nambrot** [comment]
@tkporter @asaj is this ticket closed with #2402 or is there other work from this?

**Comment by nambrot** [comment]
Closing as we are on RC
