### ISSUE TITLE
Deploying helm charts should not probabilistically error out

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2380]
When deploying helm charts from `infra`, the following error happens quite frequently:

```
Error: open tmpcharts: no such file or directory
Error: Command failed: cd /Users/yorhodes/hyperlane/abacus-monorepo/typescript/infra/src/agents/../../../../rust/helm/hyperlane-agent/ && helm dependency build
Error: open tmpcharts: no such file or directory
````

This will mean that a specific release could not be deployed or updated. The workaround is usually to just run the command again.

I believe it has something to do with the fact that the helm upgrade probably involves check or upgrading dependencies and since deployments do that concurrently across chains.

**Comment by tkporter** [comment]
Are people still seeing this? @yorhodes

**Comment by nambrot** [comment]
Haven't seen this in a while, but also i haven't deployed in a while, cc @tkporter or @daniel-savu. If neither of you, lets close this @avious00

**Comment by daniel-savu** [comment]
I don't recall seeing this error
