### ISSUE TITLE
ICA remote ICA derivation seems incorrect

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2383]
The docs currently recommend the use of `getRemoteInterchainAccount` to calculate the remote ICA address for a given local account, assuming they will call `callRemote` without overriding either the remote router or ISM.

However, it seems like, said derivation is incorrect. For https://explorer.hyperlane.xyz/message/0x10d0295107d4b550e8aa22598fb1df19b545fd35e0cc5e07f21c12081bacef1f, the sender (`0x6feAC9505615345Ed214ab6eEaEAF2f953bfCc01 `) the ICA should be `0x0f38ba177b317869E9E6f310e0c16C335f6d4C5F` (remoteInterchainAccount), in fact it is`0x0e6208650ab3b75e937a8935f7e2553b27693c21`

**Comment by nambrot** [comment]
The issue is that ICA Routers are proxied, but the remote derivation relies on being able to derive the implementation address and thus bytecode hash of the `OwnableMulticall`. On the remote, we store the implementation address in bytecode after deploying `OwnableMulticall` in the implementation contract, however the proxy address is completely independent of that.

Thus the solution is to deploy the OwnableMulticall in an initializer and store the implementation address of the OwnableMulticall in the proxy's storage. That means that the origin router is able to derive the implementation address of OwnableMulticall from the ICA Router proxy address (which means that it is able to derive the bytecode + hash of OwnableMulticall on the destination router)

**Comment by yorhodes** [comment]
> Thus the solution is to deploy the OwnableMulticall in an initializer and store the implementation address of the OwnableMulticall in the proxy's storage. That means that the origin router is able to derive the implementation address of OwnableMulticall from the ICA Router proxy address (which means that it is able to derive the bytecode + hash of OwnableMulticall on the destination router)

Adding 2 cold SLOADs does seem heavier than necessary. I'm also worried about backwards compatibility. I think there is some more we can do with CREATE2. To be honest I'm not sure why we are relying on the CREATE1 derivation.
