### ISSUE TITLE
Allow Rust implementations of `MerkleTree` / `Proof` / `SparseMerkleTree` to use non-keccak256 hash functions

### ISSUE THREAD

**Issue by serejke** [hyperlane-xyz/hyperlane-monorepo#2388]
### Overview
For non-EVM chains integration it may be necessary to use a hash function other than `keccak256`. For instance, we're working on Cardano integration. Cardano does not have a native support of `keccak256`, and implementing it in a smart contract is computationally/gas unfeasible. We've opened a [CIP](https://github.com/cardano-foundation/CIPs/pull/524) for `keccak256` support, but it may take several months to a year to make into the Cardano mainnet. For now the only option is to use `blake2b` (256) for MerkleTree (on-chain and off-chain) on Cardano side.

### Description
This task is about refactoring the off-chain agents to make the hash-function customizable. For simplicity, the new hash function must return `H256`. Returning a different value would require a massive refactoring throughout the whole codebase. So hash functions with a bigger hash size will not be supported for now. 

https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/1fff74ebd8f54e6557b3a631f9538b9718eaffc2/rust/hyperlane-core/src/accumulator/mod.rs#L18

`hash_concat(left, right)` strictly depends on `Keccak256`.

### Suggestion
I see a couple of ways to resolving this:
#### Add a trait `HashFunction`
```
pub trait HashFunction {
    fn hash_concat(&self, left: impl AsRef<[u8]>, right: impl AsRef<[u8]>) -> H256;
}

pub struct Keccak256HashFunction;

impl HashFunction for Keccak256HashFunction {
    fn hash_concat(&self, left: impl AsRef<[u8]>, right: impl AsRef<[u8]>) -> H256 {
        H256::from_slice(Keccak256::new().chain(left).chain(right).finalize().as_slice())
    }
}

pub struct Blake2b256HashFunction;

impl HashFunction for Blake2b256HashFunction {
    fn hash_concat(&self, left: impl AsRef<[u8]>, right: impl AsRef<[u8]>) -> H256 {
        let mut hasher = Blake2b::new();        
        hasher.update(left);
        hasher.update(right);
        let result = hasher.finalize();
        H256::from_slice(result.as_slice())
    }
}
``` 

Then pass the `HashFunction` trait to the `hash_concat`.
- dynamically as `&dyn HashFunction` — then we need to store the object reference in all dependent `struct`s
- statically as `&HashFunction` — then all the dependent structs need to have a generic parameter and own the function

#### Using cargo feature flags
```
// accumulator/mod.rs

#[cfg(feature = "keccak256")]
pub use keccak256::hash_concat;

#[cfg(feature = "blake2b256")]
pub use blake2b256::hash_concat;

// accumulator/mod.rs Cargo.toml

[features]
default = ["keccak256"]

// Cargo.toml
[dependencies]
accumulator = { version = "*", features = ["blake2b256"] }
```

**Comment by nambrot** [comment]
Related to https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2258, I'll try to capture it more broadly as well

**Comment by nambrot** [comment]
Tried to capture it comprehensively at https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2399
