### ISSUE TITLE
Resolve sealevel Rust dependency conflicts

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2406]
The dependencies in the `rust/` workspace conflict with the dependencies required for our sealevel programs. As a workaround, the `rust/sealevel` dir is its own workspace. This unfortunately means there's a lot of duplication between `rust/` and `rust/sealevel` -- e.g. bits of hyperlane-core were copied into `rust/sealevel/hyperlane-core`. `rust/chains/hyperlane-sealevel/src/solana` is also an abysmal copypasta of the upstream Solana client / SDK, and within `rust/chains/hyperlane-sealevel/src/*.rs` there's a lot of ugly copy/pasting of types from the solana programs.

We want to:
1. Merge everything into the same workspace
2. Remove all the awful copypasting and use the actual dependencies everywhere

Happy to go into more detail on a call with whoever picks this up

**Comment by mattiecnvr** [comment]
Hi, yes, that would be me. I am going to spend some time playing with this, but I would appreciate having a call to get up to speed when you have a chance.

**Comment by tkporter** [comment]
## what's been done

For some history to build context:

1. The first pass at resolving this was https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2434, which initially went down the vendored dependency route. We then chatted and agreed we'd rather just deal with a fork. This PR is now stale. Building the `rust` crate with a standard build target worked just fine, but things broke when trying to `cargo build-sbf` the programs
2. I then built upon Mattie's work in (1) above where I created the forks instead of vendoring, and tried my best to deal with the sbf issues. I eventually got things to work by upgrading my local solana tooling to `v1.16.2` which uses cargo 1.69 (as does our monorepo), and restructuring some of the program crates. Interestingly for some reason when running `cargo build-sbf`, it'd also try building my dev dependencies, despite building them in release mode. So I went down this path of ripping out the functional tests in each of the programs so that there weren't any dev dependencies in the main programs. In other words, most programs (other than the mailbox, for another reason that's not too important) before had `my-program/src` and `my-program/tests`, where in `my-program/tests` there were some functional tests. These were moved to a separate crate `my-program-tests`.
Unfortunately after getting everything to build, I got hit with this sad runtime error when trying to send a transaction in my local end to end test saying that my transaction was ridiculously large. The fix is to just go back down to the stable 1.14.20 version, which.. does make sense https://solana.stackexchange.com/a/6849
At this point I started diving into which dependencies were prohibiting the programs from being built with 1.14.20, and it turned out that there were some deps in `hyperlane-core` (that programs like the Mailbox used extensively) that were causing issues. I spent a bit of time putting some up some cfg flags to remove bad dependencies, but didn't get too far. This is the path Mattie then went further down iiuc.
Here are the relevant links related to my efforts:
    - My branch, with a sad commit history https://github.com/hyperlane-xyz/hyperlane-monorepo/commits/trevor/dependency-attempts
    - `solana` fork: https://github.com/hyperlane-xyz/solana/tree/hyperlane
    - `solana-program-library` fork: https://github.com/hyperlane-xyz/solana-program-library/tree/hyperlane
    - `parity-common` fork: https://github.com/hyperlane-xyz/parity-common/tree/hyperlane
3. Then Mattie picked up from my above branch, and she shared https://github.com/hyperlane-xyz/hyperlane-monorepo/commits/mattie/sealevel/dependencies-part-2 . All programs build properly when you run `cargo build-sbf` in them! Recall you can run that command in one of the program dirs directly, or run the bash script with `build-only` to build all required programs.
She told me this before she signed off:
> Okay, checkout mattie/sealevel/dependencies-part-2. Main thing I ended up feature-flagging hyperlane core and spent a while working on getting the primitive types imported. There will probably still be some issues with building normally but they should be a lot easier to resolve. The sbf program builds seem to be working now. There's some really weird stuff happening because of their forked compiler trying to compile normal rust code and not always behaving as expected.

I did try to update it to the latest version and that is what I had spent most of yesterday on, that and just trying to understand the solana repo better. But that ended up being more difficult than expected.

## what needs to get done

We should build off Mattie's latest branch.

1. Take a look at her changes - it seems like we're moving toward having some of our "core" types that are used in non-chain-specific places (types like U256 / H256 etc) be defined in-house instead of via ethers or primitive-types
2. Get `cargo build` in the `rust` directory to work. It doesn't compile yet, not 100% sure why, but seems mostly from type changes to do with the changes mentioned above. Also make sure that `cargo build-sbf` for each of the programs still works!
3. Once everything compiles properly, make sure everything actually works by running the local end to end test (i.e. the bash script & running validator & relayer stuff)
5. Merge `trevor/sealevel-validator-rebase` - I can help with this if there are lots of conflicts. Shouldn't be tons, but definitely will be some because I merged main into `trevor/sealevel-validator-rebase` not super long ago
6. Take a pass through the changes when compared to `trevor/sealevel-validator-rebase` and clean things up. These are things that stand out to me that I know should be cleaned up - it's mostly undoing some garbage I was doing when I was trying to test things out
    a. remove these dependencies - I added these to play around and understand which dependencies were at fault for sbf building failing: https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/mattie/sealevel/dependencies-part-2/rust/sealevel/libraries/account-utils/Cargo.toml#L16-L41
    b. For `sealevel/programs/validator-announce`, `sealevel/programs/isms/multisig-ism-message-id`, and ``sealevel/programs/hyperlane-sealevel-token.*` (all 3 variants), undo the changes I did to rip the functional tests into a separate crate. They should more appropriately live back in `my_program/tests` if at all possible. I.e. undo the changes I made in these commits: https://github.com/hyperlane-xyz/hyperlane-monorepo/commit/8a9f5d97b1b5759c8f1dab86862c97fd9b5f7b70, https://github.com/hyperlane-xyz/hyperlane-monorepo/commit/4c7118568b4b2e5671d8302257be3ad4a3a3d8ba, https://github.com/hyperlane-xyz/hyperlane-monorepo/commit/0fa9bd06874d8d086ee9508c65814a9854de17b4, https://github.com/hyperlane-xyz/hyperlane-monorepo/commit/15a8e2ff7562eb3dbba57456b9f68e6f87da6415, https://github.com/hyperlane-xyz/hyperlane-monorepo/commit/2dcb6ff69336b64d473addf3020c12851265c89b
