### ISSUE TITLE
Fix agent release artifact pipeline

### ISSUE THREAD

**Issue by mattiecnvr** [hyperlane-xyz/hyperlane-monorepo#2413]
Seeing some errors in the linux builds. This needs to be fixed and then we should publish the artifacts to the latest release AND update the docs to suggest using these binaries over building from source.

**Comment by nambrot** [comment]
Let's hold off on updating to docs to dfault to binaries until we have actually tested that and found it to be superior to docker images

**Comment by avious00** [comment]
@nambrot should we revisit updating docs or how do we test binaries vs docker images errors?
