### ISSUE TITLE
!gasoracle is not a useful error message

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2438]
When using an IGP and trying to quote or pay for gas and using a domain that is not supported, the error message is `!gasoracle`. There should be a developer-friendlier revert message, something like "This IGP does not support domain x".

**Comment by RohanShrothrium** [comment]
Hi @nambrot!
New here, learnt about hyperlane through the recent eth global hackathon.

Currently `require()` statements do not support dynamic errors, does switching to custom revert messages help?
https://soliditylang.org/blog/2021/04/21/custom-errors/

Although, these are like events and will have to be decoded using signatures.
