### ISSUE TITLE
Token unit tests are slow

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#2439]
[Token unit tests use a `beforeEach`](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/fdc86f687c5a8a06ea9c9ab6c47e27455ef7765e/typescript/token/test/erc20.test.ts#L63) against hardhat which makes the unit tests far slower than they need to be. It should be possible to make this a `before` but there is some bug or shared reference which causes issues. I suspect it is related to typechain contracts mutating on `contract.connect(signer)` or something.

https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/5393901672/jobs/9794374526?pr=2433

**Comment by yorhodes** [comment]
Alternatively we can migrate the test suite to foundry @aroralanuk

**Comment by RohanShrothrium** [comment]
@yorhodes would be glad to take this up and migrate the token unit tests to foundry tests.

**Comment by nambrot** [comment]
I believe @aroralanuk already done it, so this can probably be closed?

**Comment by aroralanuk** [comment]
Funnily enough, they're slower now
