### ISSUE TITLE
Yield-earning Warp Routes with ERC4626

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2450]
### Context
Tokens that are held in Warp Route's `HypERC20Collateral` back the synthetic `HypERC20` tokens on the remote chains. A warp route deployer may want to create a warp route that puts these tokens to productive use. [ERC4626](https://ethereum.org/en/developers/docs/standards/tokens/erc-4626/) standard was created to allow yield-sources to easily be used without custom integration.

This bounty calls for a `HypERC20Collateral` variant that can deposit the underlying token into a 4626 vault (and withdraws it from the vault on unlock). When withdrawing, the user should get returned the original amount, with the yield accumulating in the warp route (which is tracked and withdrawable by the owner). The change itself should be pretty simple, so to complete this issue, you should also:

- Deploy a Demo of a DAI warp route that deposits the DAI into Savings DAI https://twitter.com/MakerDAO/status/1671220727322906624
- Deploy a demo of an ETH route that deposits the ETH into a 4626 wrapper around Lido https://github.com/superform-xyz/super-vaults/blob/main/src/lido/stETH_swap.sol

This is especially compelling as that allows let's say app-rollup/chain operators to monetize the deposits and capture value from a service they are providing. Obviously this is fundamentally already possible, but having ready to go contracts/products for this use case is key.

**Comment by vinhyenvodoi98** [comment]
i would like to do this issue

**Comment by vinhyenvodoi98** [comment]
so i need to create PR to this [Repo](https://github.com/hyperlane-xyz/hyperlane-token) and try to deploy by use [hyperlane-deploy](https://github.com/hyperlane-xyz/hyperlane-deploy), right ?

**Comment by nambrot** [comment]
We actually moved Warp Routes back to the monorepo, so you should make a PR to the monorepo and then yes use it in hyperlane-deploy (you will need to deploy your own NPM package for that during development)

**Comment by nambrot** [comment]
@vinhyenvodoi98 I would recommend reading up a bit more on the 4626 standard and how it works

**Comment by vinhyenvodoi98** [comment]
i have read it but i am having a bit of trouble demo it on testnet environment.
like I can manually deploy the sDai contract and then use it. However, if they have sDai on testnet environment, that's would be perfect
I'm also having trouble implementing on the hyperlane-monorepo repo. I guess I need more time to understand it

**Comment by nambrot** [comment]
You should be able to use any 4626 compatible token

**Comment by vinhyenvodoi98** [comment]
i want confirm about
```
/**
     * @dev Transfers `_amount` of `wrappedToken` from `msg.sender` to this contract.
     * @inheritdoc TokenRouter
     */
    function _transferFromSender(uint256 _amount)
        internal
        override
        returns (bytes memory)
    {
        wrappedToken.safeTransferFrom(msg.sender, address(this), _amount);
        return bytes(""); // no metadata
    }

    /**
     * @dev Transfers `_amount` of `wrappedToken` from this contract to `_recipient`.
     * @inheritdoc TokenRouter
     */
    function _transferTo(
        address _recipient,
        uint256 _amount,
        bytes calldata // no metadata
    ) internal override {
        wrappedToken.safeTransfer(_recipient, _amount);
    }
```
- _transferFromSender: will be used when user send token from A chain to B chain
- _transferTo:  will be used when user send token back from B chain to A chain

**Comment by vinhyenvodoi98** [comment]
for example 
- user send 10 ETH from eth -> polygon
- user's 10ETH will be 10stETH and store in HypERC20Collateral and have 10ETH in polygon
- after 3months 1stETH != 1 ETH. user want to send back 3ETH from polygon to eth 
  - should i use withdraw function in ERC4626 to withdraw exact 3ETH and send back to user
  - or redeem 3stETH and send back to user 3.03ETH ( assumption )

**Comment by nambrot** [comment]
It's more generic then that, depends a lot of what A and B chain is. In general, for a warp route, there is a single `HypERC20Collateral` contract which holds the token as collateral (i.e. collateralizes it by eventually calling `_transferFromSender` and releases the collateral from `_transferTo`.

Use sDAI for an easier example.

- User sends 10 DAI from ETH to polygon.
- warp route deposits the 10 DAI into sDAI (and lets say gets 100 sDAI shares)
- after 3 months, user sends money back, the user should ge back 10 DAI (and leave the 0.01 DAI that was earned in the meantime in the 4626 vault)
- owner should be able to move the interest elsewhere (but not move the collateral for all HypERC20 that is outstanding)

**Comment by AceVikings** [comment]
I would like to work on this issue

**Comment by vinhyenvodoi98** [comment]
@AceVikings 
sorry but i still working on this 🙇

**Comment by nambrot** [comment]
@vinhyenvodoi98 I would say you had quite a lot of time on this ticket, so I'll open it up to the public again. If you end up getting your work completed with the full-scope, you obviously remain eligible

**Comment by AceVikings** [comment]
Hey, could I be assigned this now ?

**Comment by avious00** [comment]
Hey @AceVikings feel free to attempt this, When you open up the PR, tag our CTO @ nambrot for a review

**Comment by avious00** [comment]
@rohanshrothrium and megabyte also asked, but Ace was first

**Comment by AceVikings** [comment]
> Hey @AceVikings feel free to attempt this, When you open up the PR, tag our CTO @ nambrot for a review

Got it, thanks!

**Comment by ltyu** [comment]
Hello, can I work on this?

**Comment by avious00** [comment]
hey lee @ltyu - go for it!

**Comment by avious00** [comment]
linking this to @ltyu's PR https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3076

**Comment by avious00** [comment]
linking https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3076
