### ISSUE TITLE
Deploy ICAs with derivation fix on testnet3/mainnet2

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2455]
Now that we have fixed derivation in #2383 , we should deploy it so that @AlexBHarley 's demo of #1838 works

**Comment by yorhodes** [comment]
https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2496/
https://github.com/hyperlane-xyz/docs/pull/44
