### ISSUE TITLE
Fix validator checkpoint index metric

### ISSUE THREAD

**Issue by mattiekat** [hyperlane-xyz/hyperlane-monorepo#2465]
Looks like this got removed from the codebase at some point. The metric itself still exists but nothing seems to be reporting it. Probably just need to plumb it through. Also worth asking if there is a reason why this metric was removed but after talking with @yorhodes it sounds like it was probably just an accident, though I am not sure when it happened.

Followup to hyperlane-xyz/issues#497

**Comment by mattiecnvr** [comment]
I am removing the alert from grafana at this point since we have not prioritized this and until we do it is just taking up space.

Query (A):
```
clamp_min(max by (chain) (hyperlane_latest_checkpoint{hyperlane_deployment="mainnet2", phase="validator_processed"} offset 30s) - on (chain) (label_replace(max by (origin) (hyperlane_last_known_message_nonce{hyperlane_deployment="mainnet2", phase="dispatch"}), "chain", "$1", "origin", "(.*)")), 0)
```

Reduce (B):
Input A
Function Last
Mode Strict

Math (C):
$B > 0

**Other properties:**
High Urgency
pending period 3m
Summary: This alert captures the difference between the validator signing a checkpoint and the relayer having index the message resulting in that checkpoint. It gives a 30s offset grace window. Any non-immediate reversion to 0 indicates that the relayer is having issues with indexing.

**Comment by mattiecnvr** [comment]
Also

Query (A):
```
clamp_min(max by (origin)(hyperlane_last_known_message_nonce{hyperlane_deployment="testnet3", phase="dispatch"} offset 5m) - max by (origin)(hyperlane_last_known_message_nonce{hyperlane_deployment="testnet3", phase="signed_offchain_checkpoint"}), 0)
```

Reduce (B):
Input A
Function Last
Mode Strict

Math (C):
$B > 1

Other properties:
Pending period 5m
Name: testnet3 unsigned checkpoints after 5m
Summary: It is taking more than 5m for checkpoints to be signed

**Comment by mattiecnvr** [comment]
Removing from the relayer dashboard:

Query:
```
clamp_max(max by(origin) (hyperlane_validator_checkpoint_index{app_kubernetes_io_component="relayer", origin=~"$origin", environment=~"$deployment"}) - min by(origin) (hyperlane_validator_checkpoint_index{app_kubernetes_io_component="relayer", origin=~"$origin", environment=~"$deployment"}), 3)
```
Name:
`Difference in Validator signed checkpoints`
Description:
`Compares the highest and lowest observed latest signed checkpoint from the validators`


Query:
```
clamp_min(max by (chain) (hyperlane_latest_checkpoint{hyperlane_deployment="mainnet2", hyperlane_context=~"hyperlane", phase="validator_processed", chain=~"$origin"} offset 1m) - on (chain) label_replace(max by (origin) (hyperlane_last_known_message_nonce{hyperlane_deployment="mainnet2", hyperlane_context=~"hyperlane",phase="dispatch"}), "chain", "$1", "origin", "(.*)"), 0)
```
Name:
`Relayer Message Nonce Lag`
Description:
`This metric captures the difference between the validator signing a checkpoint and the relayer having nonce the message resulting in that checkpoint. It gives a 1m offset grace window. Any non-immediate reversion to 0 indicates that the relayer is having issues with indexing`

**Comment by tkporter** [comment]
Seems we have `hyperlane_latest_checkpoint` on validators so gonna close this out
