### ISSUE TITLE
Default to 1/2 aggregation of MessageIdISM and MerkleProofISM in mainnet2

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2479]
Assess quorum of validators moving to DTM first

**Comment by nambrot** [comment]
Other thigns in the release besides aggregation ism support:
- no metadata ism support for optimism hook

**Comment by yorhodes** [comment]
this needs to update https://docs.hyperlane.xyz/docs/resources/security (which uses this https://github.com/hyperlane-xyz/docs/blob/main/sync-config.js to generate)

**Comment by avious00** [comment]
yorke will unblock on signing

**Comment by yorhodes** [comment]
> yorke will unblock on signing

I think this is done?

**Comment by avious00** [comment]
blocked on flattening source code

**Comment by avious00** [comment]
Cancelled
