### ISSUE TITLE
Review mitosis work

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2486]
Mitosis is finalizing their work on PRs like https://github.com/many-things/hyperlane-monorepo/pull/1/files and https://github.com/many-things/hyperlane-monorepo/pull/2. There should be a working e2e test. Also should take a look at the contracts again (since I don't think we ever did) to ensure things are up to spec. Might have to pull in @tkporter or @mattiecnvr for deep agent stuff

includes v3, kathy and others changes as part of remediation

after that we will send to osmosis and auditor

**Comment by avious00** [comment]
currently blocked by mitosis/osmosis bug - @nambrot to update status

**Comment by avious00** [comment]
from @yorhodes: e2e test not run in CI, reaching out to mitosis to repro their setup
