### ISSUE TITLE
Explorer should simulate with tenderly

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2488]
This was mentioned as a comment on https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1091, but the explorer can help devs by simulating the `handle` call to the message recipient and showing the trace which allows developers to understand why their message may not be processing.

https://docs.tenderly.co/simulations-and-forks/simulation-api should be used.

Requirements:
- If a message is not yet processed, there should be a link that a user can click (that can either be the existing calldata link or a link on the popup on which the calldata is displayed)
- upon click, call the tenderly api to create a simulation, and open a new tab with the UI result for it

**Comment by NOOMA-42** [comment]
@jmrossy Is the PR (https://github.com/hyperlane-xyz/hyperlane-explorer/pull/49) still ongoing? can I based on this PR and continue?

**Comment by nambrot** [comment]
Looks pretty stale, so you can probablty give it another try

**Comment by jmrossy** [comment]
@NOOMA-42 I agree with Nam, that PR is stale. You can use it as a reference but note it still has some unresolved comments to be addressed
