### ISSUE TITLE
Move implementation

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2489]
Aptos and Sui are two ecosystems which are two of the most prominent alt-L1s that were launched recently. They both are descendants of Facebook's Libra project which invented a new language called Move. This ticket is to capture the (rather large) scope of implementing Hyperlane in Move, as well as the relevant integrations into the agents. Since it is so much larger than the other bounties, we'd recommend to comment here and share maybe a spec to ensure everybody is on the same page

**Comment by carl339** [comment]
hi. aptos have consider more their community and ecosystem its more large that sui

**Comment by carl339** [comment]
community its to important
