### ISSUE TITLE
Sealevel: create helloworld program and deploy tooling for use by Kathy

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2502]
* Create a helloworld program (maybe we can choose to piggyback off `test-send-receiver`? though probably makes sense to have it be a distinct program)
* Write deploy tooling for the helloworld program. I think it probably makes sense to piggyback off the existing router logic that the warp route deployment logic uses -- it's not anything generic yet, but we can make it generic

**Comment by avious00** [comment]
PR Review by Rossy and Yorke here; https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2744
