### ISSUE TITLE
Index time to sync is incorrect for the backwards cursor

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2504]
https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2036 added the calculation of `estimated_time_to_sync` to indicate to operators how long it would take to fully index. When we changed indexing behavior in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2246, the different `MessageSyncCursors` seemingly did not update that calculation. I believe it still works for the forward cursor, but not the backward one. Thus it says `synced`, even though that is not the case. It should probably use the `from` field in the settings as the target, and calculate based on that

**Comment by nambrot** [comment]
fyi @asaj @mattiecnvr

**Comment by tkporter** [comment]
Gonna close in favor of https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3265
