### ISSUE TITLE
Sealevel: refactor IndexMode and IndexRange usage, support sequence-based RateLimitedContractSyncCursor indexing for future IGP indexing

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2511]
For context, before Sealevel we index events exclusively using block ranges. This is because the `eth_getLogs` RPC takes in a block range (`from` and `to`) and what event you're looking for, and it returns all events in that range.

With Sealevel (and Fuel, and probably other future alt exec envs), we don't have this luxury. Solana doesn't offer a great experience for event indexing out of the box. The solution we ended up going with is "sequence-based" indexing, meaning instead of the EVM version asking "give me all message dispatch events that occurred in the block range N and M", we ask "give me the message that was dispatched with nonce N, then give me message with nonce N + 1, etc". We can do this in Sealevel because entire message are actually written to on-chain storage, and are easily found by their nonce.

This change has already been made, but it was kinda shoehorned in in a not super elegant way.

Basically an enum to determine which indexing mode was created that's able to be set for a particular chain:
```
/// Indexing mode.
#[derive(Copy, Debug, Default, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub enum IndexMode {
    /// Block based indexing.
    #[default]
    Block,
    /// Sequence based indexing.
    Sequence,
}
```

And then the `IndexRange` enum is used by the indexing logic:
```
/// An indexing range.
#[derive(Debug, Clone)]
pub enum IndexRange {
    /// For block-based indexers
    BlockRange(RangeInclusive<u32>),
    /// For indexers that look for specific sequences, e.g. message nonces.
    SequenceRange(RangeInclusive<u32>),
}
```

But it's a bit ugly -- if you poke around `rust/hyperlane-base/src/contract_sync/cursor.rs`, you'll see that most of the logic is still very related to the old block-based indexing mode. You can also see in each impl of the Indexer trait (e.g. in `rust/chains/hyperlane-ethereum/src/mailbox.rs` here https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/trevor/sealevel-validator-rebase/rust/chains/hyperlane-ethereum/src/mailbox.rs#L134-L141) that there's this sketchy runtime check to do with IndexRanges being of the expected type.

Concretely, we want:
1. Rethink the general approach here - is there a decent way of structuring things such that at compile time via types we don't get in a situation where the Err in https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/trevor/sealevel-validator-rebase/rust/chains/hyperlane-ethereum/src/mailbox.rs#L134-L141 will ever get hit? Can we get rid of these ugly runtime checks?
2. The ForwardMessageSyncCursor and BackwardMessageSyncCursor and ForwardBackwardMessageSyncCursor already support sequence-based indexing, but `RateLimitedContractSyncCursor` does not. `RateLimitedContractSyncCursor` is used for indexing IGP payments or message deliveries in the scraper. We'll need to update `RateLimitedContractSyncCursor` to support sequence-based indexing

Note that https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2467 makes some small changes to indexing - we should merge this first, or work off that branch

**Comment by nambrot** [comment]
Not sure if this is too much out of left field, but wondering if https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2511 can be implemented as a sequence based indexer?

**Comment by tkporter** [comment]
I believe it can

**Comment by nambrot** [comment]
@tkporter can we add an estimate here? And I assume with Dan out, we should push this to the next sprint?
