### ISSUE TITLE
Sealevel: synthetic warp route should work with non-2022 SPL token

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2547]
Token 2022 (https://spl.solana.com/token-2022), which is the token type that is used for synthetic warp route tokens on Solana, is not audited atm. It's supposed to be frozen and audited "Fall 2023" according to https://spl.solana.com/token-2022/status, but unsure what the true status is of this

We should:
1. confirm if relevant stakeholders (e.g. Eclipse) are uncomfortable with 2022 tokens for warped tokens
2. if they are uncomfortable with it, we should make a code change to the Sealevel synthetic warp routes to work with the non-2022 version of SPL

**Comment by avious00** [comment]
@tkporter let us know if this makes the cut based on Eclipse's architecture path. following the tg chat

**Comment by tkporter** [comment]
For posterity, this is no longer necessary for the Eclipse / Nautilus stuff

**Comment by avious00** [comment]
@tkporter is this also the thing you recently flagged for me to find out about eclipse's upcoming mainnet launch?

**Comment by tkporter** [comment]
Looks like token 2022 is now fit for production and fully audited, so happy to consider this something we won't do https://spl.solana.com/token-2022#security-audits
