### ISSUE TITLE
Warp route UI should support multiple collateral / native chains for a given deployment

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2548]
Zebec wants their BSC token as collateral and their SPL token as collateral. The deploy tooling doesn't actually need changes to accommodate this because we have the notion of foreign deployments. However the UI should be able to accept multiple collateral chains for a warp route deployment

**Comment by avious00** [comment]
@tkporter i'm assuming this is blocked by the architecture decision that also impacts https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2547

**Comment by tkporter** [comment]
Separate from the architecture decision - it'll be required regardless of the outcome there. We're already planning on running the UI so this isn't pending a decision there either

**Comment by tkporter** [comment]
I previously chatted to @jmrossy about this and he estimated this would take a few hours to fix. Giving 1 day to be generous

**Comment by jmrossy** [comment]
Yes, in fact this is half done by this: https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/40
