### ISSUE TITLE
helm: Agents for multiple chains in one statefulset is not proper

### ISSUE THREAD

**Issue by josedev-union** [hyperlane-xyz/hyperlane-monorepo#2549]
We have utilized the Helm chart in this repository to deploy validators for four chains. The deployment creates a statefulset with the same number of replicas as the number of chains. 

However, if there are any changes made to the chain order in the configuration or if new chains are added or removed from the chain list, but not at the bottom, it can lead to a mismatch between the PVC index and replica index. This mismatch results in the failure of all agents.

How do you guys handle this?

**Comment by nambrot** [comment]
We do 4 helm charts for the 4 chains, and we'd recommend that as well

**Comment by josedev-union** [comment]
> We do 4 helm charts for the 4 chains, and we'd recommend that as well

yeah, i am considering this approach as the last resort.
If there is no other solution, it means that the support for multiple charts in one helm chart is not only meaningless but also problematic.
