### ISSUE TITLE
Annoying log when new SDK is used: "duplicate definition - NotCrossChainCall()"

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2554]
I suspect this is from the recent SDK release

Root cause possibly related to https://github.com/ethers-io/ethers.js/issues/905, unsure if we've fixed this. Just assuming this is related to ethers-js but not 100% certain

Manifests itself in some ugly ways:
* sync-addresses.js script adds it to our docs 🤮  <img width="555" alt="Screen Shot 2023-07-21 at 11 41 29 PM" src="https://github.com/hyperlane-xyz/hyperlane-monorepo/assets/20362969/f5e8ea30-1e6d-4789-8dc6-729cbf3e9a07">
* when running scripts in hyperlane-deploy (e.g. https://discord.com/channels/935678348330434570/1132054409984094378/1132080512731713607)

You can see it was added here too https://github.com/hyperlane-xyz/docs/commit/cc628f68c52a027bf81b46a629341d40eab3772c#diff-58b2440bee27d3a72f4b43486db3403961a80e8842c2faf869ef08b4092bc71cR1

**Comment by tkporter** [comment]
Per @aroralanuk

kunal — Today at 12:58 AM
duplicate definition - NotCrossChainCall() is coming from me copying over the openzeppelin's crosschainenabled contracts and defining the error NotCrossChainCall twice in different contracts but this  should be fixed on main 

tkporter — Today at 1:01 AM
ah i see
so we need an sdk release or something to fix this

**Comment by yorhodes** [comment]
fixed by https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2532
