### ISSUE TITLE
Bug in address filtering for building apps from artifacts

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#2561]
`filterAddressesMap` does not actually "filter out chains for which we do not have a complete set of addresses" https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/16146f0f03d0b0be67583cf16b22a3c50abdd977/typescript/sdk/src/contracts.ts#L69

More generally the factory and address coercion, multiprovider intersection, connecting contracts map, chainmap etc feels quite heavy and overcomplicated

This causes the IQS testnet fork tests to fail because there is no deployment on moonbasealpha
https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/5649869227/job/15305182868

**Comment by nambrot** [comment]
@aroralanuk said that he already did this
