### ISSUE TITLE
Idempotent expansion of PI deploys

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2575]
Currently, hyperlane-deploy deploys for a given new PI local chain and then stores the relevant artifacts of the local and remote in a `artifacts/addresses.json` field, which is also the source for testing or deploying warp routes. However, if a new chain gets deployed, the script will just deploy a lot of new contracts, instead of idempotently modify existing contracts like ISMs.

Related to https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2123

**Comment by jmrossy** [comment]
Will be fixed when hyp-deploy is replaced by CLI + registry + artifact management. CLI uses timestamped artifact files
