### ISSUE TITLE
Config/artifact problem for hyperlane deployments

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2579]
As folks have done Hyperlane deployments over the last couple months, one interesting problem that can be observed is that Hyperlane has this decentralized config and artifact problem. I.e. user `A` will deploy Hyperlane to chain `x` and have some artifacts `g` (contract addresses), and then some other user `B` may actually want/need to use `g` in their config to leverage/share the deployment (lets say to deploy a warp route or run a validator). 

I was trying to think of examples of other platforms or networks, where permissionless participants have this kind of mutual/shared surface area for config and artifacts and how they manage the storage, sharing and verification of them, but couldn't really come up with great parallels. I assume IBC is probably an example, but there must also be web2 equivalents? Things like helm charts or more generally package managers are somewhat similar in that they have a registry of artifacts that are versioned and can be referenced, but they also seen distinct in that they are not referencing instances or deployments which are stateful. This could be solved with something akin to https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2178 or #2440 

Even within a single user this problem can arise, related tickets are https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2575 and https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2123.

**Comment by nambrot** [comment]
Another possible parallel could be terraform plans and how they reference remote state

**Comment by yorhodes** [comment]
closing this in favor of registry
