### ISSUE TITLE
Minimal SDK support for sealevel

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2587]
(retroactively creating just to track work more explicitly following a convo with Avi)

As part of https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2503, we need to interact with Sealevel programs via Typescript in some way. We want to leverage the existing TS SDK because we already have some nice abstractions for working with apps. However the SDK is very EVM dependent atm. Rossy did a lot of legwork as a part of the Sealevel Warp Route UI task to build out some basic Sealevel abstractions that can be brought into the SDK.

See https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2503#issuecomment-1629755262 and other comments for details on how this played out

**Comment by jmrossy** [comment]
Thanks @tkporter 
There are two PRs open that take big steps towards this but there's still more to do:
https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2550
https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2529

**Comment by jmrossy** [comment]
Done
