### ISSUE TITLE
Sealevel audit: [L-2] - Enable runtime overflow checks

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2590]
Add the following to all program Cargo.tomls:
```
[profile.release]
overflow-checks = true
```

The Mailbox is specifically called out because of `inbox_process` having `inbox.processed_count += 1`, but we may as well add this in all programs. I assume adding it to a program's Cargo.toml means that all dependencies of it will also have overflow checks, but we should confirm

**Comment by daniel-savu** [comment]
> I assume adding it to a program's Cargo.toml means that all dependencies of it will also have overflow checks, but we should confirm

The profile config of a crate doesn't change based on the profile configs of the crates it imports if that's what you're asking. That's my read of the [docs](https://doc.rust-lang.org/book/ch14-01-release-profiles.html)
> Cargo has default settings for each of the profiles that apply when you haven't explicitly added any [profile.*] sections in the project’s Cargo.toml file. By adding [profile.*] sections for any profile you want to customize, you override any subset of the default settings.
