### ISSUE TITLE
Sealevel audit: [Informational - 2] - Duplicated signatures allowed

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2591]
> When loading signatures from caller-controlled arguments, it doesn't check if there are duplicated signatures.

> However, the signature quorum check is still safe, since validator_index moves once there is a hit, and there are no duplicated validators due to the check at processor.rs:372.
> It's still a good idea to reject duplicated signatures.

See PDF for code snippets. Maybe not a huge deal tbh, but we should think about it briefly

**Comment by nambrot** [comment]
@avious00 We should probably move these out of the sprint right?
