### ISSUE TITLE
Update relayers to process without historical indexing

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-monorepo#2596]
this reduces latency. subissue below specifically covers PI chain deployments

```[tasklist]
### Tasks
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2320
```
 
also see: https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2313

**Comment by tkporter** [comment]
Thoughts on just closing in favor of https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2313 ? This isn't a small task and requires more thought as it involves some structural changes to the agents to actually happen

**Comment by nambrot** [comment]
Needs https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2792 to be done
