### ISSUE TITLE
Update PI deploy in getting started docs to reflect CLI

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#2598]
Link: https://v3.hyperlane.xyz/docs/deploy-hyperlane

**Comment by nambrot** [comment]
Would move it out of this sprint in favor of https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2614

**Comment by jmrossy** [comment]
Note, docs changes already done for the Deploy core page: https://app.gitbook.com/o/Pl1c4GYUuMTxkQTcVCdO/s/STktvmwamt5GXWv1jqOM/~/changes/252/deploy/deploy-hyperlane

Not yet done for deploy warp page
