### ISSUE TITLE
Explorer UI: Show PI destination domain on the Explorer page

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-monorepo#2616]
Show the destination chain domain on the Explorer page even if it is not currently indexed.

Currently, the Explorer shows Unknown for community-run PI domains. This occurs both on the index list page and in the details page: <img width="945" alt="Screenshot 2023-08-07 at 1 43 09 PM" src="https://github.com/hyperlane-xyz/hyperlane-monorepo/assets/103125634/41a23f79-f589-4d4b-b042-ae97681a59e9"> 
<img width="326" alt="Screenshot 2023-08-07 at 1 39 23 PM" src="https://github.com/hyperlane-xyz/hyperlane-monorepo/assets/103125634/cfdc74fa-e6ed-47b7-9332-8e9c625cae67">

Our target is to add a mouseover to the question mark/Unknown on the list page with the domain number. e.g. this interaction from Etherscan:
<img width="366" alt="Screenshot 2023-08-07 at 1 44 21 PM" src="https://github.com/hyperlane-xyz/hyperlane-monorepo/assets/103125634/d6132d0d-f356-4487-bdbb-81351a9cd33e">

In addition, we are replacing the loading wheel with the following text in the box about the recipient:
Chain: Unknown (10012)

**Comment by jmrossy** [comment]
Done
