### ISSUE TITLE
Allow ETH to be donated to a HypNative contract

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2622]
The plan for bridging into Nautilus so that bridging gives a user the native Neon EVM token (i.e. ETH on that EVM) involves sending a bunch of ETH tokens to the HypNative contract without actually bridging the tokens. This ETH serves as a liquidity source for bridging *in* to that native warp route.

Atm, there is no fallback function on HypNative and the only payable function is `transferRemote` itself. We should add a function `function donate() external payable;` that anyone can call to donate funds to the HypNative contract

See https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2621 for what this looks like in the stopgap version - need to add tests etc

**Comment by avious00** [comment]
@tkporter is this ready to close?

**Comment by avious00** [comment]
@yorhodes any updates on this?

**Comment by yorhodes** [comment]
I have been trying to merge #2671 for a week
There is some unrelated CI flakiness
