### ISSUE TITLE
Better dependency caching for Rust builds

### ISSUE THREAD

**Issue by daniel-savu** [hyperlane-xyz/hyperlane-monorepo#2630]
Our current github actions for Rust use `Swatinem/rust-cache@v2`. The drawbacks are:
- Limited to 10gb of cache because we're not using external storage
- not great at caching dependencies between failed runs (currently completely disabled in our actions)
- does not reuse cached dependencies from other branches

[sccache](https://github.com/mozilla/sccache) is quite popular for Rust and does have a github [action](https://github.com/marketplace/actions/sccache-action).
- Setup is well documented and simple, based on people's opinions
- In terms of [storage](https://github.com/mozilla/sccache#storage-options) it looks like it can work with our pre-existing github action storage, but we were considering GCP since the integration is simple and would grant us more storage
- Caches rust "object files" which can be reused across branches (still have to confirm this)

The build step takes > 20 mins [currently](https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/5786448346/job/15681183234) (see the `run test` section, which mostly just builds dependencies). There's many small cases when cross checking with the pipeline can help debug not only the code but also the local environment, so it would be a great help to minimize the build step.

**Comment by mattiecnvr** [comment]
Relates to #1840

**Comment by daniel-savu** [comment]
Fixed by ser @paulbalaji in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4424 and other follow up PRs. #1840 is still a todo
