### ISSUE TITLE
Relayer not opening on my local opstack.

### ISSUE THREAD

**Issue by uok825** [hyperlane-xyz/hyperlane-monorepo#2645]
Hi, validator runs with no problem but relayer gives me error.
My validator command:`env $(cat validator.env | grep -v "#" | xargs) ./target/release/validator --checkpointSyncer.type localStorage --checkpointSyncer.path='/tmp/hyperlane-validator-signatures-ethereum' --originChainName anvil1 --chains.anvil1.connection.url http://127.0.0.1:8545/ --validator.key pkey --chains.anvil1.signer.key pkey --allowLocalCheckpointSyncers true`
My relayer command: `    env $(cat relayer.env | grep -v "#" | xargs) ./target/release/relayer --relayChains anvil1,optimismgoerli --chains.anvil1.connection.url http://127.0.0.1:8545/ --defaultSigner.key pkey --allowLocalCheckpointSyncers true --CONFIG_FILES ./agent_config.json --chains.anvil1.addresses.interchainGasPaymaster 0x968989eDFAB00952B5F38130Fe6178f82d54590e --chains.anvil1.addresses.validatorAnnounce 0xd2eAF0B140819cAeB90467407E433A190A8760F0 --chains.anvil1.addresses.mailbox 0x65698ef6229AF993c6aC2c2ec8e08dcFEa227952`
Validator screen: 
![image](https://github.com/hyperlane-xyz/hyperlane-monorepo/assets/30076213/e8c494fb-45f8-495a-a2d0-2219ccd88469)
Relayer error: 
![image](https://github.com/hyperlane-xyz/hyperlane-monorepo/assets/30076213/46fb646a-5e24-4c2f-8afa-e3a53b616a8f)

**Comment by avious00** [comment]
Merhaba @uok825 - I apologize for the long delay but wanted to check in if you're still having issues with this. We also just shipped a single-click validator & relayer experience that you can use without setting up your own relayer https://docs.hyperlane.xyz/docs/deploy-hyperlane#3-run-validators-and-relayers
