### ISSUE TITLE
Warp UI -> Explorer PI link broken

### ISSUE THREAD

**Issue by jmrossy** [hyperlane-xyz/hyperlane-monorepo#2651]
Likely due to inconsistencies in chainmetadata schema due to churn of the shapes there recently.

**Comment by jmrossy** [comment]
Note, this should be a quick fix but I'd like to do an SDK release first once the multi-protocol changes in my Kathy branch are merged. Semi-blocked until then

**Comment by avious00** [comment]
blocked by https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2652

**Comment by jmrossy** [comment]
> blocked by #2652

No it's this one: https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2559
