### ISSUE TITLE
Update warp UI to use multi-protocol utils/sdk

### ISSUE THREAD

**Issue by jmrossy** [hyperlane-xyz/hyperlane-monorepo#2652]
The Warp UI + utils/sdk packages have a bunch of duplicated logic that was added for sealevel kathy.
Migrate the warp UI to the new multi-protocol tooling

**Comment by avious00** [comment]
@jmrossy hey, does this issue still fit into this sprint? i see kunal has a related PR

**Comment by jmrossy** [comment]
> @jmrossy hey, does this issue still fit into this sprint? i see kunal has a related PR

Hey, no it won't fit because more high-pri work has been brought in instead and also this must wait until we publish a fresh set of utils+sdk packages, which is semi-blocked by https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2559/
