### ISSUE TITLE
Improve collateral to collateral warp UI support

### ISSUE THREAD

**Issue by jmrossy** [hyperlane-xyz/hyperlane-monorepo#2654]
The warp UI was built assuming routes would go from collateral/native contracts, through any number of synthetics, and then back to collateral/native.

There are issues with direct collateral/native -> collateral/native routes, especially when synthetics get mixed in too.

Relevant for Eclipse support

**Comment by avious00** [comment]
tagging @yorhodes @tkporter or @nambrot to review

**Comment by jmrossy** [comment]
Fixed in https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/51
