### ISSUE TITLE
bug(rust): CLI argument parser doesn't work for some configurations.

### ISSUE THREAD

**Issue by josedev-union** [hyperlane-xyz/hyperlane-monorepo#2662]
~The following configurations are not parsed from either env var or cli args.~
Configurations whose key includes multiple words are not parsed from CLI args correctly. Here are typical ones.(edited)

```sh
chains.<chain_name>.addresses.interchainGasPaymaster
chains.<chain_name>.addresses.validatorAnnounce
```
Btw, when I use a config file, it works.
Here is a discord link for more details https://discord.com/channels/935678348330434570/984123861144600587/1139906822510219284

**Comment by josedev-union** [comment]
I think i found the reason.
In the `CommandLineArguments`, the key is converted to lowercase but `RawCoreContractAddresses` uses `camelCase` serde. i.e. `RawCoreContractAddresses.interchain_gas_paymaster` is seralized to `interchainGasPaymaster` and vice versa.
On the other side, the cli argument `--chains.<chain_name>.addresses.interchainGasPaymaster` is parsed as `chains.<chain_name>.addresses.interchaingaspaymaster` and it doesn't match with the camelCased result.

https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/d88fd4cd16ebee06356c4b67e6c4ef381f33ff30/rust/hyperlane-base/src/settings/chains.rs#L89-L95
https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/d88fd4cd16ebee06356c4b67e6c4ef381f33ff30/rust/hyperlane-base/src/settings/loader/arguments.rs#L80

So this issue is not only affecting to `chains.x.addresses` but also all the other configurations which include multiple words in the key. For example, `chains.${CHAIN_NAME}.finalityBlocks`.

**Comment by josedev-union** [comment]
I can reproduce this issue with the following code snippet
```rs
use serde_json;


#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct TestHyperlaneArgParse {
    single: Option<String>,
    camel_case_upper: Option<String>,
    camel_case_lower: Option<String>,
    snake_case_upper: Option<String>,
    snake_case_lower: Option<String>,
}

fn main() {
    let json_data = r#"
        {
            "single": "single",
            "camelCaseUpper": "camel_case_upper",
            "camelcaselower": "camel_case_lower",
            "snake_Case_Upper": "snake_case_upper",
            "snake_case_lower": "snake_case_lower"
        }
    "#;

    let deserialized: Result<TestHyperlaneArgParse, serde_json::Error> = serde_json::from_str(json_data);
    match deserialized {
        Ok(data) => {
            println!("{:?}", data);
        },
        Err(err) => {
            println!("Error: {:?}", err);
        }
    }
}
```
Its output is
```sh
TestHyperlaneArgParse { single: Some("single"), camel_case_upper: Some("camel_case_upper"), camel_case_lower: None, snake_case_upper: None, snake_case_lower: None }

```

**Comment by mattiecnvr** [comment]
Can you elaborate on what "Not parsed correctly means". The argument parser was intentionally designed to lowercase the strings to be insensitive to either the literal `originchainname` or `originChainName` or `OriginChainName` and so on. The JSON config parser is more rigid as it has a better definition of what is expected, and the ENV parser is, well, env format unfortunately and that is why it is `SCREAMING_SNAKE_CASE`.

**Comment by mattiecnvr** [comment]
As a stop gap I recommend creating a config file using your helm chart. What we do internally is we ship the docker image with the chains config you see in the repo; this means our helm files don't need to generate the config file.

**Comment by mattiecnvr** [comment]
This bug might block the planned changes in #2215

**Comment by josedev-union** [comment]
> As a stop gap I recommend creating a config file using your helm chart. What we do internally is we ship the docker image with the chains config you see in the repo; this means our helm files don't need to generate the config file.

yeap, thanks for your suggestion
