### ISSUE TITLE
Quickstart Review

### ISSUE THREAD

**Issue by megabyte0x** [hyperlane-xyz/hyperlane-monorepo#2680]
This issue is regarding the Quickstarts of the [Queries API](https://docs.hyperlane.xyz/docs/build-with-hyperlane/quickstarts/queries#make-a-query)

The example listed there might be wrong in the current state of Arbriturm Fuji Testnet (`chainid: 43113`) as **it's not possible to get the `1 wei` as the amount of gas required for 20000 gas**
![Screenshot 2023-08-21 at 8 44 02 PM](https://github.com/hyperlane-xyz/hyperlane-monorepo/assets/79016290/e2ea5f29-8e36-420e-8c00-42be8ca22bb6)

It's suggested to use the latest example possible,  like this:
![Screenshot 2023-08-21 at 8 45 07 PM](https://github.com/hyperlane-xyz/hyperlane-monorepo/assets/79016290/4118cc0c-c524-40e5-9592-975568405de1)

> While applying the above changes make sure to change the complete example, including this screenshot:
![Screenshot 2023-08-21 at 8 46 51 PM](https://github.com/hyperlane-xyz/hyperlane-monorepo/assets/79016290/305f3b6b-88b7-4916-97a0-ca9d631d05f9)
> The correct one can be:
![Screenshot 2023-08-21 at 8 47 56 PM](https://github.com/hyperlane-xyz/hyperlane-monorepo/assets/79016290/1e5f7216-f6cd-48f3-9b02-9a70bcca11fb)

----
The above transaction link:
- [Mumbai Scan](https://mumbai.polygonscan.com/tx/0x5c4293db6dfdb7d963ff6ae2d2a7a6e29f5dbed6738dae190d386595df15e9ae)
- [Hyperlane Explorer](https://explorer.hyperlane.xyz/message/0x86e74ed752b004de56a4afae67134ff201f535d38b80f74bcef7ae508ee0a11b)

**Comment by nambrot** [comment]
@megabyte0x fixed on docs
