### ISSUE TITLE
Contexts should be able to specify their own IGP

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2693]
When we move to the Nautilus context and start enforcing gas payments for the nautilus deployment, we'll need the relayer to index a non-canonical IGP on BSC. This is because Nautilus was deployed as a PI chain, and the canonical IGP doesn't support paying for messages to it.

Concretely, we should have:
1. The optional ability to configure IGPs for specific chains in the `AgentConfig`
2. This is passed in and overrides the one found in the agent config jsons, probably as an env var
3. When we deploy an agent (specifically care about relayers) to the context, the configured IGP is used

_Before starting_: double check if captured by Mattie's context work @daniel-savu

**Comment by nambrot** [comment]
This is just via using the CONFIG_FILES option right? I.e. the override of 1. does not need to be specific to IGPs, IMO in infra we should just have CONFIG_FILES overrides per context, and that's how we can more generally move nautilus and zkEVM for yama out of the main rust/config files?

**Comment by avious00** [comment]
@tkporter should we pull into this sprint?

**Comment by avious00** [comment]
@tkporter friendly ping to see if this is resolved or blocked

**Comment by avious00** [comment]
@tkporter @nambrot is this still relevant for our solana v2 to v3 epic? IIRC we are just treating everything as part of the hyperlane context

**Comment by avious00** [comment]
closing this out @nambrot @tkporter since we are using everything under Hyperlane context
