### ISSUE TITLE
WarpRoutes should be able to be rate-limited

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2697]
ISMs by itself are not infallible and for Warp Routes that can be catastrophic. This bounty proposes a mechanism that allows Warp Routes to be configured to only allow certain rate for transfers to mint or release collateral. The way to implement this is via an ISM that can parse a warp route message and then check what the current flow allows for it. To complete this bounty, deploy the implementation on testnet and show that indeed withdrawals are rate-limited

**Comment by armanthepythonguy** [comment]
@nambrot I would like to work on this

**Comment by avious00** [comment]
hey @armanthepythonguy I'm going to let @RohanShrothrium also try this since it's been a while

**Comment by nambrot** [comment]
Relevant discord thread https://discord.com/channels/935678348330434570/1152248979736768552

**Comment by shaspitz** [comment]
Any updates here? This feature would be very useful to the Primev team, thank you

**Comment by nambrot** [comment]
@armanthepythonguy @RohanShrothrium any updates?

**Comment by avious00** [comment]
@yorhodes can you suggest an eng day estimate + ensure the description is good to go?

**Comment by yorhodes** [comment]
@ltyu and I discussed offline
we considered a warp route extension which implements this application-specific behavior, with the drawback being that we would need variants of collateral x rate limited, synthetic x rate limited, etc
we also considered a "middleware" approach that would be transparent to the warp route implementation itself
we decided on a hook and ISM pair of implementations (shared behavior) that rate limits inflow and outflow (to solve for the case of a user sending from a warp route that will not be deliverable for some time)
