### ISSUE TITLE
Update docs for new config names

### ISSUE THREAD

**Issue by mattiekat** [hyperlane-xyz/hyperlane-monorepo#2702]

**Comment by avious00** [comment]
hey @daniel-savu @tkporter did we do this?

**Comment by tkporter** [comment]
I believe so but I'll let @daniel-savu confirm - if none of us know for sure, we should prob confirm lol

**Comment by daniel-savu** [comment]
Yes we did in https://github.com/hyperlane-xyz/v3-docs/pull/29. I don't think we've had people reach out about this since then, so I'll close
