### ISSUE TITLE
De-dupe BigNumber related utils

### ISSUE THREAD

**Issue by jmrossy** [hyperlane-xyz/hyperlane-monorepo#2751]
We sometimes use ethers v5 BigNumber and other times use BigNumber.js (which is better). There's also an option to use neither and rely on native BigInt support.
See comment here: https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2744#discussion_r1333572083

**Requirements:**
1. All public facing interfaces / methods use `string` typed-numbers, because they're universal and agnostic to any particular library.
2. In implementations, we always use BigNumber.js to parse number strings and do arithmetic
3. Create utilities for converting between BigNumber.js and Ethers-v5-BigNumber
4. Use either strings or Ethers-v5-BigNumber when interacting with Ethers contract (as they won't accept BigNumber.js). Whichever is more convenient.

**Comment by ottbunn** [comment]
hi @jmrossy I'd like to take this one :))

**Comment by aroralanuk** [comment]
viem uses BigInt fyi @jmrossy

**Comment by avious00** [comment]
> hi @jmrossy I'd like to take this one :))

go for it!

**Comment by avious00** [comment]
> hi @jmrossy I'd like to take this one :))

@ottbunn go for it!

**Comment by jmrossy** [comment]
@aroralanuk That's true but BigInt, like Ethers BigNumber, does not support decimals and we need decimal handling for the utilities that handle user input.

**Comment by jmrossy** [comment]
@ottbunn If you don't mind waiting a few days, I can assemble info that will be helpful for you here. You can start by looking at the code in `typescript/utils/src`, that's where most changes will be needed I believe, but there will likely be other places in the SDK and possibly other packages 🙂

**Comment by ottbunn** [comment]
Hi @jmrossy, sure that would be great, I dont mind waiting a few days, thank you! :)

**Comment by jmrossy** [comment]
@ottbunn @aroralanuk I've added a set of requirements to the description above, lmk what you think.

In terms of how to approach this work, as I said above I'd recommend starting the `./typescript/utils/` code. Then once that's in good form, search of all uses of `BIgNumber` across the monorepo and update them to ensure they meet the requirements above.

**Comment by ottbunn** [comment]
hi @jmrossy thanks for the details 🙏🏻

having a question: wonder if we would still need `3. Create utilities for converting between BigNumber.js and Ethers-v5-BigNumber` is we use string to interact with Ethers contract in step 4.

**Comment by jmrossy** [comment]
@ottbunn We may not. Feel free to skip that requirement 3 if you don't think it's needed :)

**Comment by ottbunn** [comment]
hi @jmrossy @aroralanuk sorry for the late update, so for `bigToFixed` and `fixedToBig` in `./typescript/utils/src/big-numbers.ts` should I remain using the fixNumber from `ethers.js` or we're good to switch them out with `toFixed()` from BigNumber.js ([doc](https://mikemcl.github.io/bignumber.js/#toFix)). The functions are not used in the codebase, I was wondering what would be the usecase of these utils functions 👀

**Comment by ottbunn** [comment]
umm and would also like to ask how to test the utils (would like to run `big-numbers.test.ts`), there doesn't seem to have a command for testing in the `package.json` under the `utils` folder 🤔 thankss!!

**Comment by ottbunn** [comment]
included the changes in the draft pr, would be great to know if my understanding is matching the requirement, thank you!!

**Comment by jmrossy** [comment]
@ottbunn Checking your draft PR now.

For the to/from fixed utils, my first instinct would be to leave those as is for now. We won't be removing ethers v5 so we may still have certain cases where we need them.

And for the utils test, good catch! That's a mistake, the unit tests should be setup there similar to the SDK. Yes please do include that in your pr

**Comment by jmrossy** [comment]
@ottbunn Nice work so far! It's okay if you want to limit your changes to just the `utils` package, that's fine for now.

If you would like to update the SDK too, cases like this will need to be changed: https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/typescript/sdk/src/gas/HyperlaneIgp.ts#L59

Note, if you do want to update the SDK, you should wait for the v3 branch to merge to main. That will happen likely sometime this week.

**Comment by ottbunn** [comment]
I see, thanks!! I'll limit the changes to the utils package and mark the pr as ready for review for now then. Maybe could have separate pr for the SDK after the merge. (( excited for the v3 merge!!
