### ISSUE TITLE
E2E tests should include insertion scenarios

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2755]
- We can configure test1 to involve double insertion, test2 to involve single, and test3 to involve no merkle tree insertion

**Comment by tkporter** [comment]
2 days

**Comment by avious00** [comment]
also test heterogeneous insertions @tkporter @daniel-savu

**Comment by daniel-savu** [comment]
done in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2815
