### ISSUE TITLE
Migrate router tests from hardhat to forge

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#2757]
This is the last remaining hardhat unit test suite and we are not instrumenting coverage following https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2752

**Comment by ottbunn** [comment]
Hi 👋🏻 I'd like to work on this if the task is still available :)

**Comment by yorhodes** [comment]
> Hi 👋🏻 I'd like to work on this if the task is still available :)

Yes! I will assign you now

**Comment by ottbunn** [comment]
updated with the pr: https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2796

**Comment by avious00** [comment]
congrats @ottbunn on your first pr contribution!

**Comment by ottbunn** [comment]
cool!! thanks!!
