### ISSUE TITLE
Arbitrum/Orbit L2 => L1 Hook and ISM

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2846]
This ticket encapsulates a hook and ISM that allows a Hyperlane message to be transported via Arbitrum's `ArbSys` precompile contract on L2 to L1. See more under https://docs.arbitrum.io/for-devs/cross-chain-messsaging

You will want to use a [CCIP-read based ISM](https://docs.hyperlane.xyz/docs/protocol/ISM/ccip-read-ISM) to allow the fetching of the `OutboxProof` data from the virtual precompile of the Arbitrum chain that can then be passed by any Hyperlane relayer to process the message on L1.

Submission of this bounty should include a demo on a testnet or mainnet with tx hashes.

**Comment by exp7l** [comment]
is this available to be worked on?

**Comment by nambrot** [comment]
Also yes!

**Comment by shreyaspapi** [comment]
@nambrot is it still being worked on? Or would like to give it a try.

**Comment by nambrot** [comment]
Looks like no progress has been made, so I'd say you go for it

**Comment by avious00** [comment]
this is available for anyone to claim

**Comment by avious00** [comment]
@exp7l want to claim this after you finish L1?
