### ISSUE TITLE
LayerZero Hook and ISM

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2853]
This ticket encapsulates a hook and ISM that allows a Hyperlane message to be transported via LayerZero. You can find their docs here https://docs.layerzero.network/explore/layerzero-v2. The Hook would call the `Endpoint` with `send` and the ISM would inherit from [`ILayerZeroReceiver.sol`](https://layerzero.gitbook.io/docs/evm-guides/master/receive-messages) to receive the messageId. The Hook and ISM should be configurable to set a LayerZero Oracle and Relayers for custom secyrity configuration. The Endpoint requires payment, so you'll want to charge for that in the hook's `quoteDispatch` function by calling `estimateFees` 

Submission of this bounty should include a demo on a testnet or mainnet with tx hashes.

**Comment by ltyu** [comment]
@nambrot is this available to work on?

**Comment by avious00** [comment]
@ltyu lee, feel free to go for it. would recommend starting with the succinct one though! https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3092

**Comment by ltyu** [comment]
> @ltyu lee, feel free to go for it. would recommend starting with the succinct one though! #3092

I’m not familiar with Succinct. Is it related to L0? Any docs for Succinct?

**Comment by ltyu** [comment]
> @ltyu lee, feel free to go for it. would recommend starting with the succinct one though! #3092

I think i'll tackle this one as i'm a bit more familiar with L0, unless theres a priority for Succinct. Lmk!

**Comment by avious00** [comment]
@ltyu sure thing, give this a go!

**Comment by avious00** [comment]
linking https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3102
