### ISSUE TITLE
TIA Bridging Leaderboard

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-monorepo#2891]
We recently shipped [usenexus.org](usenexus.org) to bring TIA from Neutron to Celestia rollups. Next, we are launching a Neutron to ARB warp route and we're looking to create a leaderboard for the following:

- Top bridgers by volume
- Top traders by volume
- Top LPs

This is a medium size bounty.

**Comment by vinhyenvodoi98** [comment]
@avious00 
i submit mu Dune dashboard for hyperlane X tia in arbitrum
https://dune.com/taionewgate/hyperlane-x-tia
Please give me feedback about it

**Comment by aiguru2023** [comment]
Can anyone participate?

**Comment by Sayan7388** [comment]
I wanna participate 🫡💕

**Comment by brambodinero** [comment]
Good idea, im in

**Comment by xieziu86** [comment]
thats so hard forme

**Comment by n4n0banano** [comment]
lfg

**Comment by kristie-dude** [comment]
Was this done? Curious to see the leaderboard

**Comment by avious00** [comment]
Hi @kristie-dude this bounty was completed. You can find the winning submission here: https://dune.com/0xduneanon/tian-activity-on-arbitrum

**Comment by 123boko** [comment]
thank you
