### ISSUE TITLE
Figure out parallel/concurrent tx signing/races

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#291]
In the current form of the relayer, there are two processes:
1) CheckpointRelayer, whose primary objective is to relay checkpoints, but also "optimistically" process messages that occur from the resulting checkpoint tx submission. It is assumed that most messages would be processed in this manner.
2) MessageProcessor, whose primary objective is to process messages that 1) did not. That could be either because the relayer was down, or because the checkpoint reorg'd, or any other failure reason.

There are the following issues:
- Tx submission happens completely serially today. Not only causes this unneccessary processing latency in 1), but also could possibly delay checkpoint relaying if the message batch is large.
- Both processes currently run in the context of a single agent and thus single signer per inbox. This can cause 1) general nonce collisions (even without parallel tx signing), but also the simultaneous processing of a message even if concurrent tx signing would have been figured out.

**Comment by nambrot** [comment]
My solution will be to just wait for Mattie to come onboard and fix this with the obvious rust way of doing this

**Comment by nambrot** [comment]
@Eadword You are on board now :)

**Comment by webbhorn** [comment]
Just noting for posterity that it looks like `rust/run-locally.sh` reliably reproduces the nonce race hypothesized in comment#1 after enough rounds, if run with the fixes introduced in #480 and #482.

See for example example run [here](https://gist.github.com/webbhorn/a36459bea32fffb8abca2a7705b4c33f) (`VM Exception while processing transaction: reverted with reason string 'block hash is odd' ... Nonce too low. Expected nonce to be 39 but got 36`).

**Comment by nambrot** [comment]
I believe this no longer applies, so closing cc @tkporter
