### ISSUE TITLE
Relayer tx issues 

### ISSUE THREAD

**Issue by shaspitz** [hyperlane-xyz/hyperlane-monorepo#2924]
Hello, we're running a [testnet](https://github.com/primevprotocol/geth-poa) with a hyperlane bridge from Goerli to a POA sidechain, and our relayer is periodically getting stuck with [this error](https://ethereum.stackexchange.com/questions/27256/error-replacement-transaction-underpriced). 

Log here
```
WARN relayer::msg::pending_message: Error when processing message, error: ContractError(MiddlewareError(MiddlewareError(MiddlewareError(JsonRpcClientError(JsonRpcClientError(JsonRpcError(JsonRpcError { code: -32000, message: "replacement transaction underpriced", data: None })))))))
```

Note when the relayer hits this error, it's not able to submit transactions and hence does not relay messages. Are there any gas config values I can change to prevent this? Thanks

**Comment by shaspitz** [comment]
I've also tried stopping just the relayer container, wiping it's db volume, and restarting. This does not seem to fix the issue, as it doesn't reset the goerli state that's causing the hangup

**Comment by shaspitz** [comment]
Changing the signer account fixed the issue, but obvi this would not be desirable in production

**Comment by nambrot** [comment]
Closing this in favor of https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2959, very much agreed that this is important for reliability
