### ISSUE TITLE
Investigate spawned metric tasks in agents

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#3047]
It seems likely that we're spawning a lot of metric tasks in the agents, as it's part of the `build_ethereum` step. We not only do this ~15 times at startup in the relayer, but also when building metadata!

@daniel-savu pointed out tokio metrics we can start using that will also reveal this to us: https://tokio.rs/blog/2022-02-announcing-tokio-metrics

If we're actually continuing to spawn a task / multiple tasks whenever we build metadata, we'll need to refactor this or somehow enforce there's only a single task per chain

**Comment by avious00** [comment]
@aroralanuk @tkporter - thinking of assigning this to Kunal since it's adjacent to the eigenlayer work he's been doing it lately. does that work?

**Comment by daniel-savu** [comment]
It's not that adjacent imo, more about tokio than about prometheus
