### ISSUE TITLE
Functional config generation in Infra

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#3064]
## Problem

Infra has a lot of useful tooling for generating verbose config from simple static config. Unfortunately, the logic here is "closed" over constants that are not in a single place and are hard to reconfigure in infra without breaking everything. I experienced this when attempting to configure an ISM other than the existing aggregation of "default" multisigs. 

For example, the mainnet3 IGP is "closed" over owners, default multisig ISM config, key funder, oraclekey, etc
https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/69d87c90c0ab824c21e37bddfb27c9e4dd8b22c4/typescript/infra/config/environments/mainnet3/igp.ts#L30

Instead, this should be purely functional

## Solution

- [ ] Refactor these functions to be purely functional
- [ ] Pull these functions into the SDK for use in the CLI

## Nice to have

Expose these functions in the CLI interactively somehow

**Comment by avious00** [comment]
@yorhodes confirming this issue is covered in Kunal's PR?

**Comment by yorhodes** [comment]
> @yorhodes confirming this issue is covered in Kunal's PR?

@aroralanuk 's PR does cover the mentioned example but that is the tip of the iceberg
this is more like a multiday epic

**Comment by avious00** [comment]
@yorhodes please break this down further

**Comment by avious00** [comment]
@yorhodes to scope this down and close
