### ISSUE TITLE
Retry messages in the relayer queue via on demand API

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#3098]
If there's downtime or a chain has gone down etc, we should be able to easily tell the relayer to retry delivering all or some messages. 

Plan:
- Building upon Kunal's work in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3095, we'll create a new API path for the relayer (maybe `/relayer/`?) where we will have multiple endpoints
- one endpoint will allow us to request that the relayer retries a message or messages that match certain criteria
- The endpoint will take in either:
  - a message ID of a specific message (maybe allow for multiple? dunno)
  - a matching list, so we can match multiple messages easily (covering the case of retrying all messages to a chain or recipient etc)
- The endpoint's code will:
  - have a channel that it will use to send an action to serial submitters tasks (note we have one set of submitter tasks per destination chain - we'll probably need a channel that broadcasts from the endpoint logic to all of the destinations, e.g. in the case of a matching list that would match multiple dest chains, or a message ID where it's unknown what the dest chain is, etc)
  - when a serial submitter task receives an action on this channel, it should find any matching messages and place them at the front of the OpQueue. We may need to move away from a BinaryHeap to a BTreeMap for efficient ordering & lookup. We may also want to reset the # of retries for the message, though I don't feel strongly there

[architecture discord discussion](https://discord.com/channels/935678348330434570/1202202064864935957/1203041613157236836)

**Comment by nambrot** [comment]
Wdyt of doing this as part of https://github.com/hyperlane-xyz/issues/issues/868

Make some simple way to query messages and their retry stats but then also reset or adjust them via the relayer API

**Comment by tkporter** [comment]
Yeah it'd make sense to put it in there

**Comment by tkporter** [comment]
We should decide whether this should be an HTTP API (which requires plumbing thoughout the agent codebase), or if this should be a separate command you run against a local hyperlane DB (which would involve some code that is external to the relayer, like a CLI)

**Comment by nambrot** [comment]
Also thinking if explorer support is proximate enough to be an alternative

**Comment by nambrot** [comment]
Happy for @tkporter to decide what the best trade off to go with is

**Comment by daniel-savu** [comment]
> We should decide whether this should be an HTTP API #868 (which requires plumbing thoughout the agent codebase)

Ideally that plumbing is done by Kunal's work in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3095, which I'll review today

**Comment by avious00** [comment]
from @yorhodes offline
- potential solution is reusing IGP top up semantics to upsert message IDs from existing position to front of queue

**Comment by yorhodes** [comment]
this would have been useful testing the injective <> inEVM warp route

**Comment by avious00** [comment]
@tkporter to start a discord thread to build consensus
