### ISSUE TITLE
mantapacific scraper support

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#3123]
## Problem

**Is your feature request related to a problem? Please describe.**

**Additional context**

## Solution

**Describe the solution you'd like**

**Describe alternatives you've considered**

## Nice to Have

**Describe non-essential extensions to the solution**
Additional features which should be implemented if they are easy to accommodate but otherwise can be skipped

**Comment by avious00** [comment]
@tkporter confirming we have manta but not viction or ancient8 support - should we close out this ticket then?
