### ISSUE TITLE
Derive `HookConfig` from `IPostDispatchHook` address

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#3129]
## Problem

From a `IPostDispatchHook` address, we should be able to derive the [`HookConfig`](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/0727a6178eaea332788a30cc2871a8865b28c34c/typescript/sdk/src/hook/types.ts#L61) that this contract reflects from  onchain.

## Solution

- Recursive derivation function from a hook address

```typescript
function deriveConfig(address hook): Promise<HookConfig>;
```

- Should include modular derivation functions for children:

```typescript
function deriveIgpConfig(address igpHook): Promise<IgpConfig>;
```

This represents the Read operation of Hook CRUD management

The CLI command for this is tracked separately in https://github.com/hyperlane-xyz/issues/issues/1183

**Comment by avious00** [comment]
@yorhodes @nambrot is this other issue related? https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2797 can we collapse them

**Comment by avious00** [comment]
@yorhodes to refresh this ticket
