### ISSUE TITLE
Deployer config duplication

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#3135]
## Problem

- Deployer config schemas are duplicated across the CLI (as Zod) and the SDK (as types)

## Solution

- Pull the zod schemas into the SDK
- Use the schema derived types in the SDK
- Import the schemas from the SDK into the CLI

```[tasklist]
### Tasks
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3188
```

**Comment by avious00** [comment]
to be done by either Paul or Kunal, with Yorke's guidance

**Comment by avious00** [comment]
@paulbalaji fyi @aroralanuk is going to do the warp route de-duping, the rest of the config shapes is up to you. definitely sync with Yorke before you dive in!

**Comment by avious00** [comment]
@aroralanuk please share context on handoff for paul also mention yorke's nested pr
