### ISSUE TITLE
Cosmwasm contract addresses w/ lengths other than 32 bytes should be supported

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#3143]
## Problem

Neutron cosmwasm contract addresses are 32 bytes. Injective ones are 20. The agent implementation uses H256s for contract addresses that are taken in via config, and therefore always creates a 32 byte `CosmosAddress`. When this is serialized in bech32, we get 32 byte addresses prefixed with 12 0 bytes, when we really need them serialized shorter

## Solution

- Should we allow / require protocol-specific addresses in config files? Atm we need to convert bech32 -> hex and then put it into the config JSONs. Same for Solana, we need to convert base58 -> hex. Maybe taking in bech32 in the config will let us support arbitrary length cosmos contract addresses?
- Other ideas could be to read them in as vec<u8> or something but still require hex? Or maybe to configure the length for contract addresses? but these feel a bit worse tbh

**Comment by avious00** [comment]
@tkporter is this is in review?
