### ISSUE TITLE
Agent indexing may miss logs

### ISSUE THREAD

**Issue by daniel-savu** [hyperlane-xyz/hyperlane-monorepo#3171]
## Problem
There are cases when a querying a node at the latest block returns no logs, in spite of a message being dispatched at that block. This is probably due to a race condition caused by the node not being fully synced according to @tkporter. Due to that, indexing may miss a message and cause it to not be delivered, at least until a new message _is_ detected and triggers the logic [here](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/234982486fc490a13935f333c4cc4fe5361e5257/rust/hyperlane-base/src/contract_sync/cursor.rs#L149).

## Solution
There could be better solution and part of this task is to find one. A possible solution is to use the latest sequence, read each time indexing runs (e.g. [here](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/234982486fc490a13935f333c4cc4fe5361e5257/rust/hyperlane-base/src/contract_sync/cursor.rs#L226)), to check whether there is a processed message in the local [db](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/234982486fc490a13935f333c4cc4fe5361e5257/rust/hyperlane-base/src/db/rocks/hyperlane_db.rs#L101) for it. This should happen regardless of whether `self.cursor.sync_state.next_sequence` is equal to `mailbox_count`. If there's no message in the db, some of the logic  [here](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/234982486fc490a13935f333c4cc4fe5361e5257/rust/hyperlane-base/src/contract_sync/cursor.rs#L149) should be run.

## Alternative Solution

For now, this issue can be fixed by just restarting the agent

**Comment by tkporter** [comment]
I think this should be fixed by #3262, so gonna close
