### ISSUE TITLE
Prune agent artifacts to only contain relevant chains

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-monorepo#3189]
### Problem
As a PI deployer, i want my artifacts to include just the chains I have deployed to instead of all of them. When all of the chains are included, the agent config becomes too large to generate a Kurtosis URL.  

### Solution
Likely a small change to https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/dcf8b800a9a4c06b140efc3092b72bf995f1452a/typescript/cli/src/deploy/core.ts#L466

**Comment by paulbalaji** [comment]
Can confirm this fixed the issue with URLs being too long when trying to deploy kurtosis agents via CLI
