### ISSUE TITLE
Update checker/governor to handle proxied ICA safe calls

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-monorepo#3199]
- maintain fork tests coverage for current v3 deployments
   - ICA proxied state submission, run the checker again chainB, with the additional knowledge the governor sees the violation, pass ICA call on chainA
- enqueuing calls from all the destination chain to the hub chain
- add union type LOCAL(address or REMOTE(ICA object) violation in governor
- determine the origin router and insert ICA proxied calls into the governor

**Comment by yorhodes** [comment]
I think we should support configuring an owner as an ICA in the deployer

## governor changes
from the config or from detecting from the owner address, we know the owner is an ICA
1. get the ICA router from the ICA
2. lookup the owner of the ICA on the router
3. check if thats a safe?
4. wrap the call (on local) with an ICA router call (on origin)
abi encode callremote(local, ...call, 0)
