### ISSUE TITLE
Spec out an agent indexing refactor epic

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#3224]
## Problem

We're ripe for an indexing refactor / new plan. This tracks creating a new epic around indexing in the agents

## Solution

**[Notion document](https://www.notion.so/hyperlanexyz/Indexing-Refactor-7220f23de5fd4592beb30af801b6f61a?pvs=4)**

See all issues https://github.com/hyperlane-xyz/hyperlane-monorepo/issues?q=is%3Aissue+is%3Aopen+indexing, need to sift through and decide which are important & plan out what we should do to address them
```[tasklist]
### Related Tasks
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3224
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3213
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3264
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3267
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3265
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3266
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3268
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3269
```

related: https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2313

**Comment by avious00** [comment]
@tkporter would say this has been the main agent indexing epic to date https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2313 it's on the list of open issues you have

**Comment by tkporter** [comment]
@avious00 https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2313 is definitely related. I'm happy to have that be the main indexing epic - it's pretty stale imo and doesn't mention a bunch of new experiences / ideas we've had with indexing, so we'll need some time to update that epic more thoughtfully

**Comment by tkporter** [comment]
notion https://www.notion.so/hyperlanexyz/Indexing-Refactor-7220f23de5fd4592beb30af801b6f61a
