### ISSUE TITLE
Refactor watermark-based / rate limited indexing

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#3264]
Similar refactor to https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3262, but now for watermark-based / rate limited indexing

When indexing data types that are not always sequenced (like IGP payments and message deliveries), we use the `WatermarkContractSync` using the `RateLimitedContractSyncCursor`.

`RateLimitedContractSyncCursor` is a forward-only cursor. The name reflects that - the "rate limiting" part only kicks in when we're close to the tip, this way we don't end up making a bunch of expensive eth_getLogs RPCs (or alternatives for other chains) when e.g. only one new block has come in. Much of the motivation for this was to do with RPC providers charging us a flat cost for a single eth_getLogs request regardless of how many blocks we were actually querying.

Requirements:
- re-evaluate the goals of watermark indexing to begin with - does the rationale behind it still even make sense? this feels rather ethereum-specific tbh -- for instance when we're doing block based indexing when indexing cosmos chain IGP payments, does it really make sense for us to rate limit ourselves at all?
- should we really rate limit ourselves up to 30 seconds? Because we use this for indexing IGP payments, this means we're only polling for new IGP payments every 30 seconds, and therefore if gas payments are being enforced, we're increasing the message delivery latency! Should this be configurable or related to the block time? Feel free to create issues out of this, rather than putting them in this refactor. See https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2308 and sleeping done in other cursors, e.g. https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/18d1d0d54eda245c4758b61261a003f7445edb18/rust/hyperlane-base/src/contract_sync/cursors/sequence_aware/forward.rs#L396
- consider whether the Sleep action makes sense or if the cursor itself should just sleep (see https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3262#discussion_r1493816338)
- simpler logic - it's too confusing
- unit test it rigorously
- if an error occurs getting a range of logs, that range should be retried. We shouldn't silently move on to the next range!
  - `next_action` should not move the cursor forward - only a call to `update`, which indicates a successful fetching of logs, should
  - remove retrying logic from `rust/chains/hyperlane-cosmos/src/providers/rpc.rs`:`get_logs_in_block`. Instead, propagate errors and make sure failed queries are retried.
- consider only implementing `HyperlaneWatermarkedLogStore<InterchainGasPayment> for HyperlaneRocksDB` [here](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/rust/hyperlane-base/src/db/rocks/hyperlane_db.rs#L317) instead of the generic T. At the moment for some reason we are happy to have a shared watermark across different cursors responsible for indexing different types, but iiuc there is no need for this!
- One of the most awkward parts about the current implementation of `RateLimitedContractSyncCursor` is that it can work in a block-range indexing mode, or a sequence-range indexing mode. This feels counter to what `RateLimitedContractSyncCursor` is intended to do to begin with - which is to rate limit itself due to the nature of block ranges! Imo `RateLimitedContractSyncCursor` is appropriate only as a block-range-based cursor, and we should rearrange things such that e.g. on Solana, we index IGP payments using a sequence-aware cursor, but on other chains, we index IGP payments using the rate limited contract sync cursor
  - We can maybe do this by moving away from `interchain_gas_payment_syncs: HashMap<HyperlaneDomain, Arc<WatermarkContractSync<InterchainGasPayment>>>` to a trait e.g. `interchain_gas_payment_syncs: HashMap<HyperlaneDomain, Arc<dyn ContractSyncer<InterchainGasPayment>>>,`
  - Note this may be getting close to the territory covered by https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3266 and https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3268. I'd suggest keeping these in mind when we choose our approach

```[tasklist]
### Tasks
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3417
```

**Comment by daniel-savu** [comment]
Tried to strip down this ticket to essentials in order of priority:
- switch from watermark to sequence-aware cursor for AEEs (includes using trait objects in `interchain_gas_payment_syncs`)
- simplify watermark cursor impl to only support block-range indexing
- restrict this impl to use `InterchainGasPayment` instead of a generic: `HyperlaneWatermarkedLogStore<T> for HyperlaneRocksDB`. Bc the watermark is stored under the IGP key anyway.
- retry instead of skipping on indexing errors
- bear in mind the ticket about separating indexing mode from cursor mode at compile time
- unit test

This task is mainly about reliability so I'll focus on that. I'll probably see about latency and error propagation later

**Comment by tkporter** [comment]
lgtm! for "switch from watermark to sequence-aware cursor for AEEs", just wanna make sure that this is just for Solana but that cosmwasm keeps using watermark

**Comment by daniel-savu** [comment]
Closing as this work was finished in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3500
