### ISSUE TITLE
Relayer should be able to submit transactions on Nitro orbit chains

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#3310]
Arbitrum nitro has a more elaborate gas pricing mechanism that the relayer hard codes right now https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/9a83eb4d57f89f5499c1b308fb0cfee0c815c7d3/rust/chains/hyperlane-ethereum/src/mailbox.rs#L235

This ticket captures the change to allow relayer operators to configure that any chain (like an orbit rollup) has these semantics

**Comment by tkporter** [comment]
Fixed by #3312 which was merged into main with #3260
