### ISSUE TITLE
CLI should help with setting up validators

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#3341]
## Problem

When running validators on AWS, its hard to know what the validator address is. Also, announcing requires sending funds to the validator (signer address).

## Solution

There should be a CLI command which helps folks to get the validator address from the announcement by passing in the bucket. And then also there should be a related command to announce the validator directly.

**Comment by muskbuster** [comment]
Will be taking this up @nambrot.

**Comment by brymut** [comment]
Hi @nambrot / @avious00 , making an attempt at this. Will update you with progress & PR

**Comment by avious00** [comment]
picked up by @aalaoui12 and in review
