### ISSUE TITLE
WarpCore: prevent transfer to zero-ish addresses

### ISSUE THREAD

**Issue by jmrossy** [hyperlane-xyz/hyperlane-monorepo#3421]
- Strengthen common sense tx data checks, including null-related addresses, before we submit the tx to the wallet to prevent unexpected tx encoding results.
- Add special logging & alerting to Sentry related to null address generation

Thread: https://discord.com/channels/935678348330434570/1217889698400440381

**Comment by avious00** [comment]
@yorhodes is it worthwhile for us to do the same for contract side or no?
