### ISSUE TITLE
Cosmos RPC fallback provider

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#3425]
## Problem

- On Comsos, we just have the fallback provider implemented for GRPC
- We use RPC for e.g. requesting block data in block-by-block indexing, so RPC is pretty critical

## Solution

- Implement fallback provider for Cosmos RPC

**Comment by avious00** [comment]
hey @tkporter is this a different fallback from https://github.com/hyperlane-xyz/issues/issues/892

**Comment by tkporter** [comment]
Recent motivating incident https://www.notion.so/hyperlanexyz/Neutron-indexing-outage-6eb3ad137337411c8329595a47e86147#8a5ae8509bdc4dad9b5af5495fb0b937

**Comment by antonr-p2p** [comment]
We face this issue from time to time for Neutron network, depending on frequency of Neutron validators upgrades. Last months there were few Neutron network outages that lead to Hyperlane validator stucking due to missing of proper failover to other RPC nodes.

**Comment by antonr-p2p** [comment]
Cool! Would wait for the new build to upgrade to!

**Comment by daniel-savu** [comment]
> Cool! Thanks! Would wait for the new build to upgrade to!

@antonr-p2p you're free to upgrade, we're also trying to move to versioned releases and this will be included in the next one (`agents-1.1.0`) that should go live by end of week
