### ISSUE TITLE
Warp route deployment verification is broken

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#3457]
## Problem

The [HyperlaneDeployer](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/02d5549608e97401edc5028ba59de0809c5a459e/typescript/sdk/src/deploy/verify/ContractVerifier.ts#L230) assumes that the verification `input.name` matches the contract name. 

The [HypERC20Deployer](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/dcb67e97da6e0e3d9abd1533dc2a5ca2ff9b4617/typescript/sdk/src/token/deploy.ts#L138) now uses the `TokenType` as the `contractName` but these do not match the actual contract name.

## Solution

Adjust `HypERC20Deployer` to use the correct contract names.

- [ ] Test warp route deployment **and verification** on testnet

**Comment by paulbalaji** [comment]
useful reference https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3379/files#diff-a7e3646e88e11cdab899cb99fa6e62f74893bdb0415e58879668cb79ff0ad3ec
