### ISSUE TITLE
CLI warp route deploys do not support ISM configuration

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#3479]
## Problem

`hyperlane warp deploy` only supports token configuration. Even worse, it assumes that the warp deployer wants to configure the ISM artifact from the `core deploy` (as an override) instead of inheriting the default behavior (and any future mailbox default configuration changes).

## Solution

The warp deploy should not assume that the ISM artifact is being configured from the `core deploy`. Instead, it should inherit the default behavior from the mailbox configuration.

## Nice to Have

It should support ISM and hook configuration as well, and this behavior should be reused from `hyperlane core deploy`.

**Comment by yorhodes** [comment]
see warp-deploy-ism-config branch

**Comment by tkporter** [comment]
I think we should roll this into scope for the issues here https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3541 / https://github.com/hyperlane-xyz/issues/issues/1190

**Comment by avious00** [comment]
@tkporter i see this issue is paired with the issues you mentioned, but not inside those issues. can you change this if that makes more sense for you?
