### ISSUE TITLE
[Investigate] Why does abacus deployment in beforeAll not work

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#351]
https://github.com/abacus-network/abacus-monorepo/runs/6115352394?check_suite_focus=true

Had to move abacus deployment in the beforeEach hook, since it seemed like state wasn't properly reverting where some message  dispatches from other test runs persisted and those message were then not processable since the target no longer exists

**Comment by asaj** [comment]
@nambrot can we close this?
