### ISSUE TITLE
goo

### ISSUE THREAD

**Issue by Romulobiscoito** [hyperlane-xyz/hyperlane-monorepo#3623]
## Problem

**Is your feature request related to a problem? Please describe.**

**Additional context**

## Solution

**Describe the solution you'd like**

**Describe alternatives you've considered**

## Nice to Have

**Describe non-essential extensions to the solution**
Additional features which should be implemented if they are easy to accommodate but otherwise can be skipped

**Comment by tkporter** [comment]
Hi @Romulobiscoito, not sure if you meant to create this issue, feel free to re-create one with details but I'll close this
