### ISSUE TITLE
Infra script to create AWS users / keys / buckets

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#363]
Right now, the creation of AWS users / keys / S3 buckets happens when getting helm values when running `deploy-agents.ts`. Compare this to GCP keys, which have `create-keys.ts`. This is not ideal for a few reasons:
1. it's an awkward pattern - e.g. someone getting helm values probably wouldn't think it'd result in a bunch of things happening on the AWS side behind the scenes
2. We need validator keys to deploy core contracts. The workaround is to run `deploy-agents.ts` before deploying core contracts, but this is awkward.
3. As a workaround for a race condition, we serially deploy helm charts in `deploy-agents.ts` (see [here](https://github.com/abacus-network/abacus-monorepo/pull/361/files/8de40881fb9c4f9ad195deb48fc5cd5debc99502#diff-e5e40509429103d7dbcf1fe361ceb26c7ea4a93704c4e68d2db08f97de738033R10)). Once this is done, we should get this back to a Promise.all

**Comment by avious00** [comment]
@nambrot to edit description

**Comment by nambrot** [comment]
@tkporter is this still valid? I thought we do create AWS resources in create-keys
