### ISSUE TITLE
Replace pending messages on chains we don't scrape

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-monorepo#3641]
- remove pending category from homepage
- remove top right spinning wheel for non-EVM when clicking in to tx
- for PI, this wlll be solved by registry

**Comment by jmrossy** [comment]
@avious00 I'm wondering if we should simply remove the status badge for messages on the home screen entirely.
We'll inevitably reach a point where so many messages are flying through that the latest ones we show will _always_ be pending. So not sure if it's creating value or making us look slow!

**Comment by yorhodes** [comment]
> @avious00 I'm wondering if we should simply remove the status badge for messages on the home screen entirely

either that or not show pending messages on home screen? or have a toggle?
