### ISSUE TITLE
Pull Explorer's metadata & artifacts from `registry` instead of SDK

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-monorepo#3655]

**Comment by avious00** [comment]
@jmrossy are any of the issues in the parent epic relevant here? or any other related issues for registry + explorer?

**Comment by jmrossy** [comment]
Sister tickets:
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3692
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3700
