### ISSUE TITLE
Connor's Starter Ticket

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#3711]
Capturing the scope for @cmcewen starter scope:

### Deploy Hyperlane to Holesky

Use https://github.com/hyperlane-xyz/v3-docs/pull/89 with the latest registry changes on the CLI, you'll need to use the pre-release version of the CLI to do this. The holesky deployment will be useful for https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3597 as well. This allows you to gain empathy for the PI deploy stakeholder as well give you exposure to contracts, SDK/CLI and running agents (right now with Kurtosis)

### Improve logging

Logging was recently overhauled in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3519 and https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3481. However, when deploying from the CLI, there are some inconsistencies in the logging approach (some are structured, some are not, different noisiness, misleading "error" messages). Your goal should be to recommend a consistent logging approach and change the logs. Also see this part of the README https://github.com/hyperlane-xyz/hyperlane-monorepo?tab=readme-ov-file#logging

**Comment by jmrossy** [comment]
> you'll need to use the pre-release version of the CLI to do this.
@cmcewen You can just `yarn build` the monorepo and then run the CLI from there with `yarn hyperlane` in the `typescript/cli` folder.

**Comment by cmcewen** [comment]
cli-2.0 😄
