### ISSUE TITLE
MVP for xERC20/Bridged USDC Hyperlane support

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#3716]
https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3618 added the scaffolding on the contract and SDK side to support xERC20 and Circle's Bridged USDC standard as per https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3486. This ticket captures the remaining work to make this MVP accessible to deployers
```[tasklist]
### xERC20
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3780
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3782
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3783
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3851
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3781
```

References:
- https://github.com/defi-wonderland/xerc20#deploy--verify

```[tasklist]
### Bridged USDC
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3778
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3777
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3779
```

References:
- https://www.circle.com/blog/bridged-usdc-standard
- https://github.com/circlefin/stablecoin-evm/blob/master/doc/bridged_USDC_standard.md
- [`FiatToken Deployment`](https://github.com/circlefin/stablecoin-evm/tree/master?tab=readme-ov-file#deployment)

**Comment by avious00** [comment]
fyi @alexwhte we closed contract work in https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3486 and our now doing tooling work here

included Connext steps here at the top 🫡
