### ISSUE TITLE
Ensure infra scripts / services use RPC URLs from GCP secrets

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#3774]
## Problem

It seems like following the registry code changes, we no longer use RPC URLs from GCP secrets

## Solution

Make sure that we use the private RPCs when running local deploys, kathy, key funder, etc

**Comment by yorhodes** [comment]
We should declare a `LocalRegistry` instance for each environment in infra
Then we can use `MergedRegistry` to combine that with the existing `MergedRegistry` that @jmrossy migrated infra to
if network round trips go the github remote registry are a concern, we can ignore the github registry entirely and just merge the local clone with the environment overrides

**Comment by jmrossy** [comment]
> We should declare a `LocalRegistry` instance for each environment in infra Then we can use `MergedRegistry`

I don't totally follow why we'd want separate LocalRegistries for that but RE MergedRegistry I guess this is reason reason number 2 to have it live outside the CLI. I'll migrate it to the Registry repo this week.

**Comment by tkporter** [comment]
done
