### ISSUE TITLE
Hyperlane cli panic out with '@hyperlane-xyz/core' does not provide an export named 'ECDSAStakeRegistry__factory'

### ISSUE THREAD

**Issue by bianyuanop** [hyperlane-xyz/hyperlane-monorepo#3797]
## Problem

The hyperlane cli errored out on executing any commands, e.g. `hyperlane --help`. See the error message below

> file:///home/ubuntu/.nvm/versions/node/v20.13.1/lib/node_modules/@hyperlane-xyz/cli/dist/src/avs/stakeRegistry.js:4
> import { ECDSAStakeRegistry__factory } from '@hyperlane-xyz/core';
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> SyntaxError: The requested module '@hyperlane-xyz/core' does not provide an export named 'ECDSAStakeRegistry__factory'
>     at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
>     at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
>     at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
>     at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
> 
> Node.js v20.13.1
> 

This error was produced on ubuntu 22.04 install by nvm

**Additional context**
OS: Ubuntu 22.04

## Solution
N/A

## Nice to Have
N/A

**Comment by yorhodes** [comment]
Thank you for your report, we are getting a hotfix up asap

**Comment by aroralanuk** [comment]
Please use the updated 3.12.2 version of the CLI. Closing this issue.
