### ISSUE TITLE
CLI command with pre-flight checks for a validator

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#3813]
## Problem

Partners should be able to run a CLI command that confirms their validator has been stood up correctly. This is part of the Hybrid HaaS process (https://www.notion.so/hyperlanexyz/Hybrid-HaaS-67195982e71b42de92bc83038498583a?pvs=4#ca11e1fe300940fc910ff5d8aff515ad) where we want to make sure that partners have set their validator up correctly before things are handed off to AW

## Solution

A CLI command that:
- Checks if a validator is announced, and outputs a link to the announced S3 bucket
- Checks that there are signed checkpoints in this S3 bucket
  - the latest checkpoint index should roughly match what's on chain (considering that due to reorg periods, validators don't necessarily sign the tip)

## Nice to have

It may be nice to think through how we may want to use this internally -- e.g. should it allow for multiple validator addresses to be supplied as well?
```[tasklist]
### Tasks
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3976
```

**Comment by tkporter** [comment]
Related: Kunal's work here in infra https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3923 - could maybe bring some of this into the CLI

Thread with some context here https://discord.com/channels/935678348330434570/1247230341006102661/1248454826074046572

**Comment by avious00** [comment]
@tkporter created a subtask for kunal to do that https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3976
