### ISSUE TITLE
Implement XERC20 type token adapter

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#3851]
## Problem

`TokenType.XERC20` and `TokenType.XERC20Lockbox` use the `EvmHypCollateral` token adapter type (used by `WarpCore` and in the UI). This nicely inherits token approval logic but fails when the destination chain is checked for sufficient collateral as neither of these `TokenRouter` variants actually custody the collateral token.

## Solution

- [ ] XERC20 adapter should check if the HypXERC20 has sufficient minting limits on the XERC20 for `handle`. This should take effect in `WarpCore.isDestinationCollateralSufficient`.
- [ ] XERC20 adapter should check if the HypXERC20 has sufficient burning limits on the XERC20 for `transferRemote`

**Comment by jmrossy** [comment]
@AlexBHarley Here are a few pointers of where we'd need code additions:
https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/typescript/sdk/src/token/Token.ts#L208
https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/typescript/sdk/src/token/Token.test.ts#L21
https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/typescript/sdk/src/token/adapters/EvmTokenAdapter.ts

And just for reference:
https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/typescript/sdk/src/warp/WarpCore.ts#L411
