### ISSUE TITLE
[fix][cli] forked provider not set in context.multiProvider during dry-run

### ISSUE THREAD

**Issue by ltyu** [hyperlane-xyz/hyperlane-monorepo#3862]
## Problem
In `getDryRunContext()` of cli/src/context/context.ts, a MultiProvider is created and passed into `forkNetworkToMultiProvider()`. 
https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/8a6654477eccc1316bf2933523c7c3e5a02625c6/typescript/cli/src/context/context.ts#L102-L103

The expectation is that the MultiProvider is mutated to a forked provider. However, this is not the case because a new MultiProvider is created, and is mutated instead.
https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/8a6654477eccc1316bf2933523c7c3e5a02625c6/typescript/cli/src/deploy/dry-run.ts#L23-L27

This is problematic because it leads to bugs that depends on the mutation of the context multiprovider. For example, calling `context.multiProvider.getProvider(chain)` with a dry run will fail, because `multiprovider.providers` doesn't get set (the expectation is it should get set inside `setFork()`). The result is `context.multiProvider.getProvider(chain)` will try to use the live RPCs, instead of anvil which will throw a `Error from provider #0: Error: Invalid response from provider -  Triggering next provider.`

For more details, please see this [thread](https://discord.com/channels/935678348330434570/1245437405847097364)

## Solution
Consider returning the new Multiprovider from `forkNetworkToMultiProvider()` 
```typescript

export async function getDryRunContext() {
   ...
   let multiProvider = await getMultiProvider(registry);
   multiProvider = await forkNetworkToMultiProvider(multiProvider, chain);
}
```

Alternative solutions can be found and discussed in this [thread](https://discord.com/channels/935678348330434570/1245437405847097364)

**Comment by nbayindirli** [comment]
fixed by https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3894
