### ISSUE TITLE
Prevent backward cursor from starving the forward cursor in the ForwardBackwardCursor

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#3916]
### Some context

Some examples:

We deployed the scraper at `16:59:20` yesterday, and then rolled back at `17:52:11` after getting some alerts and seeing that the explorer was lagging

This https://cloudlogging.app.goo.gl/DMpRzNbDfeJT5kB68 shows inserted messages for inevm, which had a pretty constant stream of messages coming in.

Upon startup, we have a single "Wrote new messages to database" log, and then never again until we restart the scraper. After restarting the scraper, a similar thing - no logs until a hour and a half later we see the next one - this time not from restarting, but just from letting the scraper do its thing

You can see the ranges for the forward/backward cursor here https://cloudlogging.app.goo.gl/Zka7n1vgpuJKB4qy8

What happens:
1. Right upon startup, forward returns None (no new messages forward to index) and backward returns a range (because between the scraper going down & coming back up, some new messages have come in)

2. On the next range attempt, forward again returns None (no new messages), but this time backward has already indexed the messages that it missed earlier, so it goes into the `skip_indexed` loop https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/rust/hyperlane-base/src/contract_sync/cursors/sequence_aware/backward.rs#L110-L145

3. each iteration of that loop involves several DB interactions. With RocksDB, this is pretty quick - with SQL, this means a network round trip for each DB interaction, and the queries seem pretty unoptimized :/

4. It seems after about an hour and a half, the ~317k inevm messages have been processed by the backward indexer (https://abacusworks.grafana.net/goto/jSbB5QySR?orgId=1). The image I rolled back to doesn't seem to instrument the `get_next_range` function however, but this is going off forward indexing progress resuming

## Solution

Our choices:

1. move the scraper back to the forward-only indexer
Dan's thoughts:
> I think the forward-only indexer has been removed when I last refactored, might be tricky to add back

2. prevent the backward cursor from starving forward progress by maybe breaking out of the skip_indexed loop if X seconds have elapsed. We'd need to make sure that in this case, we don't return a range from the backward cursor, and instead return None
Dan's thoughts:
> this seems quick to implement, I like it

3. try to optimize interactions with the scraper DB to avoid this
Dan's thoughts:
> this is my preferred fix - postgres shouldn't even have cursors for the most part. It supports fast queries over the entire message set - so imo iterating is only appropriate for rocksdb

We'll go with approach 2 as a quick fix

**Comment by daniel-savu** [comment]
fixed it https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3918
