### ISSUE TITLE
hyperlane core read shows provider errors

### ISSUE THREAD

**Issue by ltyu** [hyperlane-xyz/hyperlane-monorepo#4061]
## Problem
`hyperlane core read --mailbox 0xEf9F292fcEBC3848bF4bB92a96a04F9ECBb78E59 --chain alfajores` display provider errors. This is problematic because it can confuse users thinking they have an actual error
![Screenshot 2024-06-26 at 12 03 32 PM](https://github.com/hyperlane-xyz/hyperlane-monorepo/assets/6251863/056fc304-85e0-4f8a-8acb-ad1fe16b83bf)

## Solution
- Consider silencing the provider before trying to derive Ism?

- Dry out `setSmartProviderLogLevel()` as mentioned in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4055#discussion_r1653406785

**Comment by nbayindirli** [comment]
fixed by https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4194
