### ISSUE TITLE
Validator should be able to be configured to use GCP storage for checkpoints

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#4069]
## Problem

- GCP checkpoint storage is implemented and the relayer is seemingly capable of reading checkpoints
- Validator settings seem to not support this case though

## Solution

- Update the match that validators use to support using GCP storage https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/44cc9bf6b33f5288462ecc027e9d624ae682d552/rust/agents/validator/src/settings.rs#L151-L195
- Probably get rid of the Some(_) branch so this doesn't happen again
- Probably worth a run to confirm it actually works, and maybe another pass on the code

**Comment by mawutory** [comment]
@tkporter can i pick this up? this would be my first.

**Comment by daniel-savu** [comment]
we should also update out infra `announce-validators.ts` script to parse gcp paths and announce with that: https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/bb470aec25c02086921d1305c78cc09a1cda2528/typescript/infra/scripts/announce-validators.ts#L49

but this is probably for another ticket

**Comment by daniel-savu** [comment]
> @tkporter can i pick this up? this would be my first.

go for it @mawutory

**Comment by mawutory** [comment]
thanks @daniel-savu here's what i believe is expected of me:

replace `Some(_)` with `Some("gcp")` having a similar structure as `Some("s3")`?

**Comment by daniel-savu** [comment]
closed in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3156 and other follow ups
