### ISSUE TITLE
Relayer retry API: retry a subset of messages

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#4079]
## Problem

- We have large prep queues
- We probably want the ability to retry only messages that are important for the problem at hand -- e.g. maybe we want to retry everything for a given origin, or we want to retry only messages for a specific app

## Solution

- Probably involves using matching lists
- It'd be nice to not need to construct these matching lists manually - maybe a CLI command or infra script to help us do this makes sense?

**Comment by Mantas-M** [comment]
On it 🫡

**Comment by Mantas-M** [comment]
@tkporter Is there a preference to which automation to use for matching list generation?
I would assume it would be either:
- Commander project
- Bash script
From my understanding, both would essentially produce JSON, saved to a file, and to be used in the retry API endpoint as a payload, is that correct?

**Comment by daniel-savu** [comment]
> @tkporter Is there a preference to which automation to use for matching list generation? I would assume it would be either:
> 
> * Commander project
> * Bash script
> 
> From my understanding, both would essentially produce JSON, saved to a file, and to be used in the retry API endpoint as a payload, is that correct?

@Mantas-M we actually just manually define the matching lists, so you don't need to worry about generation. The endpoint would just take in the JSON-encoded matching list string

**Comment by daniel-savu** [comment]
closed in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4693
