### ISSUE TITLE
High urgency alerts related to traffic should not go off for newly added chains

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#4086]
## Problem

We get alerted when there are no message deliveries from a given origin or to a given destination in a period of time. This poses issues for new chains, where we often start getting metrics for some chains before they're fully connected with other chains and have some meaningful traffic on them.

A few weeks ago I changed the origin "mainnet3 origin chain deliveries" alert query https://abacusworks.grafana.net/alerting/e9d6a58f-94f7-4173-a0ad-1416388857bd/edit?returnTo=%2Falerting%2Flist to be a little more friendly -- it requires opting chains into a more aggressive window and otherwise puts chains into a more lenient time window. I didn't change the destination one "mainnet3 destination chain deliveries" https://abacusworks.grafana.net/alerting/c50e1f7e-872a-4ebb-bac8-c331ba8f7048/edit?returnTo=%2Falerting%2Flist

## Solution

I think moving the destination alert to something closer to the origin one would help, and maybe also a rule to ignore chains whose latest nonce is < 20 message or something, which would indicate that a chain is too new and can be ignored

Mostly wanna avoid ppl getting alerted for new chains but also make sure that we have some alert coverage for new chains when they're "ready"

We should make sure whatever new queries we write have some nice comments to explain what they're doing -- imo we should treat these as bits of code that should be easy to understand / documented

## Nice to Have

- would be nice for this to not require too much human action to promote a chain from "new and low traffic" to "less new and higher traffic". Could get fancy and maybe look at message volume in the past xx days or something as a heuristic
- If this does require human action, make sure it's part of the "adding a new chain" part of the runbook

**Comment by paulbalaji** [comment]
alert has been up and not fired unnecessarily for 2-3 recent batches now
