### ISSUE TITLE
Add monitoring and alerting for hardware usage of kubernetes pods

### ISSUE THREAD

**Issue by daniel-savu** [hyperlane-xyz/hyperlane-monorepo#4109]
## Problem

We only noticed the recent Gas Escalator roll out issue by observing a weird pattern in the RC prep queue dasbhoard. Ideally we should alert on increased resource usage that is sustained over at least 1h - to filter out startup CPU spikes and similar. the `hyperlane` and `neutron` contexts should be high severity and `rc` can be low severity

**Comment by tkporter** [comment]
See https://abacusworks.grafana.net/d/FSR9YWr7k/containers?orgId=1&refresh=1m

**Comment by daniel-savu** [comment]
done by @tkporter in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4158 and then by creating these alerts:
- https://abacusworks.grafana.net/alerting/grafana/fdrx0zpe84av4c/view?returnTo=%2Falerting%2Flist
- https://abacusworks.grafana.net/alerting/grafana/cds0thghpi9z4e/view?returnTo=%2Falerting%2Flist
