### ISSUE TITLE
AbacusCore should support multiple deployments per environment

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#417]
There will likely be multiple testnet deployments to test additional changes on top of the current testnet deployment and in general, changes to the protocol will happen. The general migration path will be to have AbacusConnectionManagers enroll multiple Outboxes/Inboxes per domain to gradually migrate to those newer deployments.

AbacusCore should be able to support this reality so that this migration path can be tested asap.

**Comment by asaj** [comment]
I would call these separate environments, no?

**Comment by asaj** [comment]
I would still call these separate environments :)
