### ISSUE TITLE
More clear status of each chain deployment when running deploy.ts

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#4230]
## Problem

Inspired by https://www.notion.so/hyperlanexyz/Deploy-Notes-July-26-9595392a3a2e4bbe9bc64439ade94d09. More info https://www.notion.so/hyperlanexyz/Deploy-Notes-July-26-9595392a3a2e4bbe9bc64439ade94d09?pvs=4#082b018210e8442da2b335615812e596

Copying some info from that Notion when we ran `deploy.ts -m core --concurrentDeploy`:
- It’s likely that at least viction failed at some point - the default hook wasn’t updated with the new domains
    - These “silent” failures are very annoying and should be surfaced more clearly. Now that we have so many chains it’s easy to get lost in the output. Maybe a summary with good error colors?
    - Happened for scroll too
    - When we originally ran the deploy script, it stopped outputting new logs but hadn’t yet exited. The only “deployment failed” log was to do with arbitrum. Maybe the viction & scroll tasks were hanging without a timeout or something?
- seems likely that the root cause was probably the initialize check in the Mailbox deploy tooling being flaky for Scroll, Viction, and Arbitrum. This HyperlaneCoreDeployer.ts likely doesn’t meet the cut as it’s so dependent on RPC URL error messages. We'll address this separately, but the root problem of this not being clear when running deploy.ts is what to focus on here

## Solution

I wouldn't spend tons of time on this tbh but there must be some low hanging fruit to make this easier to use and understand.

- It should be much more clear if a chain deployment fails or times out
- Maybe we can have some kind of status of all concurrent deploys?

## Nice to Have

**Describe non-essential extensions to the solution**
Additional features which should be implemented if they are easy to accommodate but otherwise can be skipped

**Comment by paulbalaji** [comment]
- Need better logging of:
    - How many chains we’re deploying to
    - How many succeed
    - How many fail
    - And need this to be tolerant of the fact that we could timeout and the deployment might still succeed

from https://www.notion.so/hyperlanexyz/Enrollment-Notes-August-14-xlayer-cheesechain-worldchain-zircuit-f8af8f6e9aaa48fd92be60756cb3e895

**Comment by paulbalaji** [comment]
Add a failure summary, red error messages and have a clear distinction between debug and info logs for deploy commands

Same as https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4347
