### ISSUE TITLE
[BUG] warp init outputting an empty {}

### ISSUE THREAD

**Issue by drewstone** [hyperlane-xyz/hyperlane-monorepo#4255]
# Overview
Version 5.0.0. Calling `warp init` with the CLI doesn't really do anything as far as configuration building goes. Is this the correct behavior? It just creates a `yaml` with `{}` inside.
```
npx @hyperlane-xyz/cli warp init
Hyperlane CLI
Hyperlane Warp Configure
------------------------
Creating a new warp route deployment config...
? Detected owner address as 0x89db5277A310C473d515891cafCD4E66b8A7F06F from signer, is this correct? yes
? Select network type Mainnet
Use SPACE key to select chains, then press ENTER
? Select chains to connect
Warp Route config is valid, writing to file ./configs/warp-route-deployment.yaml:

    {}

✅ Successfully created new warp route deployment config.
```

**Comment by yorhodes** [comment]
hey @drewstone , I think this is an issue we inherited from https://www.npmjs.com/package/inquirer where you have to use the spacebar to select in a multiselect and then press enter once you have selected a list of chains
I will patch this by requiring that at least 2 chains are selected before proceeding
