### ISSUE TITLE
Developers should understand if insufficient gas payments cause the lack of processing of their message

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#440]
Once #313 is in, developers should easily determine whether a message that hasn't been processed is due to insufficient gas payments. That could be solved with #414 , but if that won't be live, tooling should be available to the developer

**Comment by nambrot** [comment]
I.e. given a message, the calculator should say whether a message should be processable right now, by looking for the actually paid amount, and then estimateGas for the processing, either just the handle or (if easy) submit the signatures and merkle proof.

**Comment by nambrot** [comment]
That estimateGas also would then be helpful in debugging as to why a message may not be processed (even if enough gas was paid for)

**Comment by tkporter** [comment]
I'm a little inclined to wait to do this till we are closer to shipping GRR, wdyt?

**Comment by nambrot** [comment]
shipping grr, or letting folks operate under grr? I think it may still be valuable to let folks know what they are supposed to do, even if grr isn't fully functionaining yet?

**Comment by nambrot** [comment]
Now on the explorer
