### ISSUE TITLE
Message explorer

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#442]
A message explorer to show the progress/status of a message through the Abacus system

- #77 
- #414 
- #885
- #886
- #887
- #814
- #815
- #590 

- hyperlane-xyz/issues/issues/201 (only do this work if explorer will not ship before Bogota)
- hyperlane-xyz/issues/issues/202 (only do this work if explorer will not ship before Bogota)
- hyperlane-xyz/issues/issues/198
- hyperlane-xyz/issues/issues/199
- hyperlane-xyz/issues/issues/200

We could even consider an even lighter weight version of this that just runs a modified agents and spits out structured logs and then expose that in BigQuery.

Another alternative is the creation of TheGraph subgraphs on all chains and then have some querying on top

**Comment by Skunkchain** [comment]
If we opt for subgraphs I can talk to folks at the graph about it. Also, Figment is one of the best at working with subgraphs and could likely help here.

**Comment by Skunkchain** [comment]
If we opt for subgraphs I can talk to folks at the graph about it. Also, Figment is one of the best at working with subgraphs and could likely help here.

**Comment by jennifermarie** [comment]
Added a few new items to this epic following feedback sourced from ETH Berlin.
