### ISSUE TITLE
Create an Agent debug API framework

### ISSUE THREAD

**Issue by mattiekat** [hyperlane-xyz/hyperlane-monorepo#453]
@webbhorn had the great idea that we should have a way to query the current state of an agent for when the world is on fire. This should probably just be a somewhat basic HTTP API that is NOT normally exposed but that we can query if we do a kube port-forward.

Might want to put this in abacus-base and have a way for different agents to add additional options. Let's also decide on insomnia or postman and then create a config we can save to the repo to quickly import all the possible debug queries.

#452 should be the first function on the API.

**Comment by nambrot** [comment]
I think obviously this will be useful to have, but I'm not sure that I would start with an HTTP based API? I believe what's already supported is a CLI that can be invoked to return DB state which I imagine is the most impactful one? Even just pulling the DB locally seems like possibly a better trade-off that implementing a full blown debug API at this stage?

**Comment by mattiecnvr** [comment]
> I believe what's already supported is a CLI that can be invoked to return DB state

What CLI tool is this? If we already have something then maybe but I was under the impression that we did not. I do see the tools crates but nothing that looks like it does anything similar.

Again the proposal is for a private API that allows for debug info, this could then be queried by a CLI. Unless you have a CLI which is reading files on the container volumes I am not sure how you are getting the information out of their DBs.

**Comment by nambrot** [comment]
This is basically https://github.com/hyperlane-xyz/issues/issues/868, so closing this
