### ISSUE TITLE
Make ChainConnection a ethers.Provider

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#462]
- Make ChainConnection a ethers.Provider
- use the provider for read calls
- use the signer for write transactions
- Optional: 
  - add a `waitConfirmations` to `ContractTransaction`
  - have global overrides
  - have retries built-in

**Comment by nambrot** [comment]
Hmm an important obsevation in https://docs.ethers.io/v5/api/signer/#Signer--subclassing

> It is very important that all important properties of a Signer are immutable. Since Ethereum is very asynchronous and deals with critical data (such as ether and other potentially valuable crypto assets), keeping properties such as the provider and address static throughout the life-cycle of the Signer helps prevent serious issues and many other classes and libraries make this assumption.

Makes me less confident that this is the way. Because effectively, we are creating a mutable provider/signer (eventually when we allow the change of a signer). I guess for now I'll just consider this to be immutable

**Comment by asaj** [comment]
@nambrot do we still want to do this?

**Comment by nambrot** [comment]
Feel less convicted about this now, so happy to punt

**Comment by nambrot** [comment]
This is done
