### ISSUE TITLE
Expose metrics for sequence indexing cursor progress

### ISSUE THREAD

**Issue by daniel-savu** [hyperlane-xyz/hyperlane-monorepo#4715]
# Context 
Sequenced events like `HyperlaneMessage` and `MerkleTreeInsertion` are indexed using a forward-backward cursor which is initialized to the sequence number at the blockchain tip, when the agent is started. 

For instance, if the last `HyperlaneMessage` had nonce 123, the forward-backward cursor would instantiate:
- a forward cursor that looks for messages in new blocks, with nonces 124 and up
- a backward cursor that iterates blocks from the tip back to genesis (or to whatever is configured in `index.from`)

# Problem
When an RPC becomes healthy after an outage, it's hard to know if agents are making any progress indexing the missed events over that period. If they're running but not making any progress, the RPC may still be having issues. The only way to know this is by checking raw logs, which requires knowledge of what to look for.

# Suggested Solution
A simple way to provide better observability here is to have some new Prometheus metrics for indexed events:
- for all event types (regardless if sequenced or not): the block number the cursor(s) are currently at
- for sequenced events: the sequence number that the backward and forward cursors are on, and the max known sequence

To continue with the `HyperlaneMessage` example, the metrics at a random point for a given chain would look something like:
- `cursor_current_block{eventType: 'HyperlaneMessage', cursorType: 'ForwardSequenced'}: 118000`
- `cursor_current_sequence{eventType: 'HyperlaneMessage', cursorType: 'ForwardSequenced'}: 240`
- `cursor_current_block{eventType: 'HyperlaneMessage', cursorType: 'BackwardSequenced'}: 91021`
- `cursor_current_sequence{eventType: 'HyperlaneMessage', cursorType: 'BackwardSequenced'}: 82`
- `cursor_max_sequence{eventType: 'HyperlaneMessage'}: 345`

Based on this, it will be much easier to have dashboard showing the indexing progress agents make after each RPC rotation and restart, per indexed event and chain.

**Comment by RajVerma97** [comment]
can you assign me?
and how much is the bounty?

**Comment by daniel-savu** [comment]
> can you assign me? and how much is the bounty?

@RajVerma97 sure thing! The approximate scope I assigned is `small` which is $500. If it ends up being easier than expected, it'll be `extra-small` which is $250. KYC is required FYI

**Comment by RajVerma97** [comment]
got it

**Comment by RajVerma97** [comment]
i am having issues in running the project locally
i did npm install 
then npm run build 
still cant see the project locally

**Comment by paulbalaji** [comment]
> i am having issues in running the project locally i did npm install then npm run build still cant see the project locally

please read the "working on hyperlane" section of the monorepo README. For further questions, join the discord and ask the community for help. https://github.com/hyperlane-xyz/hyperlane-monorepo#working-on-hyperlane

**Comment by RajVerma97** [comment]
<img width="1243" alt="Screenshot 2024-10-23 at 5 21 32 PM" src="https://github.com/user-attachments/assets/8b56cdea-9abc-4ebf-bb18-0dc75e9318eb">

do i have to add the metrics here?

**Comment by RajVerma97** [comment]
sorry i wasnt able to move forward

**Comment by Mantas-M** [comment]
On it 🫡
