### ISSUE TITLE
"cargo miri test" for agents

### ISSUE THREAD

**Issue by webbhorn** [hyperlane-xyz/hyperlane-monorepo#476]
[Miri](https://github.com/rust-lang/miri) is a rust sanitizer that can detect certain categories of undefined behavior.

Interestingly, Miri does not actually run cleanly against the current agents (though probably not for an interesting reason). In particular, it [claims to find undefined behavior in our agent unit tests](https://gist.github.com/webbhorn/a34fecbae269e3d6213142af277814d8), though it is likely a false positive as the error string notes. The error seems potentially macOS-specific, since the triggering stack trace appears to be async-tokio waiting for an event via a syscall to kqueue(2) -- nothing agent-specific going on. I was able trigger the error on my M1 Macbook Pro against both the `aarch64-apple-darwin` target and the `x86_64-apple-darwin` target so I don't think it's arm-specific. I only spent a few minutes and haven't tried running on a linux-x86 target.

[Edit: it isn't detecting UB, it is just flat-out saying you aren't allowed to call foreign function kqueue]

In any case, it'd be nice to one day:

- ascertain whether the detection really is a false positive or not [Edit: it's not even a false positive]
- make whatever change we need to in order to get reliable clean runs against the targets we care about (maybe just x86 linux?)
- set up an additional [https://github.com/abacus-network/abacus-monorepo/blob/main/.github/workflows/rust.yml](workflow) for our project so that we guard against any introduction of new UB (or are able to detect if that happens via a dependency). I think miri requires nightly, but they have [documentation](https://github.com/rust-lang/miri#running-miri-on-ci) how to set this up in a github workflow file.

As far as I understand how miri works, it instruments intermediate representation and looks for instances of UB at runtime, which means that the value we'd get from this check also depends on the extent to which our test code actually triggers relevant code paths. So, as test coverage improves, the value we'd get from something like miri also improves.

If speed or performance is not prohibitive, we could also consider running one or two agents in the testnet environment under miri to get coverage against real life workloads. We could imagine doing that against mainnet one day too, if they run in some kind of read-only mode perhaps. We'd want some monitoring so that we'd actually find out if/when it did ever find something!

These are all just ideas and I don't think this is a big priority, but opening this bug to track the proposal for when it is appropriate to eventually invest some time on.

**Comment by nambrot** [comment]
v old
