### ISSUE TITLE
chore: Upgrade SeaORM to the latest version

### ISSUE THREAD

**Issue by ameten** [hyperlane-xyz/hyperlane-monorepo#4793]
## Problem

Currently we are using obsolete version of SeaORM, namely `0.11.1` and we generate entities using version `0.12.3`. It produces different source code for the entities which a developer has to remove when the developer changes the migration scripts.

## Solution

Upgrade SeaORM to the latest version everywhere:
1. To be used for migrations
2. To be used for generating entities
3. To be used by Scraper to interact with Postgres DB

### Tasks
1. Upgrade SeaORM in `main/Cargo.toml` (`sea-orm` and `sea-orm-migration`).
2. Upgrade SeaORM in `generate_entities.rs` and regenerate entities. Make sure that new datatypes can handle existing data without issues.
4. Make the code compilable again.
5. Remove SeaORM from `sealevel/Cargo.toml`.

## Testing

1. Run Scraper from mainstream branch with current SeaORM version and populate database with data from some blockchain
6. Switch to the feature branch with the latest SeaORM version.
7. Run Scraper from feature brach and confirm that all the data is populated in the same format as before

**Comment by tkporter** [comment]
@Mantas-M is doing this (can't assign on github bc he's not in the org)
