### ISSUE TITLE
Investigate Gelato Relay API observability

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#489]
* How can we debug if a message isn't being processed? We should investigate the Gelato Relay API and see what our options are

**Comment by tkporter** [comment]
Looks like there is a task ID that is returned from their API when creating a new task

**Comment by nambrot** [comment]
We should consider surfacing some of this information in #414 , @webbhorn feel free to comment on that ticket if you wanna reserve something in the schema

**Comment by asaj** [comment]
We dropped gelato
