### ISSUE TITLE
Update infra to run Relayer to use Gelato Relayer API for supported networks

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#492]
* Blocked by:
   * https://github.com/abacus-network/abacus-monorepo/issues/485
* Following https://github.com/abacus-network/abacus-monorepo/issues/485, we will likely have a list of networks that Gelato supports being passed in to the Relayer settings. We should update `infra` to specify this correctly

**Comment by asaj** [comment]
@tkporter we did this, right?

**Comment by tkporter** [comment]
yeah, closing
