### ISSUE TITLE
Forward payments from InterchainGasPaymaster to Gelato Gas Tank

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#493]
* This is only necessary for mainnet. Currently, Gelato's off chain accounting system (i.e. their logic behind managing their gas tanks) isn't ready. As of May 23, from Telegram:
   * For gas tank payments (type 1 and type 2) we need a few weeks until we launch the off-chain accounting system, but because here payment mode is decoupled from the stability and robustness of the relay APIs / smart contracts, we can launch with you asap and worry about payments later.
   * Our GasTank will be available in a few weeks as soon as we finish some required work for our off-chain accounting system. I will forward you its implementation as soon as available. For the time being, we chose to let everyone know about our Gelato Relay which is finished. Even without having the off-chain payment system, devs like you would be able to try it out and this should speed up the feedback loop on both sides.
   * But from a high level perspective, the Gas Tank will simply be a smart contract where you would be able to deposit funds on behalf of your users, or even your users directly. For each ForwardRequest, sponsor is the EOA that must sign the data in order to commit to a payment, and therefore hold enough balance in the Gelato gas tank so we can deduct asynchronously. I see two different ways of making this happen:
      a. You can have your own sponsor EOA, that aggregates all of your user's balances into one slot in the Gas Tank, and signs each ForwardRequest that is submitted to our API. The awkward part here is that with a single balance it is hard to have a granular overview on how much each of your users has deposited. There could be situations where user A deposits in excess and user B has a deficit, and if done naively we would take user A's surplus balance to pay for B's. 
      b. Knowing that each of your users will deposit their funds into Gelato (and you won't be subsidising them from a single sponsor EOA), and bump if needed be, we could have a setup where you create a temp private key for each user in the front-end just to sign the ForwardRequest and to hold funds in the Gelato gas tank. This could simplify the on-chain implementation, as all you would have to do is transfer the user's funds into the Gelato Gas Tank and name the address of this temporary PK as the sponsor in the Gas Tank.  And so we execute the ForwardRequest, emit the fee to be credited and sponsor address from this temp private key, and then a few hours later deduct the deposited funds from the Gas Tank's balance. And because you create the temp PK on your side, the user doesn't need to craft another signature just to deposit into Gelato for a single tx, which could hurt UX. You would likely need to store a mapping from the user's address to this temp PK in order to handle fee bumping if needed.

We'll be going with option (a).
A lot of this depends on timing - assuming we'll launch on mainnet after Gelato's gas tank work is completed, we can make this change. Otherwise, we should make InterchainGasPaymaster upgradeable, launch on mainnet without gas tank, and then upgrade the implementation to forward payments to the gas tank later. This is probably preferable over swapping out the contract because then the agents don't have to worry about indexing issues. The scope of this seems small regardless of how the timing works out, so let's first build out the agents and we can decide what action to take here once we feel confident this is the missing piece

**Comment by jennifermarie** [comment]
Closing this; no longer relevant to epic.
