### ISSUE TITLE
Document and showcase advanced Router abi codec patterns

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#494]
Currently we only showcase single message type applications in the [abacus-app-template `HelloWorld`](https://github.com/abacus-network/abacus-app-template/blob/main/contracts/HelloWorld.sol) and [abacus-token `AbcERC20`](https://github.com/abacus-network/abacus-token/blob/main/contracts/AbcERC20.sol). We should demonstrate internal handler functions with multiple message type decoding in favor of `TypedMemView` usage (as well as migrate `Controller`/`Governance`). Ideally we can decode without copying from `calldata` to `memory`.

**Comment by asaj** [comment]
@yorhodes would you say we do this now?

**Comment by yorhodes** [comment]
yes!
