### ISSUE TITLE
Use `finality_blocks` instead of `reorg_period` in validator

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#532]
In #504, `finality_blocks` was added for each ChainConfig. The `reorg_period` in the Validator agent settings is basically a duplicate of this-- we should remove `reorg_period` in favor of `finality_blocks` and update the `infra` package accordingly

**Comment by ritikBhandari** [comment]
I'd like to take up this issue if possible.

**Comment by tkporter** [comment]
hey @ritikBhandari, amazing please do! I'm happy to answer any questions you may have

**Comment by ritikBhandari** [comment]
Sure. Thanks!

**Comment by tkporter** [comment]
Hey @ritikBhandari, just wondering if you've taken a stab at this?

**Comment by nambrot** [comment]
Related is also the confirmations field in `ChainConnection` which should be part of this merge

**Comment by avious00** [comment]
hey @mattiecnvr is this still in review?

**Comment by mattiecnvr** [comment]
@avious00
No, and from what I can tell it will need to be re-done if we want to move forward with it.

**Comment by mattiecnvr** [comment]
I think this would make sense to do with #2215

**Comment by mattiecnvr** [comment]
This ended up changing a bit with the new config shapes and we are now using reorg period but it is the one defined in the common chain metadata.
