### ISSUE TITLE
Support hosted whitelisted relayers

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#587]
Applications may choose to effectively pay for their application messages, especially if the interchain gas payment protocol cannot accomodate their messaging patterns. In that case, there may be operators who run the relayers, but the application developers fund them and take the risk of grievance.

The infra package should support the deployment of multiple relayer instances with different whitelist and `InterchainGasPaymaster` configurations.

Create new instance:
- [ ] Deploy interchain gas paymasters
- [ ] Persist whitelist configuration

Application developers should then have an easy way to:
- [ ] Observe the relayer addresses and fund them when necessary
- [ ] Be able to withdraw funds from configured Interchain Gas Paymasters

**Comment by asaj** [comment]
I believe @tkporter did this with "contexts"
