### ISSUE TITLE
Configure routing for notifications/alerts from GCP

### ISSUE THREAD

**Issue by webbhorn** [hyperlane-xyz/hyperlane-monorepo#617]
Sometimes the GCP console displays warnings or errors about our cluster. It could be beneficial for us to at least find a way to get email-notifications for some sufficiently severe category of alert. This issue is kind of backburner for now, but tracks exploring options and potentially setting that up.

**Comment by mattiecnvr** [comment]
Looks like the "correct" way to do this is using the pub/sub service, but I don't see a way with this to send emails directly, so we would need to post it to something that sends the email or do a webhook with discord and just publish it to a channel.

Relevant docs:
https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-notifications

Relevant service page:
https://console.cloud.google.com/cloudpubsub/topic/list?project=abacus-labs-dev
