### ISSUE TITLE
Mainnet alpha operating as expected

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#628]
* https://github.com/abacus-network/abacus-monorepo/issues/625
* https://github.com/abacus-network/abacus-monorepo/issues/624
* https://github.com/abacus-network/abacus-monorepo/issues/617
* https://github.com/abacus-network/abacus-monorepo/issues/615
* https://github.com/abacus-network/abacus-monorepo/issues/551
* https://github.com/abacus-network/abacus-monorepo/issues/573
* https://github.com/abacus-network/abacus-monorepo/issues/596

**Comment by nambrot** [comment]
POssible overlap with https://github.com/abacus-network/issues/issues/77
