### ISSUE TITLE
Tooling to migrate existing Optics v2 xApps to Abacus

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#63]
While many of the relay smart contracts are upgradable, new instances of the relay will be deployed whenever major changes are released.

Xapps can migrate to new relay instances so long as they are backwards compatible by calling `xAppConnectionManager.enrollReplica()` to enroll the new replicas.

Once all the new replicas are enrolled, xapps can call `xAppConnectionManager.setHome` to start directing messages to the new relay.

Eventually, xapps should call `xAppConnectionManager.unenrollReplica` to deprecate the old relay instance.

There should be governance tooling to support this process.

**Comment by nambrot** [comment]
We have made sufficient changes that there are now to kinds of migrations that we should talk about:

1. Migration from some version of an Abacus Relay to another.
2. Migration from the Optics Relay to an Abacus Relay.

This ticket should now encompass only 2), 1) should be covered by https://github.com/abacus-network/abacus-monorepo/issues/416

For the existing apps on Optics v2, they will need contract upgrades to support things like gas payments, and thus the upgrade path probably looks closer to:

- Create an AbacusConnectionManager that enrolls both existing Optics v2 replicas and Abacus Inboxes/Outboxes
- Upgrade xApp Routers to the latest versions and set the abacusConnectionManager atomically (that will allow existing messages to continue to be relayed)

Obviously this is a pretty invasive operation and thus should be tested rather thoroughly.

**Comment by asaj** [comment]
Outdated
