### ISSUE TITLE
High concurrency on `Outbox.dispatch` calls causes unpredictable gas estimation

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#634]
Number of iterations that run in [`tree.insert`](https://github.com/abacus-network/abacus-monorepo/blob/main/solidity/core/contracts/libs/Merkle.sol#L29-L45) causes gas estimation to be inconsistent with gas consumption when there are many concurrent pending transactions which dispatch messages on the `Outbox`

**Comment by yorhodes** [comment]
See out of gas failures on https://kovan.etherscan.io/address/0x057d38d184d74192b96840d8fbb37e584ddb569a (kathy)

**Comment by asaj** [comment]
This happened again, needs to be increased from 10%, suggest going to 20%

**Comment by asaj** [comment]
https://github.com/abacus-network/abacus-monorepo/pull/836

**Comment by yorhodes** [comment]
I don't think #836 solves this issue satisfactorily. Presumably applications should not need to apply this estimation buffer unilaterally.

**Comment by avious00** [comment]
@yorhodes can this be closed?
