### ISSUE TITLE
Deploys should happen concurrently

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#640]
We had to revert concurrent deploys because they led to non-deterministic contract addresses for the core deploy which agent development implicitly relied on https://github.com/abacus-network/abacus-monorepo/pull/639

However, concurrent deploys obviously are preferable since they reduce the total time consumed. Whenever environment management is under better control, we should consider re-adding concurrent deploys.

Deploys probably should become more reliable so that debugging of deploys is not getting worse when doing so

**Comment by asaj** [comment]
I feel like we no longer need/want this
