### ISSUE TITLE
Remove all Checkpointer references in infra & code

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#641]
* We've moved away from the Checkpointer being required, and it seems like it was mostly removed from Rust. We should do a pass of the Rust code and ensure all Checkpointer references are removed, and we should remove all Checkpointer-related code in the `infra` package.

**Comment by tkporter** [comment]
Partially satisfied by #673

**Comment by asaj** [comment]
We did this :)
