### ISSUE TITLE
NFT E2E example

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#657]
We do not have an example of how to built an Abacus app end to end with the tooling that has been worked on. The hypothesis is that the tooling is the simplest way to create and deploy such an application and can be done in a weekend. As part of this effort, there is likely additional tooling that we want to create to help developers build UIs. Specifically manage signers across wallets for the MultiProvider.

- #658 
- #659

**Comment by yorhodes** [comment]
closing in favor of https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1458

**Comment by nambrot** [comment]
Hmm that is actually a good point, I believe we have mostly worked for ERC20, but obviously the contracts already exist as 721
