### ISSUE TITLE
Abacus ERC721 v0.2

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#658]
- Mint ranges 
- some basic properties per chain

**Comment by jmrossy** [comment]
@yorhodes Though I suggested the other day that the ERC721 live with the ERC20 in the same repo (as it does now), I've reconsidered and think we should make a separate repo with the contracts + nft app together. WDYT?

**Comment by yorhodes** [comment]
closed by https://github.com/hyperlane-xyz/hyperlane-token/pull/10
