### ISSUE TITLE
Build a simple UI for a NFT app

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#659]
- Should allow you to mint on any chain
- Allows you to switch networks
- Lists the NFTs you own
- Allows you to transfer the NFTs to a different chain

As part of this effort, likely some common abstraction to handling signers for a multiprovider in the UI should fall out

**Comment by jmrossy** [comment]
I propose a simple stack for the web app:
`Next.js (which includes React) + Tailwind + Ethers.js`

And for the contracts it would be the usual `Hardhat + Typechain`, same as the HelloWorld app.

I don't think we'll need any state management or other component libs will be needed for this.
