### ISSUE TITLE
Mainnet relayers experiencing deserialization error

### ISSUE THREAD

**Issue by mattiecnvr** [hyperlane-xyz/hyperlane-monorepo#680]
```
Error in retrying provider

Deserialization Error: EOF while parsing a value at line 1 column 0. Response:
```

`eth_getBlockByNumber` and `eth_blockNumber` seem to exclusively be the problem functions right now. I have confirmed that this error is happening in more than one relayer on mainnet and is NOT happening in testnet.

You can see this section of logs at https://cloudlogging.app.goo.gl/QGeyovGjx9niyG287.

After restarting relayers in mainnet avalanche processed messages but it looks like optimism still has pending ones, though there are no errors visible in the log to explain it. It is also not putting them in the retry queue.

It is possible we might have gotten caught in a re-org on one of these chains or that we were getting rate limited.

We should check if we were getting rate limited or if it was a provider error of some sort. Ideally we would have better logs for when these errors happen so we can see what data they are responding with.

**Comment by asaj** [comment]
I believe this is fixed
