### ISSUE TITLE
Verify InterchainGasPaymaster on testnet2 and mainnet

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#753]
Blocked by #674 and #752 

* Once the IGP is deployed onto testnet2 and mainnet, they should be verified

**Comment by yorhodes** [comment]
unblocked by https://github.com/abacus-network/abacus-monorepo/pull/720

**Comment by yorhodes** [comment]
mainnet
![Screen Shot 2022-07-18 at 11 26 51 AM](https://user-images.githubusercontent.com/3020995/179546472-6e26db98-e443-4245-88c2-a94b31803fed.png)

**Comment by yorhodes** [comment]
tesnet
![Screen Shot 2022-07-18 at 11 51 10 PM](https://user-images.githubusercontent.com/3020995/179660775-db32557a-9d95-4b4a-8606-a005e399a1d2.png)
