### ISSUE TITLE
Only process messages with non-zero interchain gas payments

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#759]
Blocked on #758 

* This issue requires communicating with FlowCarbon, Toucan, and any others building upon Abacus and make sure they're already paying interchain gas and are aware that we will be no longer processing messages without gas payments.
* We should first make sure this is very clear in documentation before actually changing any infrastructure. We can indicate that this is already live in the docs before actually making the infrastructure change to err on the side of safety
* Deploy the relayers with the minimum gas payment as `1`

**Comment by jennifermarie** [comment]
Blocked by conversations with Flowcarbon and Toucan.

**Comment by nambrot** [comment]
Closing this if you agree @tkporter
