### ISSUE TITLE
Providing a GRR-like experience with the relayers before full GRR

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#760]
(GRR = grief-resistant-relayer)

* https://github.com/abacus-network/abacus-monorepo/issues/758
* https://github.com/abacus-network/abacus-monorepo/issues/759
* https://github.com/abacus-network/issues/issues/96
* https://github.com/abacus-network/abacus-monorepo/issues/766

TODO: add more tickets here - I'm OOO today / tomorrow but will resume once back

**Comment by jennifermarie** [comment]
@tkporter @nambrot is this epic complete, or are there additional tickets needed? (pruning the board and saw the TODO in the issue)

**Comment by nambrot** [comment]
My understanding is that this is basically done as #759 is done as well?

**Comment by tkporter** [comment]
Originally I was thinking https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/759 would be actually flipping the switch on charging 1 wei for messages, but I think that's gonna take some time to happen, so yes happy to close this

I think it may be worth a new epic to track the transition to full GRR though?
