### ISSUE TITLE
Transition over to Goerli or Sepolia as the ETH test network

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#761]
We have been using Kovan as our ETH testnet due to its availability of testnet funds, but it is deprecated (for a while already). I do expect Kovan to continue running for quite a while. Optimism is planning on migrating to Goerli https://twitter.com/optimismFND/status/1542589602329919490

Thus, we should likely be moving to Goerli as well. This can be a good test case for testing enrollment of new chains, both for the core platform and for applications

**Comment by asaj** [comment]
We did this!
