### ISSUE TITLE
Remove rust agent configs from typescript/infra

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#779]
Some behavior in `typescript/infra` writes the rust agent json config to `typescript/infra/config/environments/${env_name}/core/rust/`, but we may as well just write directly to `rust/config/${env_name}/` and avoid the duplicate configs in `typescript/infra`. The `typescript/infra` content is just clutter at this point.

We should:
* Change any rust agent config writing in `typescript/infra` to write directly into the correct place in `rust/config`
* Remove any rust agent configs in `typescript/infra`

**Comment by asaj** [comment]
We did this!
