### ISSUE TITLE
More verbose agent logging in our own infrastructure

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#781]
* Atm we run with just `info`, which makes it hard to debug. We should operate with a higher verbosity as we gain more operational expertise-- it's better to generously log than not be able to see `debug` logs that we need when debugging.
* Annoyingly, just setting the relayer to use `debug` causes a bunch of network-related logs from the `hyper::` and `rusoto_core::` targets. We should try to just show debug logs that originate from our own code-- e.g. for the relayer, only log `relayer::` logs as `debug`

**Comment by nambrot** [comment]
Talked offline, we'll bumb certain messages from debug to info so that we can address https://github.com/abacus-network/abacus-monorepo/issues/784

**Comment by asaj** [comment]
I believe we've done this
