### ISSUE TITLE
Don't increment `messages_processed_count` when a relayer isn't responsible for the processing

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#783]
I noticed that upon starting up a relayer with a wiped DB, when the relayer attempts to process a message and realizes by checking the Inbox for the message status that the message has already been processed (i.e. [here](https://github.com/abacus-network/abacus-monorepo/blob/main/rust/agents/relayer/src/msg/serial_submitter.rs#L210)), it'll call `self. record_message_process_success`, which will increment the `messages_processed_count` counter [here](https://github.com/abacus-network/abacus-monorepo/blob/main/rust/agents/relayer/src/msg/serial_submitter.rs#L273).

This results in some misleading metrics because I'd expect that counter to count the total # of messages the relayer has actually processed since startup. A few graphs / alerts rely upon this metric meaning the # of messages the relayer has been responsible for processing, so I think we should make a change to not increment this if the relayer didn't actually process the message

**Comment by webbhorn** [comment]
Yeah, I thought about this case when writing `record_message_process_sucess()`, but at the time hoped that this case would be sufficiently rare that we could get away with the simplicity of not special-casing already-processed messages, to the extent that the rate metric is useful over the majority of time intervals.

But it is not too hard to make this precise, I don't mind fixing it if that's preferable.
