### ISSUE TITLE
Remove rust-based kathy

### ISSUE THREAD

**Issue by asaj** [hyperlane-xyz/hyperlane-monorepo#799]
Following https://github.com/abacus-network/abacus-monorepo/pull/636, Rust-Kathy isn't used anymore. We should remove Kathy from the Rust code and all Rust-kathy code from infra (found in the agent deployment code)

**Comment by webbhorn** [comment]
Cross-referencing my abandoned attempt in #713, because @tkporter left a nicely detailed comment outlining some specific places to clean up related typescript infra

**Comment by asaj** [comment]
#713 got merged!
