### ISSUE TITLE
The "mainnet no messages processed from an origin in 24h" alert should be robust to relayer restarts

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#809]
Upon restarting relayers (or deploying a new one), the "mainnet no messages processed from an origin in 24h" is fired. The query should be robust to restarts. See the screenshot for context:
<img width="1147" alt="Screen Shot 2022-07-21 at 11 24 49 AM" src="https://user-images.githubusercontent.com/20362969/180179705-646eb02a-f237-4d9c-a151-ff77297ba533.png">

**Comment by asaj** [comment]
I believe we've fixed this
