### ISSUE TITLE
Serve Message Explorer API

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#814]
Should probably use something a la https://www.moesif.com/blog/graphql/technical/Ways-To-Add-GraphQL-To-Your-Postgres-Database-Comparing-Hasura-Prisma-and-Others/

**Comment by mattiecnvr** [comment]
Let's plan on Hasura unless for some reason it is just not going to work for our needs, then we can revisit and consider building a custom server.

**Comment by jmrossy** [comment]
Live at api.hyperlane.xyz
