### ISSUE TITLE
MultiProvider and AbacusCore types should be less heavy

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#819]
Right now the types of MultiProvider and AbacusCore express the specific networks that they support at compile time, however depending on your setup (like we do in infra with `CoreConfig`), you don't actually have the concrete types if you wanna abstract the environment. This leads to very annoying type errors. Instead, we should simplify the type overhead and rely more on runtime incompatibilities like introduced in #394

**Comment by jmrossy** [comment]
Fixed a while back
