### ISSUE TITLE
InterchainGasCalculator for L2

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#835]
IGC does not work for L2 as the IGC assumes L1-style single dimension `gasPrice` and `gas`

i think the truly right approach would be to
$1 have rough estimates for the l2 tx calldata size required for a particular validator set size (+merkle proof + message data)
$2 estimate l1 fee based on that calldata
$3 estimate l2 execution gas for handle function

Return: l1_gasPrice * $2 + l2_gasPrice * (systemOverheadGas + $3)

**Comment by asaj** [comment]
The IGC is no more
