### ISSUE TITLE
Investigate merging domain specific Inbox instances

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#855]
domain specific inboxes require developers to implement access control which is domain aware for multiple addresses
a single access control address would be much simpler as an API

**Comment by asaj** [comment]
Inboxes currently only have two pieces of state:
- Message status
- IVM address

You could imagine making IVM status a mapping from domain to address. Message status is already keyed by global UID. This allows you to combine the Inboxes into a single contract.

The tricky bit here is in migrating from the current, multi-inbox model, to the single inbox model. A few options:
1. Deploy entirely new Outbox/Inbox contracts. Existing applications, validators, and relayers would need to migrate.
2. Deploy new Inbox contracts, modify the message status function for the new Inbox to query the previous Inbox contracts. Applications need to abandon the old Inboxes before adopting the new Inbox. *Eventually*, we can deprecate the old Inboxes by encoding a per-domain "high water mark" in the new Inboxes, before which messages will be rejected. Applications would not need to change outbox contracts, but *would* need to migrate Inbox contracts. Validators wouldn't need to do anything. Relayers would need to be spun up for the new Inbox contracts. 

(1) is cleaner but a larger lift for partners. (2) is messier (and thus riskier), but minimizes work for other parties (mostly validators)
