### ISSUE TITLE
Investigate merging send and payfor API

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#858]
`Outbox.dispatch` and `InterchainGasPaymaster.payGasFor` are conveniently bundled in our library code but remain cumbersome to use from an API perspective. We could consider folding interchain gas message processing payment directly into the `dispatch` API. LZ leans heavily into this single endpoint simplicity.

**Comment by asaj** [comment]
I believe we decided not to do this cc @tkporter
