### ISSUE TITLE
SDK abstractions should throw an error if chains in configuration are not covered by multiprovider

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#877]
https://github.com/abacus-network/abacus-monorepo/issues/394 was fixed by using the intersection between chains in the configuration and the chains of the multiprovider.

There is an argument that this will be surprising to developers. In a world in which one uses an app-independent multiprovider (like `infra` does), imo it would be surprising to get a subset of the chains in the configuration. Instead, the abstractions could throw an error and force the developer to adjust the configuration if the subset is desired

**Comment by asaj** [comment]
I believe we've done this
