### ISSUE TITLE
HIP: On-Chain Circuit breaker

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#884]
Learning from the Nomad hack, we should consider adding circuit breakers to inboxes that tradeoff liveness for safety.

Conditions could be the observation of messages that are processed that an offchain agent does not have observed dispatches for

**Comment by asaj** [comment]
Closing in favor of https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1347
