### ISSUE TITLE
Explore what it would take to offer a version of the API that uses address and not bytes32

### ISSUE THREAD

**Issue by asaj** [hyperlane-xyz/hyperlane-monorepo#921]
Developers often get tripped up over the idea that Outbox.dispatch takes a bytes32, and (somewhat less so) over the idea that handle() takes a bytes32.

The motivation behind this awkwardness was to support non-EVM chains in the future, whose identifiers may be 32 bytes.

This ticket is to design a migration plan from the current bytes32-only API to one that supports addresses. It should prioritize zero or minimal changes for existing users, and as such will *likely* require that bytes32 compatibility be maintained.

**Comment by yorhodes** [comment]
https://github.com/abacus-network/abacus-monorepo/blob/main/solidity/core/contracts/libs/Message.sol#L96 the core message encoding supports decoding to addresses

**Comment by asaj** [comment]
I believe we decided not to do this cc @nambrot
