### ISSUE TITLE
Cache token prices for the `CoinGeckoTokenPriceGetter` in the SDK

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#949]
At the moment, each time the InterchainGasCalculator is used, token price API calls to CoinGecko (using the `CoinGeckoTokenPriceGetter`) are made. Due to CoinGecko API rate limiting, this causes errors if the IGC is used very frequently. We should cache prices in the `CoinGeckoTokenPriceGetter`.

Concretely:
* Cache token prices in the `CoinGeckoTokenPriceGetter` (or possibly do the caching at a higher level abstraction, if that feels appropriate)
* Come up with a reasonable TTL for prices so that a new price is fetched if the cached one is too old.

**Comment by asaj** [comment]
We did this!
