### ISSUE TITLE
Scraper: estimate gas to enrich with current message processing status

### ISSUE THREAD

**Issue by mattiekat** [hyperlane-xyz/hyperlane-monorepo#972]
Created from #885 

- Find pending transactions
- Periodically estimate gas and write results to database

**Comment by mattiecnvr** [comment]
This is part of a class of updates to the scraper to add live data that will change over time and cannot be scraped after the fact.

**Comment by nambrot** [comment]
Closing in favor of https://github.com/hyperlane-xyz/issues/issues/868
