### ISSUE TITLE
rs CI jobs being skipped when they should be run

### ISSUE THREAD

**Issue by asaj** [hyperlane-xyz/hyperlane-monorepo#981]
Has led to failed CI on main

See https://github.com/abacus-network/abacus-monorepo/pull/934 for an example of a PR where lint-rs, test-rs, build-rs all ran the "skipped" versions despite rust changes

**Comment by mattiecnvr** [comment]
Ooops, that's what I get with auto-merge. The issue specifically here is not that the regular workflow did not run, but rather that the rust-skipped workflow _also_ ran (and it will always run faster so it gives the green light). What we need ideally is to make the rust-skipped workflow run exclusively when the rust workflow is not running. i.e. the condition for it to run should be a perfect inverse of the rust workflow.

**Comment by asaj** [comment]
@mattiecnvr you're exactly right. Unfortunately, my understanding of `paths` and `paths-ignore` do not allow you to do this, despite it being the recommended solution:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

What we need is probably something based on conditionals:
https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#overview

**Comment by nambrot** [comment]
Pretty sure this is done now
