### ISSUE TITLE
Prevent replayable slashes on `OutboxValidatorManager`

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#982]
The `OutboxValidatorManager` does not check for proof/root reuse. Once the `Outbox` is `fail()`ed, subsequent calls have no effect. However, when economic slashing is added to the `OutboxValidatorManager`, care must be taken to prevent validators from being slashed multiple times with the same evidence.

**Comment by asaj** [comment]
No longer relevant for v2 for now, closing
